### ISSUE TITLE
“忘记密码”500错误

### ISSUE THREAD

**Issue by Jarvanh** [orvice/ss-panel#104]
是信息填写错了么
![](http://i.imgur.com/nncv4uh.png)

**Comment by orvice** [comment]
域名填写错了
比如我写的是
cattt.me

**Comment by Jarvanh** [comment]
这样子么？

![](http://i.imgur.com/HSBeXCn.png)

![](http://i.imgur.com/U05UqKZ.png)

**Comment by Jarvanh** [comment]
貌似是这儿出问题了？


root@default:~# curl -sS https://getcomposer.org/installer | php
Failed loading /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/opcache.so:  /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/opcache.so: cannot open shared object file: No such file or directory
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /root/composer.phar
Use it: php composer.phar
root@default:~# php composer.phar  install
Failed loading /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/opcache.so:  /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/opcache.so: cannot open shared object file: No such file or directory
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

**Comment by orvice** [comment]
你的环境是啥？

**Comment by Jarvanh** [comment]
lanm
2015年4月26日 下午2:42于 "orvice" <notifications@github.com>写道：

**Comment by orvice** [comment]
删除下 composer.lock
在执行下 php composer.phar  install

**Comment by Jarvanh** [comment]
![6](https://cloud.githubusercontent.com/assets/5900885/7336285/e8ec60b0-ec28-11e4-8f61-b820fc880370.jpg)

**Comment by Jarvanh** [comment]
原来是编译php的时候没有加上Zend Opcache参数，谢谢您的帮忙

**Comment by akw28888** [comment]
不需要opcache的吧
PHP 7.0.0-dev (cli) (built: Mar 30 2015 00:13:31)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

我的沒opcache 正常

**Comment by Jarvanh** [comment]
额，那是怎么回事
2015年4月26日 下午6:58于 "akw28888" <notifications@github.com>写道：

**Comment by Jarvanh** [comment]
额，那是怎么回事

应该就是 php composer.phar install 出错了

**Comment by liuchao0130** [comment]
怎么解决的 我一直是500错误 。

**Comment by Jarvanh** [comment]
你需要cd 到ss-panel目录运行这两条命令，而不是root目录

$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar install
