### ISSUE TITLE
註冊用戶數據庫中不增加

### ISSUE THREAD

**Issue by mindlc** [orvice/ss-panel#108]
更新完2.2.4，新註冊用戶，提示註冊成功，但是無法登錄，查看數據庫無新數據。

**Comment by mindlc** [comment]
另外，找回密碼提示錯誤500，確認mailgun api和域名設置正確，之前的0.X.X版本郵件正常，更新了2.2.4就不行了。

**Comment by orvice** [comment]
需要执行这些命令 https://github.com/orvice/ss-panel#send-mail-using-mail-gun
以及需要修改数据库 https://github.com/orvice/ss-panel/blob/master/upgrade_to_v2.md

**Comment by mindlc** [comment]
Thanks.
