### ISSUE TITLE
几个js相关错误

### ISSUE THREAD

**Issue by Gav1nMa** [orvice/ss-panel#110]
1、
/index.php中末尾链接的这个JS文件并不存在：
/assets/js/ie10-viewport-bug-workaround.js
2、
/header.php中链接的这个JS文件并不存在：
/asset/js/ie-emulation-modes-warning.js
3、
/asset/plugins/slimScroll/jquery.slimscroll.min.js
此JS文件在两个_footer.php中调用时为：jquery.slimScroll.min.js，实际命名为：jquery.slimscroll.min.js，大小写错误。

**Comment by qyidc** [comment]
这个js已经添加，可是在ie9下仍无法正常登陆！
