### ISSUE TITLE
重置密码代码有问题

### ISSUE THREAD

**Issue by thank243** [orvice/ss-panel#113]
点击重置密码提示500错误，查找日志发现。
2015/04/29 22:07:56 [error] 11194#0: *88922 FastCGI sent in stderr: "PHP message: PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in /usr/www/ss_panel/user/_resetpwd.php on line 6

继续查找此文件没发现没有vendor文件夹。

**Comment by orvice** [comment]
查看readme
https://github.com/orvice/ss-panel#send-mail-using-mail-gun
需要在当前目录执行如下代码
```
$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar  install
```

**Comment by thank243** [comment]
已解决，需要在ss_panel目录下运行。

2015-04-29 22:20 GMT+08:00 orvice <notifications@github.com>:

**Comment by yanest** [comment]
我怎么安装有错误呢
```
root@i-g7w6tq1b:/var/www/html# curl -sS https://getcomposer.org/installer | php

#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /var/www/html/composer.phar
Use it: php composer.phar
root@i-g7w6tq1b:/var/www/html# 
root@i-g7w6tq1b:/var/www/html# php composer.phar  install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzle/guzzle v3.9.3 -> satisfiable by guzzle/guzzle[v3.9.3].
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - mailgun/mailgun-php v1.7.2 requires guzzle/guzzle <4.0,>=3.8 -> satisfiable by guzzle/guzzle[v3.9.3].
    - Installation request for mailgun/mailgun-php v1.7.2 -> satisfiable by mailgun/mailgun-php[v1.7.2].
```

**Comment by thank243** [comment]
����������������������������

�������� iPhone

> �� 2015��5��17����21:01��yanest <notifications@github.com> ������
> 
> requires ext-curl * -> the requested PHP extension curl is missing from your system. Problem 2 - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system. - mailgun/mailgun-php v1.7.2 requires guzzle/guzzle <4.0,>=3.8 -> satisfiable by

**Comment by orvice** [comment]
requested PHP extension curl is missing from your system.


curl扩展没装





—

**Comment by liuchao0130** [comment]
我把com…….lock删除 重新运行了一遍 还是错误 。啊  怎么解决
[root@li889-159 default]# curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /data/www/default/composer.phar
Use it: php composer.phar
[root@li889-159 default]# php composer.phar  install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Removing symfony/event-dispatcher (v2.6.6)
  - Installing symfony/event-dispatcher (v2.7.2)
    Downloading: 100%         

Writing lock file
Generating autoload files

**Comment by thank243** [comment]
去ss-panel根目录运行

发自我的 iPhone

**Comment by liuchao0130** [comment]
我就是在ss-panel根目录运行的

**Comment by liuchao0130** [comment]
我把ss-panel的文件全部拷到default  ，就相当于换了个目录名而已

**Comment by thank243** [comment]
第二次不是安装成功了？

发自我的 iPhone
