### ISSUE TITLE
用户管理手动设置流量大小无效

### ISSUE THREAD

**Issue by kaneawk** [orvice/ss-panel#116]
v2.2.5版本。无法进行手动设置用户流量。。

**Comment by orvice** [comment]
用户管理还没完成。

**Comment by kaneawk** [comment]
Okay, I'm a little impatient about this.
In fact,couldn't manage users was very awful...Waiting you completed,Thanks.2333

**Comment by Mujj** [comment]
这样的？
![20150502175650](https://cloud.githubusercontent.com/assets/3275231/7440667/b793d266-f0f4-11e4-9206-cfeacac7de39.png)
![20150502175709](https://cloud.githubusercontent.com/assets/3275231/7440669/bd2dd532-f0f4-11e4-8bb2-20c3c32894d9.png)

**Comment by kaneawk** [comment]
是啊是啊。就是这样的。。求提交。^_^

**Comment by Mujj** [comment]
<div class="form-group">
                                <label for="cate_title">设置流量</label>
                                <input type="hidden" name="transfer_enable_hidden" value="<?php echo $rs['transfer_enable'];?>" >
                                <input   class="form-control" name="transfer_enable"  placeholder="单位为GB，直接输入数值" >
                            </div>
仿照原有的加一句就好啦。

**Comment by kaneawk** [comment]
不是，这里修改什么都修改不了。根本写不进数据库。

**Comment by Mujj** [comment]
lib 里面还有个文件需要加一句。忘记具体是哪里了，我找别人帮我加的。

**Comment by kaneawk** [comment]
额。求提取出来我对比一下就可以。。

**Comment by shuangzhijinghua** [comment]
同求
