### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by 604542720** [orvice/ss-panel#186]
1.admin index 页面的get_month_traffic()  命名 与 Ana.php 中的方法命名不一致。
2.admin界面的用户修改按钮点击无反应 。

**Comment by 604542720** [comment]
fix  
$mt = $ssmin->getMonthTraffic();
$active_user = $ssmin->activedUserCount();
$all_user    = $ssmin->allUserCount();
$node_count  = $ssmin->nodeCount();

**Comment by 604542720** [comment]
admin/user_edit 增加 jQuery 文件
<script src="../asset/js/jQuery.min.js"></script>

加了之后updateUser还是执行有错误。。。。提示说
sh: user_name: command not found
sh: email: command not found
(current) UNIX password: passwd: Authentication token manipulation error
sh: transfer_enable: command not found
不太懂这是啥意思啊。。？

**Comment by liuchao0130** [comment]
我想问下： 
admin/user_edit 增加 jQuery 文件
src="../asset/js/jQuery.min.js"
这个加哪里 啊  ，怎么加啊，麻烦详细一点点

**Comment by liuchao0130** [comment]
为什么我按照这个修改了，还是 点 修改按钮无效呢

**Comment by liuchao0130** [comment]
解决了， 楼主还要加上一句： #188
才能解决问题

**Comment by 604542720** [comment]
加jq文件也可以，你看我写的第一条
