### ISSUE TITLE
admin/_user_edit.php中 $email变量没设置

### ISSUE THREAD

**Issue by ilazycat** [orvice/ss-panel#189]
$uid = $_POST['user_uid'];
    $name = $_POST['name'];
    $passwd = $_POST['passwd'];
    $transfer_enable = $_POST['transfer_enable'];
    $invite_num = $_POST['invite_num'];

少了$email导致出问题，加上就好

$uid = $_POST['user_uid'];
    $name = $_POST['name'];
    $email = $_POST['email'];
    $passwd = $_POST['passwd'];
    $transfer_enable = $_POST['transfer_enable'];
    $invite_num = $_POST['invite_num'];

**Comment by 604542720** [comment]
已经发过了，见#186
