### ISSUE TITLE
页面无法打开

### ISSUE THREAD

**Issue by PaytonShaw** [orvice/ss-panel#191]
一个奇怪的现象，如果没有lib/config.php，则主页可以打开，注册登录等页面打不开。
如果有config.php,则全部页面打不开。

PHP 5.4.41
MYSQL 5.5.40
nginx-generic-1.6.0

**Comment by 70599** [comment]
config.php配置错误就会白板。
检查config.php配置。

**Comment by PaytonShaw** [comment]
已经仔细检查过了，似乎没有问题啊。

**Comment by angelina999990** [comment]
同样的问题

**Comment by orvice** [comment]
数据库连接不上就会白
