### ISSUE TITLE
忘记密码，提示500错误

### ISSUE THREAD

**Issue by liuchao0130** [orvice/ss-panel#197]
这个设置搞了我很久很久 ，请帮我看下哪里的问题。   还是一直提示 500错误。。

![2](https://cloud.githubusercontent.com/assets/13215589/8888631/63397780-32e8-11e5-9975-728a6c0315bf.jpg)
![3](https://cloud.githubusercontent.com/assets/13215589/8888635/84155942-32e8-11e5-9039-db82ab2ebe80.jpg)

**Comment by liuchao0130** [comment]
刚才 我看到有人说是因为没有安装 php-curl
我就安装了一次  yum install php-curl
![4](https://cloud.githubusercontent.com/assets/13215589/8888649/18616794-32e9-11e5-8db7-1ad5d3d1a857.jpg)
![6](https://cloud.githubusercontent.com/assets/13215589/8888653/2f2bcaf0-32e9-11e5-9586-b9c5842e9256.jpg)

**Comment by kozora** [comment]
500错误就是mailgun这边环境的问题，多谷歌一下，btw:珍爱生命，远离centos。。

**Comment by orvice** [comment]
mailgun那边添加个域名试试看

**Comment by liuchao0130** [comment]
怎么加？？

**Comment by kozora** [comment]
善用谷歌。。

**Comment by a1ickgu0** [comment]
光看500没有用，把php.ini里的displayerror打开之后再看页面的错误提示吧。

**Comment by liuchao0130** [comment]
把displayerror 设置为on， 重置还是提示  500错误。没有其他信息

**Comment by evilkong** [comment]
试试在config.php最后一句：
require_once 'do.php';
的前面加上
ini_set("display_errors", "On"); 
error_reporting(E_ALL | E_STRICT);

整个面板确实有不少地方有些小错误。

**Comment by 604542720** [comment]
学会去查技术文档，就很轻松的解决各种问题了。

**Comment by Jarvanh** [comment]
你需要cd 到ss-panel目录运行这两条命令，而不是root目录

$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar  install
