### ISSUE TITLE
注册页面不兼容和腾讯邮箱无法收到mailgun的邮件

### ISSUE THREAD

**Issue by liuchao0130** [orvice/ss-panel#203]
1、 注册页面不兼容，很大一部分人都使用不了啊，大家有没有什么解决方法？
2、我设置了mailgun,， 然后找回密码，提示成功。 但是腾讯邮箱一直都无法收到邮件，怎么办？
![1](https://cloud.githubusercontent.com/assets/13215589/8932666/14b7146a-3571-11e5-8b64-a2dc92067868.jpg)

**Comment by orvice** [comment]
1 你是什么浏览器?
2  腾讯邮箱对IP的发件限制  会考虑smtp

**Comment by liuchao0130** [comment]
注册页面感觉不是挑浏览器而且跟系统有关， 有些电脑就会这样，无论什么浏览器都这样，有些电脑无论哪个浏览器都没问题 。大概有40%的用户打开会有问题。

**Comment by liuchao0130** [comment]
重置密码 好像可以用了，但是有一个新情况 ，这个怎么解决 求方案。。。如图
![qq 20150730110658](https://cloud.githubusercontent.com/assets/13215589/8975032/ad3cec24-36ab-11e5-942d-6dc466b551b5.jpg)

**Comment by liuchao0130** [comment]
没事了，我以为这个是MD5加密密码， 原来不是，这个就是密码！！！！我去　这么长的密码，而且超级像加密过的密码。。

**Comment by liuchao0130** [comment]
经过测试 ，实际上是支持QQ邮箱的， 我用 了一段时间了 没有问题
