### ISSUE TITLE
管理员账号登录后台无法修改用户

### ISSUE THREAD

**Issue by snhun** [orvice/ss-panel#204]
登录管理后台-查看用户-用户管理，点 修改 完全没任何反应！！！

**Comment by liuchao0130** [comment]
你查看前面cloesd的提问，即可解决这个问题，提问之前先看看之前别人问题的。

**Comment by snhun** [comment]
已经按之前cloesd的问题修改了问题，点击还是没反应。
https://github.com/orvice/ss-panel/issues/186

**Comment by snhun** [comment]
也已经把
<script type="text/javascript" src="../asset/js/jQuery.min.js"></script> 
放到
<?php
require_once '_footer.php'; ?>
后面

**Comment by a1ickgu0** [comment]
参考：
https://github.com/a1ickgu0/ss-panel/commit/54323c70396c9b1470f7e43330886db2f220925d
