### ISSUE TITLE
请作者做修复

### ISSUE THREAD

**Issue by xiaoyawl** [orvice/ss-panel#209]
暂时编辑了下

**Comment by orvice** [comment]
你好，请问版本号多少
可以邮件发给我详细信息吗？
邮箱 orvice at gmail

**Comment by xiaoyawl** [comment]
你好：

应该是个存储型xss漏洞，这个检测结果是一个做安全的朋友给我做的




393411264@qq.com
 
发件人： orvice
发送时间： 2015-08-04 10:58
收件人： orvice/ss-panel
抄送： SEEDBOX-HDPT
主题： Re: [ss-panel] 请作者做修复 (#209)
你好，请问版本号多少 
可以邮件发给我详细信息吗？ 
邮箱 orvice at gmail

**Comment by orvice** [comment]
能提供下具体实现过程吗？

**Comment by xiaoyawl** [comment]
Hi

朋友暂时不在线了，他离开前和我说的是_sspwd_update.php没做任何过滤



393411264@qq.com
 
发件人： 393411264@qq.com
发送时间： 2015-08-04 11:02
收件人： orvice/ss-panel
主题： Re: Re: [ss-panel] 请作者做修复 (#209)
你好：

应该是个存储型xss漏洞，这个检测结果是一个做安全的朋友给我做的




393411264@qq.com
 
发件人： orvice
发送时间： 2015-08-04 10:58
收件人： orvice/ss-panel
抄送： SEEDBOX-HDPT
主题： Re: [ss-panel] 请作者做修复 (#209)
你好，请问版本号多少 
可以邮件发给我详细信息吗？ 
邮箱 orvice at gmail

**Comment by orvice** [comment]
谢谢反馈，稍后会处理。

**Comment by xiaoyawl** [comment]
为了安全考虑 删除了细节提供
