### ISSUE TITLE
可以注册新用户，但是打开/admin/或者/user/ 页面就超时

### ISSUE THREAD

**Issue by feisu** [orvice/ss-panel#212]
/user/register.php 可以访问并且注册，也可以登录
/user/login.php
/admin/login.php 也可以访问

但是访问/admin/或者/user/ 不对自动跳转到/login.php

会一直停留在/user/ 或者/admin/ 导致超时。请问是什么缘故？我是NGINX.

**Comment by orvice** [comment]
版本多少

**Comment by feisu** [comment]
最新版本
Powered by ss-panel <https://github.com/orvice/ss-panel> 2.4.4 Processed in
0ms Theme by Materialize <http://materializecss.com>

On Thu, Aug 6, 2015 at 2:28 PM, orvice <notifications@github.com> wrote:

> 版本多少
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orvice/ss-panel/issues/212#issuecomment-128264067>.
>



-- 
Jingzi Yang

**Comment by liuchao0130** [comment]
我去还有 2.4.4我前天才装完2.4.3

**Comment by xuanhuan** [comment]
哎。。。我还在改2.2.9....

**Comment by liuchao0130** [comment]
哈， 是啊 版本升级好麻烦啊， 自己增加了那么多功能， 真实不好升

**Comment by PlaneV** [comment]
把修改的代码贡献出来不就可以和大家一起升级了，你也不会这么麻烦了嘛
2015年8月6日 下午6:14于 "liuchao0130" <notifications@github.com>写道：

**Comment by 604542720** [comment]
然而伸手党并没有开源精神233333

**Comment by xuanhuan** [comment]
在这啊 https://github.com/xuanhuan/ss-panel
我也有向orvice发邮件，提义他建一个smarty分支，然后推送过来给大家用的，可是他并没回复我。。。
为什么是smarty分支，因为是基于smarty模板引擎做的二次修改，保留了原版，又新增了Material Design风格模板materialize。

**Comment by orvice** [comment]
我回复你了



—
通过 Mailbox 发送

**Comment by xuanhuan** [comment]
刚才看到了，这几天没上GMAIL

**Comment by akw28888** [comment]
雖然可能有點奇怪 但是借樓問一下
@xuanhuan 大的smarty分支, 註冊頁面點了沒反應 (8/2的版本 revert到7/30的版本是可以的)

**Comment by xuanhuan** [comment]
不支持ie11以下浏览器，请用Chrome内核之类的浏览器。

**Comment by xuanhuan** [comment]
。。。刚才试了一下，发现改了一下id...
if(document.getElementById("agree").checked===false){
                            id_name=".tos";
                            msg_out("必须要同意<a href=\"#!\" onclick=\"$('#TOSINFO').openModal();\" >《用户协议》</a>才可以注册!","error");
                            msg_id=1;
                            return false;
                        }
你改一下这个验证同意用户协议的。

**Comment by akw28888** [comment]
好的 稍後去cherry-pick一下

**Comment by dotedu** [comment]
请问这个版本怎么区分用户查看节点？免费和PRO节点
