### ISSUE TITLE
重置密码 发生错误：200

### ISSUE THREAD

**Issue by mac-zhou** [orvice/ss-panel#214]
PHP Fatal error:  Uncaught exception 'Mailgun\\Connection\\Exceptions\\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs!'

**Comment by mac-zhou** [comment]
日志：
[Fri Aug 07 03:48:30.812961 2015] [:error] [pid 27958] [client 122.96.25.42:64529] PHP Fatal error:  Uncaught exception 'Mailgun\\Connection\\Exceptions\\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs!' in /btr/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:127\nStack trace:\n#0 /btr/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\\Connection\\RestClient->responseHandler(Object(Guzzle\\Http\\Message\\Response))\n#1 /btr/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\\Connection\\RestClient->post('sandbox6a755069...', Array, Array)\n#2 /btr/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\\Mailgun->post('sandbox6a755069...', Array, Array)\n#3 /btr/ss-panel/user/_resetpwd.php(25): Mailgun\\Mailgun->sendMessage('sandbox6a755069...', Array)\n#4 {main}\n  thrown in /btr/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 127, referer: http://mac-zhou.com/user/resetpwd.php

配置：

//
//选择邮件服务
// smtp未完成，现在只能用mailgun
//mail-gun
//mail-smtp
$Selectmailservice = "mail-gun";
//邮件发件人
$sender = "xxxxx@live.com";

//mail-gun
// Get your key from https://mailgun.com
$mailgun_key = "key-73ce80efd3dadb92ad93b8c5";
$mailgun_domain = "sandbox6a75506901aa4a300b2b90fc8dd.mailgun.org";


//
//mail-smtp
// smtp发件方式暂时无法使用
//设置smtp服务器连接方式:  
//加密连接(ssl) = "1"
//普通连接 = "0"
$mail_smtp_Connection = "1";
//smtp服务器端口 25 , 465 ...
$mail_smtp_Port = 465;
//smtp服务器
$mail_smtp_Server = "smtp.gmail.com";
//邮件帐号
$mail_smtp_Account = "xxxx@gmail.com";
//邮件密码
$mail_smtp_password = "密码";

正好我有个账号的email为 xxxxx@live.com ,  跟配置$sender是一致的，如果重置此账号的密码是没有问题的。

**Comment by mac-zhou** [comment]
不好意思，找到问题了，密码重置一直出现500的错误，发现原来是个低级错误，我没有激活mailgun

**Comment by sunnoy** [comment]
怎么么激活mailguan呢
