### ISSUE TITLE
话说重置密码这项做的真的有点奇葩啊

### ISSUE THREAD

**Issue by 604542720** [orvice/ss-panel#215]
重置密码后发一封邮件，给个链接点击去，输入邮箱然后再发一封新的随机密码的邮件，然后还要去登陆个人中心去改成自己的密码，这样的设计真的好吗，强迫症伤不起，233333 = =

**Comment by orvice** [comment]
因为我懒，重置的时候生成密码这样比较快，重置的时候就设置密码又要多一些逻辑。
