### ISSUE TITLE
能够发送重置密码邮件但是收到的新密码都无法登陆？

### ISSUE THREAD

**Issue by Lantrancy** [orvice/ss-panel#216]
重置的新密码无法登陆

**Comment by xuanhuan** [comment]
有一种可能，文本框限制输入长度，所以只粘贴了一部分新密码，另外一部分被截断了。

**Comment by Lantrancy** [comment]
用的是带盐sha256，重置密码只写了8位，应该不会超过长度吧？重置邮件里面是很长一串的码，看上去有点不太正常

**Comment by orvice** [comment]
密码就是很长一串

**Comment by orvice** [comment]
此bug已确认，晚上会fix

**Comment by 604542720** [comment]
我用的是旧版本的密码，可以重置的 。旧版本不升级到新密码没问题吧？ = = @orvice
