### ISSUE TITLE
admin/user.php 如何实现倒序

### ISSUE THREAD

**Issue by liuchao0130** [orvice/ss-panel#221]
数据多了 ，每次都要拉下去，怎么样实现倒序排列呢？？？
这个框架我真的是看不懂 ，sql都不知道在哪里。。
求指点

**Comment by xuanhuan** [comment]
这个问题我已经解决了，在明天的smarty分支更新里面会有。

**Comment by liuchao0130** [comment]
谢谢，分支地址可否提供一下。

**Comment by xuanhuan** [comment]
https://github.com/xuanhuan/ss-panel/tree/smarty
现在合拼的分支还有一点小问题（文件冲突）待解决，明天合拼过来。

**Comment by myfingerhurt** [comment]
这个排序功能到V3以后被取消了吗？我也有同感，本来想自己改，结果发现看不明白代码。。。。各种第三方库直接晕死，好不容易找到了分页的函数，参数比官方库多两个，结果找不到函数定义。。。。。

**Comment by hudson6666** [comment]
app/Controllers/Admin/UserController.php的第19行
按注册顺序倒序
`$users = User::orderBy('id','desc')->paginate(15, ['*'], 'page', $pageNum);`
按最后在线时间排序
`$users = User::orderBy('t','desc')->paginate(15, ['*'], 'page', $pageNum);`
