### ISSUE TITLE
请问SS-PANEL如何更改签到方式?

### ISSUE THREAD

**Issue by ArnaudGithub** [orvice/ss-panel#224]
//check is able to check in
    function is_able_to_check_in(){
        $now = time();
        if( $now-$this->get_last_check_in_time() > 3600*22 ){
            return 1;
        }else{
            return 0;
        }
    }

看到这里相关代码，在数据库获取最后签到时间再3600*22 请问如何改为GMT+8的凌晨0点00分签到！ 
非常感谢！

**Comment by PlaneV** [comment]
//check is able to check in
    function is_able_to_check_in(){
    //更改为每日0时起可以开始当天的签到，如果当前日子大于最后签到日期的日子则返回“1”
        $now = time();
        if (date('Ymd',$this->get_last_check_in_time()) < date('Ymd',$now)){
            return 1;
        }else{
            return 0;
        }
    }

2015-08-16 0:08 GMT+08:00 ArnaudGithub <notifications@github.com>:
