### ISSUE TITLE
user/_main.php 

### ISSUE THREAD

**Issue by soaper** [orvice/ss-panel#229]
<li  >
                    <a href="sys.php">
                        <i class="fa fa-align-left"></i> <span>系统信息</span>
                    </a>
                </li>

改为
     <li>
                    <a href="sys.php">
                        <i class="fa fa-align-left"></i> <span>系统信息</span>
                    </a>
                </li>

**Comment by orvice** [comment]
不懂你意思

**Comment by Seevil** [comment]
@orvice 用户是不需要这个的，放到admin目录下，给管理员用。（管理员竟然没有这个功能。。）

**Comment by orvice** [comment]
这个没有说管理员才可以看。
如果觉得只有管理员可以看就自己设置下
