### ISSUE TITLE
请问邮件重置密码怎么用？

### ISSUE THREAD

**Issue by TobeHu** [orvice/ss-panel#235]
我按照mailgun里面设置了，但是没有用，一直是500错误，不知道有没有详细的说明，或者教程呢？

**Comment by orvice** [comment]
mailgun域名有验证嘛

**Comment by LongTaiJun** [comment]
SMTP邮件没法用吗？

**Comment by TobeHu** [comment]
域名验证过了，SMTP支持了吗？我看备注说暂时不支持，特意去注册的mailgun

**Comment by TobeHu** [comment]
//选择邮件服务
// smtp未完成，现在只能用mailgun
//mail-gun
//mail-smtp
$Selectmailservice = "mail-gun";
//邮件发件人
$sender = "xxx@xxx.xx";
//mail-gun
// Get your key from https://mailgun.com
$mailgun_key = "";
$mailgun_domain = "";
//
//mail-smtp
// smtp发件方式暂时无法使用
//设置smtp服务器连接方式:  
//加密连接(ssl) = "1"
//普通连接 = "0"
$mail_smtp_Connection = "1";
//smtp服务器端口 25 , 465 ...
$mail_smtp_Port = 465;
//smtp服务器
$mail_smtp_Server = "smtp.gmail.com";
//邮件帐号
$mail_smtp_Account = "xxxx@gmail.com";
//邮件密码
$mail_smtp_password = "密码";


这两个应该用哪个？还是2个都需要填呢？smtp现在可以用了吗？谢谢

**Comment by orvice** [comment]
只需要mailgun
SMTP写了也没用

**Comment by TobeHu** [comment]
明白了，另外麻烦再问您一下
使用mailgun的话是不是只填这3项就可以了？像我这样的填写是正确的吗？服务器上需不需要安装postfix这样的软件呢？
第一次用这里，怎么不能像楼上你那样引用回复呢。。。抱歉
![mailgun](https://cloud.githubusercontent.com/assets/13883762/9408746/df803cb0-4847-11e5-990f-94dd9e5505ec.jpg)

**Comment by orvice** [comment]
compser install有运行就ok
