### ISSUE TITLE
ERROR 1115 (42000): Unknown character set: 'utf8mb4' ERROR 1146 (42S02): Table 'ss_panel.user' doesn't exist

### ISSUE THREAD

**Issue by KingHanWen** [orvice/ss-panel#244]
ERROR 1115 (42000): Unknown character set: 'utf8mb4'
ERROR 1146 (42S02): Table 'ss_panel.user' doesn't exist

**Comment by orvice** [comment]
需要升级mysql了

**Comment by KingHanWen** [comment]
`user_name` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
你这个编码~utf8mb4   改成utf-8 就好了  不知道会不会出问题
