### ISSUE TITLE
大神 报错了啊

### ISSUE THREAD

**Issue by KingHanWen** [orvice/ss-panel#245]
Parse error: syntax error, unexpected '[', expecting ')' in /ss-panel/lib/do.php on line 42

**Comment by orvice** [comment]
php版本要求5.4+

**Comment by KingHanWen** [comment]
[root@iZ62hujsgaiZ ~]# php -v
PHP 5.6.13 (cli) (built: Sep 15 2015 19:53:31) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by KingHanWen** [comment]
我错了 使用中的php不是这个版本  sorry
