### ISSUE TITLE
port没有连续，还有办法让他连续起来吗

### ISSUE THREAD

**Issue by liuchao0130** [orvice/ss-panel#248]
端口，port，一直都不连续生成， 现在还有办法让它变的连续吗？

**Comment by Guenlay** [comment]
php没接触过 不过你可以试试
/lib/Ss/User/Reg.php
找到 "port" => $this->GetLastPort()+rand(1,5),
修改为 "port" => $this->GetLastPort()+1,
或者 "port" => $this->GetLastPort()+rand(1,1),

**Comment by liuchao0130** [comment]
谢谢  已解决
