### ISSUE TITLE
some v3 feature

### ISSUE THREAD

**Issue by orvice** [orvice/ss-panel#262]
一些v3中可能会去做的功能

*  筛选不活跃的用户
*  smtp支持(已完成未测试)
*  API
*  认证机制,暂定为cookie,file,redis
*  多模板支持(完成)
*  优雅的链接(完成)  /code.php -> /code

v3目前进度见 [Trello](https://trello.com/b/dr62AtYI/ss-panel)
v2将不会继续开发仅做bug fix

**Comment by liuchao0130** [comment]
恩好滴  谢谢。

**Comment by noah70** [comment]
感谢作者~V2大部分功能我都做了增强，现在又到了动手的时间了~

**Comment by govpn** [comment]
有两个问题请教（win7_en+wampserver+php5.5+mysql5.5）：
1，访问密码重置页面报错“Undefined index: code in C:\wamp\www\user\resetpwd.php on line 3”，以及“乱码”；
2，密码重置页面和注册页面 点击提交按钮后报错“ 出错了!发生错误：200”
