### ISSUE TITLE
如何实现节点连接控制

### ISSUE THREAD

**Issue by liuchao0130** [orvice/ss-panel#264]
请问下，如何实现节点的控制呢， 比如： 现在端口和密码可以连接任何SS节点，只要知道了节点的IP ，
那有没有办法实现 就是 用户就算知道了节点IP 也可以让他连不上呢， 就是ss-panel的 pro 节点

**Comment by falseen** [comment]
这个需要修改ss，如果想要更完美一点的话两个都需要修改。具体做法是新增一个数据库字段，用来记录当前用户可使用的节点ip或节点序号，然后修改ss，在启动时根据数据库判断当前用户是否有权使用当前节点。

以上想法做起来也不难，ss只要做简单的修改就可以了，只是sspanel可能要修改的多一些（php我不是很懂）。如果orvice愿意做这个功能的话ss那里我可以帮忙修改。

**Comment by liuchao0130** [comment]
ss-panel ,我可以改， 就是服务端 不太会 。  - -

**Comment by glzjin** [comment]
服务端= =我可以改 用 Java 写了个多用户的壳子
2015年10月15日 下午4:24，liuchao0130 <notifications@github.com>写道：ss-panel ,我可以改， 就是服务端 不太会 。  - -

**Comment by noah70** [comment]
如果只是SS-PANEL本身，在node.php, node_json.php, node_qr.php 加一个判断语句就行了，但是这样做的缺点是如果你的用户泄露了你的服务器IP，别人一样连得上。
我的做法是修改manyuser的db_transfer.py文件，增加SQL判断就行了。

**Comment by liuchao0130** [comment]
修改manyuser的db_transfer.py文件，增加SQL判断就行了。 
这个要怎么改呢~~

**Comment by glzjin** [comment]
https://www.zhaojin97.cn/read-3289.html 这个，配合 go mu 后端。
