### ISSUE TITLE
关于登陆页面的问题

### ISSUE THREAD

**Issue by kozora** [orvice/ss-panel#270]
我现在把登陆页面换成了html的，post到哪个页面处理合适呢？ 还是把login.php底部的js代码移动到新的页面然后post到这个页面去？

**Comment by orvice** [comment]
post到user/_login.php

**Comment by kozora** [comment]
post  登录之后 显示{"code":"1","ok":"1","msg":"\u6b22\u8fce\u56de\u6765"}

**Comment by orvice** [comment]
嗯 这样应该没错

**Comment by kozora** [comment]
但是没有跳转到登录之后的页面。。

**Comment by frjalex** [comment]
@kozora ss-panel本身的登录页面使用了Ajax. 根据源码判断，你需要自己写一段js post一组json到_login.php才行。另外，_login.php返回的数据也只能用js读取的。

**Comment by kozora** [comment]
@frjalex 3Q
