### ISSUE TITLE
邮件问题。

### ISSUE THREAD

**Issue by zhwalker** [orvice/ss-panel#271]
我把我的网站整体打包迁移的另一个vps后，并重新成功执行以下两句命令，但找回密码出时现错误500，要如何解决？或者说要重新装？
<code>$ curl -sS https://getcomposer.org/installer | php</code>
<code>$ php composer.phar  install</code>

**Comment by orvice** [comment]
目录下有vendor文件夹了么

**Comment by zhwalker** [comment]
有

orvice <notifications@github.com>于2015年10月27日周二 上午9:27写道：

**Comment by zhwalker** [comment]
我是全部复制过来的

Tristan Zhang <zhwalker20@gmail.com>于2015年10月27日周二 上午9:39写道：

**Comment by orvice** [comment]
看下nginx error log？

**Comment by zhwalker** [comment]
我用的apache2,error log是在/var/log/apache2？
可是我把里面的error.log删掉之后，再在网站找回密码出现错误500，里面并没有生成error.log了。

**Comment by zhwalker** [comment]
数据库在另一个空间里有没有影响？

**Comment by zhwalker** [comment]
已经重新装了
不过还有一个问题 怎么一次性删除超过一定时间没签到的人？

**Comment by SharkIng** [comment]
如果数据库在另一个空间就要确定你能不能链接上数据库了，有些空间的数据库不能外部链接的。

**Comment by zhwalker** [comment]
可以连上，都可以登录，只是找回密码不行。

David Jiang <notifications@github.com>于2015年10月30日周五 上午9:50写道：
