### ISSUE TITLE
新版本使用的什么框架开发的

### ISSUE THREAD

**Issue by x91270** [orvice/ss-panel#272]
RT

**Comment by orvice** [comment]
基于Slim封装的一个框架
https://github.com/OzCat/LightFish

**Comment by SharkIng** [comment]
咨询下，会考虑可以让V2的升级V3么？还是说不考虑这个只能重新安装？

**Comment by orvice** [comment]
可以保留用户数据进行升级。
当然了，升级比较麻烦- -
