### ISSUE TITLE
如何全部重新分配端口?

### ISSUE THREAD

**Issue by akw28888** [orvice/ss-panel#274]
端口已經超過65535了=.=
想要全部重新分配端口

**Comment by liuchao0130** [comment]
让用户全部重新注册， 或者你手动帮所有人换端口

**Comment by falseen** [comment]
用数据库工具批量修改，比如phpmyadmin。

**Comment by orvice** [comment]
写了个脚本可以试试看
https://gist.github.com/orvice/8389c8ea97c09fe6aee6

未测试，先备份，本地试试看。。。有bugs明天修  = =

**Comment by falseen** [comment]
orvice真是个好人。。。

**Comment by akw28888** [comment]
@orvice 用了一下...端口會變成從0開始分配

**Comment by orvice** [comment]
更新了
https://gist.github.com/orvice/8389c8ea97c09fe6aee6
@akw28888

**Comment by 476210180** [comment]
@orvice 为什么端口是隔4个一分配？为何不是按序分配？

**Comment by orvice** [comment]
@476210180 
* 一个vps 能撑1w个端口也很多了，1w个端口vps能不能挂还是个问题。
*  原本是想通过端口不连续来防止被扫等问题。
