### ISSUE TITLE
请问如何设置每月流量自动清零啊

### ISSUE THREAD

**Issue by btmouse** [orvice/ss-panel#282]
就是想每个月都有固定的流量，用完了就等下个月

**Comment by a1ickgu0** [comment]
你在 Issue #273 不是问过了？

**Comment by a1ickgu0** [comment]
google ``crontab`` ，加上以下，``/var/www/html/tools/cron.php`` 根据你的实际放`` cron.php ``的位置填写 
```
  0  1  1  *  * root php /var/www/html/tools/cron.php
```
