### ISSUE TITLE
ss-node.sql导入报错诶

### ISSUE THREAD

**Issue by thsheep** [orvice/ss-panel#290]
![image](https://cloud.githubusercontent.com/assets/13295079/12059596/5bf9daf4-af99-11e5-9615-d94a3aa95be1.png)

![image](https://cloud.githubusercontent.com/assets/13295079/12059603/7abd1d66-af99-11e5-87b7-865f8c26bccb.png)

**Comment by orvice** [comment]
不用工具用cli导入呢？

**Comment by thsheep** [comment]
已经找到问题了。

[cid:c8a63d9c-8bd5-4a41-9aa6-95d69b4dd273]


创建表的时候不写数据就OK了 、MySql能够正常导入、AWS RDS需要先创建表再写数据[&#X1f61c]
________________________________
发件人: orvice <notifications@github.com>
发送时间: 2016年1月6日 3:07
收件人: orvice/ss-panel
抄送: thsheep
主题: Re: [ss-panel] ss-node.sql导入报错诶 (#290)


不用工具用cli导入呢？

―
Reply to this email directly or view it on GitHub<https://github.com/orvice/ss-panel/issues/290#issuecomment-169206305>.

[https://avatars2.githubusercontent.com/u/13295079?v=3&s=400]<https://github.com/orvice/ss-panel/issues/290#issuecomment-169206305>

ss-node.sql导入报错诶 ・ Issue #290 ・ orvice/ss-panel<https://github.com/orvice/ss-panel/issues/290#issuecomment-169206305>
github.com
