### ISSUE TITLE
邀请者显示异常

### ISSUE THREAD

**Issue by ljl024** [orvice/ss-panel#292]
###### 问题发生的过程如下：
1.了解到有*两名用户*间存在邀请关系
2.在**数据库**中修改了一名用户的**邀请者**
3.发现在**用户列表**中在被修改的用户后的**邀请者**全都显示为了那个**邀请者**
###### 数据库
|ID|用户名|...|邀请人|
|:---:|:---:|:----:|:---:|
|1|我|...| |
|2|...|...|1|
|3|...|...|1|
|...|...|...|...|
|20|用户X|...|1|
|21|...|...|20|
|22|...|...|1|
|23|...|...|1|
|...|...|...|..|
###### 显示结果
|ID|用户名|...|邀请人|
|:---:|:---:|:----:|:---:|
|1|我|...| |
|2|...|...|我|
|3|...|...|我|
|...|...|...|...|
|20|用户X|...|我|
|21|...|...|用户X|
|22|...|...|用户X|
|23|...|...|用户X|
|...|...|...|..|

**Comment by orvice** [comment]
不太明白你的意思
你怎么修改数据库的？

**Comment by ljl024** [comment]
用phpMyAdmin编辑的
只改了user表里的uid为21的用户的ref_by字段

**Comment by orvice** [comment]
无法确定是不是v2的bug
非安全问题不会继续fix
只能在v3中解决

**Comment by ljl024** [comment]
OK~
