### ISSUE TITLE
用户后台和管理后台登陆后都是空白…

### ISSUE THREAD

**Issue by MXiaohei** [orvice/ss-panel#295]
V2，使用LNMP作环境
管理后台（/admin/index.php）登陆后直接空白，无任何输出
用户后台（/user/index.php）也是一样
HTTP响应码是200，PHP也没报错
见鬼了…

**Comment by luobingwei** [comment]
你不是一个人。我也是lnmp环境换了好几个版本php了。一样是空白。用户管理者登录后台后就空白。

**Comment by orvice** [comment]
检查下数据库配置是否正确。

**Comment by leungzw** [comment]
我的也是……版本249。
数据库连接无误，(新注册用户写入数据库成功)，
但是打开用户中心，用户登录，后台登录后返回空白页……(登录页面用户名/密码验证是通过的)
系统debian6，用的lnmp.org的一键安装，求指点。

**Comment by sky5567** [comment]
2.4.6是好的吗？我搞了一天，数据库什么的都是好的，换了LNMP,ONEINSTACK,的一键包，都是这样，就是登陆进去显示空白

**Comment by orvice** [comment]
新版解决
https://github.com/orvice/ss-panel/releases/tag/v2.5.1
