### ISSUE TITLE
v2  user/_checkin.php文件 

### ISSUE THREAD

**Issue by chenfeng432** [orvice/ss-panel#300]
if ($oo->unused_transfer() < 2048 * $tomb) {
        $transfer_to_add = rand(1024, 2048);
    } else {
        $transfer_to_add = rand($check_min, $check_max);
    }

以上代码,  意思是不是说, 如果用户当前流量 小于 2G, 则新增流量在 1G到2G之间. 
这样子写用意何在啊, 那配置 check_min and check_max就没有意义了啊

**Comment by ZacharyJia** [comment]
作者的本意应该就是用来分享SS的吧，所以会有这种设定。不喜欢的话自己改掉就好了。
