### ISSUE TITLE
最新版本 2.51

### ISSUE THREAD

**Issue by jingwangnet** [orvice/ss-panel#301]
后台管理界面  貌似 去掉了 修改用户套餐的功能
(-｡-;)  该不是忘记 添加这个功能了吧

**Comment by orvice** [comment]
一直都没有这个功能吧。

**Comment by jingwangnet** [comment]
大牛 是我记错了吗 ，对   
有个修改版的 的   是基于你的版本改的。
支持 smtp  套餐修改  
http://www.hostloc.com/thread-287174-1-1.html

你看看 能不能 直接 copy  他的代码 实现 smtp

**Comment by orvice** [comment]
smtp v3会实现。
