### ISSUE TITLE
v3 安装后没有管理员账号

### ISSUE THREAD

**Issue by nqzhang** [orvice/ss-panel#303]
这个怎么增加个管理员啊

**Comment by ZacharyJia** [comment]
先到数据库里的邀请码表，随便添加一个邀请码，然后用这个邀请码注册一个账号，再到数据库里把用户表里的admin字段改成1，就是管理员了

**Comment by orvice** [comment]
拉取最新dev分支，根据提示创建管理帐号
https://github.com/orvice/ss-panel/wiki/v3-Config#%E6%B7%BB%E5%8A%A0%E7%AE%A1%E7%90%86%E5%91%98
