### ISSUE TITLE
composer 无法安装

### ISSUE THREAD

**Issue by holotr** [orvice/ss-panel#310]
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Connection timed out

**Comment by orvice** [comment]
国外vps么

**Comment by ljl024** [comment]
我在php composer.phar  install的时候出现了
Failed to download twig/twig from dist: The "http://packagist.phpcomposer.com/files/twigphp/Twig/ae53fc2c312fdee63773b75cb570304f85388b08.zip" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
    Now trying to download from source
是国内这个镜像阻止了国外访问么
