### ISSUE TITLE
V2升级到V3需要注意些什么？

### ISSUE THREAD

**Issue by YoungSx** [orvice/ss-panel#311]
我把根目录的替换成V3、修改完Apache路径，数据库重新导入后网站挂了，.env也修改过了，不知是什么原因。
难不成V3后端必须用Go版的吗？
求升级步骤。

**Comment by YoungSx** [comment]
访问网站显示：
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by orvice** [comment]
升级比较麻烦近期会写  后端py和go都可以  

---Sent from Boxer | http://getboxer.com

On January 25, 2016 at 12:41:22 AM GMT+8, SX <notifications@github.com> wrote:我把根目录的替换成V3、修改完Apache路径，数据库重新导入后网站挂了，env也修改过了，不知是什么原因。 难不成V3后端必须用Go版的吗？ 求升级步骤。  —Reply to this email directly or view it on GitHub.

**Comment by orvice** [comment]
debug设置为true后看下log

---Sent from Boxer | http://getboxer.com

On January 25, 2016 at 12:45:23 AM GMT+8, SX <notifications@github.com> wrote:访问网站显示： Slim Application Error A website error has occurred. Sorry for the temporary inconvenience.  —Reply to this email directly or view it on GitHub.

**Comment by zhanzhenchao** [comment]
会不会是原先版本的redius端口占用了

**Comment by YoungSx** [comment]
应该和V2版本没有关系，我重开一个虚拟机搭建测试，也是这个错误。
Debug改成了true后，弹出了附件图片中的一大坨错误代码。

![errorpic](https://cloud.githubusercontent.com/assets/4066622/12559038/bd253a1a-c3cd-11e5-8fd5-8fae715e403d.png)

**Comment by fivestar0517** [comment]
@YoungSx 
我是小白，ubuntu按教程刚开始装走到 php composer.phar  install 提示 composer.json not found，放狗搜了下没找到解决办法。
后来直接改 Nginx配置、导入数据库、再改env，chrome打开直接403~只能明天再试了。

**Comment by zhanzhenchao** [comment]
@YoungSx  6379是radius端口，你看看端口是否被占用，还有如果先前有radius没卸载干净也会影响的。如果急着使用新版本，可以使用cookie的模式。

**Comment by orvice** [comment]
要在ss panel目录下执行

---Sent from Boxer | http://getboxer.com

On January 26, 2016 at 2:51:59 AM GMT+8, fivestar0517 <notifications@github.com> wrote:@YoungSx  我是小白，ubuntu按教程刚开始装走到 php composer.phar install 提示 composer.json not found，放狗搜了下没找到解决办法。 后来直接改 Nginx配置、导入数据库、再改env，chrome打开直接403~只能明天再试了。  —Reply to this email directly or view it on GitHub.

**Comment by orvice** [comment]
@YoungSx apt-get install redis-server

**Comment by bg4kks** [comment]
打开邀请码那个链接，又提示了这个：
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by vacan** [comment]
打开邀请码那个链接，又提示了这个：
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by orvice** [comment]
开下debug发log

---Sent from Boxer | http://getboxer.com

On January 26, 2016 at 11:25:00 AM GMT+8, vacan <notifications@github.com> wrote:打开邀请码那个链接，又提示了这个： Slim Application Error A website error has occurred. Sorry for the temporary inconvenience.  —Reply to this email directly or view it on GitHub.

**Comment by hanzexu990323** [comment]
啊，话说V3需要使用新的数据库么_(:з」∠) _

**Comment by orvice** [comment]
升级方案近期会给

---Sent from Boxer | http://getboxer.com

On January 26, 2016 at 11:55:52 AM GMT+8, 雨宮千夏 <notifications@github.com> wrote:啊，话说V3需要使用新的数据库么_(:з」∠) _  —Reply to this email directly or view it on GitHub.

**Comment by vacan** [comment]
@orvice 请问一下看什么的log，已经调了debug =  'ture‘，不好意思新手。

**Comment by orvice** [comment]
错误页面完整信息在发下

---Sent from Boxer | http://getboxer.com

On January 26, 2016 at 12:56:40 PM GMT+8, vacan <notifications@github.com> wrote:@orvice 请问一下看什么的log，已经调了debug = 'ture‘，不好意思新手。  —Reply to this email directly or view it on GitHub.

**Comment by vacan** [comment]
@orvice   debug= ture 之后页面没有什么变化
![screen shot 2016-01-26 at 13 42 59](https://cloud.githubusercontent.com/assets/16891619/12573351/dbcf09cc-c432-11e5-924d-bd325014e45d.png)

**Comment by vacan** [comment]
@orvice debug= ture 之后页面没有什么变化
![screen shot 2016-01-26 at 13 45 25](https://cloud.githubusercontent.com/assets/16891619/12573372/196b55ec-c433-11e5-8b10-4a1cbe0b7383.png)

**Comment by vacan** [comment]
@orvice   找到原因了，是我的数据库的问题。不过还是疑惑，楼上的那位是怎么看到错误log的呢？我很想知道。

**Comment by orvice** [comment]
更新到最新版，然后
composer install
在开debug

**Comment by YoungSx** [comment]
我服务器用的是Apache，说我就只修改Apache的配置，不用管Nginx配置什么的了吧？

**Comment by orvice** [comment]
对

**Comment by YUX-IO** [comment]
可能是因为没有权限的问题 我也遇到了
把权限给过去就可以了
chown -R www /home/wwwroot/你的目录/

**Comment by fiepi** [comment]
遇到同样的问题。

> chown  -R http:http /path 

archlinux 的 nginx 默认用户是http，改了属主

> php xcat createAdmin 

创建管理员成功，说明数据库连接正常。。
nginx的配置

```
root /path/ss-panel/public;
	location / {
    		try_files $uri $uri/ /index.php$is_args$args;
	}
	location ~ [^/]\.php(/|$) {
    		try_files $uri =404;
    		fastcgi_pass   unix:/run/php-fpm/php-fpm.sock;
    		fastcgi_index index.php;
    		include fastcgi.conf;
    	}
```

**Comment by canyong** [comment]
chmod -R 777 sspanel目录路径
