### ISSUE TITLE
要死的php5.6

### ISSUE THREAD

**Issue by Losgif** [orvice/ss-panel#314]
该死的面板都是5.3-5.4的，升个级都像死个人这么难。。

**Comment by orvice** [comment]
能装这个的一般都有vps
有vps php不都是随便升级？

**Comment by Losgif** [comment]
有些面板很烦的，还是自己安装生产环境吧

**Comment by orvice** [comment]
amh？
不用面板也不难吧。。

就算是面板升级php也不难
