### ISSUE TITLE
lnmp环境配置完成后访问，页面一片空白···

### ISSUE THREAD

**Issue by serm12** [orvice/ss-panel#318]
server
    {
        listen 80;
        #listen [::]:80;
        server_name v3.xxxx.com;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home1/ss-panel/public;

        include none.conf;
        #error_page   404   /404.html;

        location / {
                   try_files $uri $uri/ /index.php$is_args$args;
                   }

        location ~ [^/]\.php(/|$)
        {
            # comment try_files $uri =404; to enable pathinfo
            try_files $uri =404;
            fastcgi_pass  unix:/tmp/php-cgi.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            #include pathinfo.conf;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        access_log  /home/wwwlogs/v3.xxxx.com.log  access;
    }

**Comment by orvice** [comment]
看下nginx和php的log

**Comment by serm12** [comment]
2016/01/31 10:51:12 [error] 21512#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  require(): open_basedir restriction in effect. File(/home1/ss-panel/bootstrap.php) is not within the allowed path(s): (/home1/ss-panel/public:/tmp/:/proc/) in /home1/ss-panel/public/index.php on line 7
PHP message: PHP Warning:  require(/home1/ss-panel/bootstrap.php): failed to open stream: Operation not permitted in /home1/ss-panel/public/index.php on line 7
PHP message: PHP Fatal error:  require(): Failed opening required '/home1/ss-panel/public/../bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home1/ss-panel/public/index.php on line 7" while reading response header from upstream, client: 113.116.62.213, server: v3.1122.lol, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "v3.1122.lol"

**Comment by orvice** [comment]
location ~ [^/]\.php(/|$)这里添加下

```
fastcgi_param  PHP_VALUE  "open_basedir=$document_root:/tmp/:/proc/:/home1/ss-panel/";

```

**Comment by serm12** [comment]
OK了，多谢·
