### ISSUE TITLE
v3 qrcode好像不生成

### ISSUE THREAD

**Issue by kuertianshi** [orvice/ss-panel#322]
不知道是我配置错了还是什么= =QRcode都没生成，链接倒是没问题

**Comment by orvice** [comment]
没生成是指页面空白么？

**Comment by kuertianshi** [comment]
@orvice 
不是，有个错误的二维码，所有的都是这一张图，解码出来好像是no text

**Comment by jsonge** [comment]
扫描二维码提示no text

**Comment by anhonestman** [comment]
header模板里调用 <link href="//fonts.lug.ustc.edu.cn/icon?family=Material+Icons" rel="stylesheet"> 这个网址访问不了，导致网页加载极慢

**Comment by zhaofengli** [comment]
发现用 `render:"table"` 就可以，不知道大家是不是一样

**Comment by wswing** [comment]
应该是因为没有text的原因，有指定text就行了
`jQuery('#qrcode')..qrcode({ "text" : "{$ssqr}" });`

看[官方的说明](https://larsjung.de/jquery-qrcode/)，render的选项应该没有table（`render method: 'canvas', 'image' or 'div'`）

**Comment by zhaofengli** [comment]
并不是这个qrcode，而是[这个](http://jeromeetienne.github.io/jquery-qrcode/)
