### ISSUE TITLE
请问如何关闭自定义加密方式?

### ISSUE THREAD

**Issue by mythcry** [orvice/ss-panel#336]
V3.1登录之后用户中心-连接信息- rc4-md5
信息更新也显示修改新的加密方式
怎么彻底删除了？
还有节点列表-查看配置文件-显示的信息{"server":"XXX","server_port":XXXX,"password":"XXXX","method":"aes-256-cfb"}总是超出边框了。。。

**Comment by orvice** [comment]
添加节点的时候自定义加密填0

**Comment by jinyu121** [comment]
建议此问题重新打开：

刚刚测试了一下，自定义加密填写为0仍然可以自己修改加密方式，无论是管理员还是非管理员。

节点列表那个`{"server":"XXX","server_port":XXXX,"password":"XXXX","method":"aes-256-cfb"}`，建议使用多行吧：
```
{
"server":"XXX",
"server_port":XXXX,
"password":"XXXX",
"method":"aes-256-cfb"
}
```

**Comment by orvice** [comment]
你没懂逻辑，用户一直可以修改自己的加密方式
但是如果节点不支持，就会用节点的加密，如果节点支持才用用户自定义的加密方式。

**Comment by jinyu121** [comment]
OK，懂了。
