### ISSUE TITLE
CSS中使用了GoogleFonts导致页面加载缓慢

### ISSUE THREAD

**Issue by jinyu121** [orvice/ss-panel#338]
`views/default/user/main.tpl`中第14行`<link href="/assets/public/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />`，这个css里面在第一行引用了GoogleFonts，会导致页面加载很慢。

建议去掉`/assets/public/css/AdminLTE.min.css`中的第一行`@import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);/*!`。

![screenshoot](https://cloud.githubusercontent.com/assets/7346324/13026635/1d5cfd78-d26a-11e5-835d-47a7c749d015.png)

**Comment by ZacharyJia** [comment]
可以改成360提供的cdn，直接把googleapis改成useso就行了。
`@import url(//fonts.useso.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);`
