### ISSUE TITLE
怎样在.env里面增加一个变量

### ISSUE THREAD

**Issue by jinyu121** [orvice/ss-panel#345]
想在.env里面增加一个变量`testVar`，但是在程序里面不能引用。

1. 在php里使用`Config::get('testVar')`获取到的一直是`true`。
2. 在tpl里面使用`{$config['testVar']}`，直接报错`testVar无效`。

还需要在其他地方修改什么东西么？

**Comment by orvice** [comment]
出于安全考虑，.env 的变量，不能通过 tpl里直接获取。
需要在
`app/Services/Config.php`
的
`getPublicConfig() `函数中引入。
