### ISSUE TITLE
装完之后显示Slim Application Error

### ISSUE THREAD

**Issue by evindu** [orvice/ss-panel#352]
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by orvice** [comment]
开启debug看log

**Comment by mythcry** [comment]
我的也是这样。。。。
[debug.txt](https://github.com/orvice/ss-panel/files/140538/debug.txt)

**Comment by orvice** [comment]
@mythcry 我是说发slim的debug log

**Comment by mythcry** [comment]
好像是redis的问题 我改成cookie可以访问了，安装redis提示
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: repos.lax.quadranet.com
 * extras: repos.lax.quadranet.com
 * updates: repos.lax.quadranet.com
No package redis-server available.
Error: Nothing to do

**Comment by maxidea-com** [comment]
please start the redis via: sudo service redis start
this error due to authDriver = 'redis' in .env setting and the redis is not running.
you can also set debug =  'ture' for got detail info
