### ISSUE TITLE
ss-panel  显示 错误     节点 显示  乱码

### ISSUE THREAD

**Issue by jingwangnet** [orvice/ss-panel#355]
{"server":"\u7f8e\u56fd\u65b0\u6cfd\u897f","server_port":1025,"password":"T9HL8x","method":"aes-256-cfb"}

**Comment by jingwangnet** [comment]
这个 是  ss-panel3

**Comment by jingwangnet** [comment]
https://github.com/orvice/ss-panel/releases/tag/v3.1.0          版本号

**Comment by orvice** [comment]
不明白你想表達啥

**Comment by jingwangnet** [comment]
我看看 能不能截图  
能截图 发给你

**Comment by jingwangnet** [comment]
![qq 20160223093752](https://cloud.githubusercontent.com/assets/12670670/13238894/2da14532-da11-11e5-92ec-96b490f61484.png)

**Comment by jingwangnet** [comment]
好吧  是我的 问题
我把节点地址  写成节点名称。
close 吧     不好意思
