### ISSUE TITLE
[提问]：能否从V2升级到V3

### ISSUE THREAD

**Issue by usami-mizugi** [orvice/ss-panel#358]
本人是小白，一点基础。现在前端部署了V2，能向DZ论坛那样能够升级V3么？不能的话，部署了V2升级到V3需要那些工作？

**Comment by ju0594** [comment]
我也是按教程装了V2 想升到V3也是无从下手，请原谅我小白⊙﹏⊙。

**Comment by usami-mizugi** [comment]
你V2使用的mail-gun吗？好想使用smtp，v2能使用么？

2016年2月27日星期六，ju0594 <notifications@github.com> 写道：

**Comment by ju0594** [comment]
我可是真小白 还没配置邮件呢...V3不是支持吗？你可以升到V3嘛╮(╯_╰)╭

2016-02-27 19:02 GMT+08:00 usami-mizugi <notifications@github.com>:

**Comment by orvice** [comment]
升级参考这个
https://www.zhaojin97.cn/read-3189.html
