### ISSUE TITLE
我安装了3.2.0 用户节点列表用户密码显示有问题

### ISSUE THREAD

**Issue by Kenw800c** [orvice/ss-panel#359]
节点列表密码显示有点问题 比如  节点列表中密码显示为 GF82Q1 实际上是应该是gF82Q1
在用户中心 连接信息中 显示为正常gF82Q1

**Comment by Kenw800c** [comment]
谢谢作者这么快就修复了 问题解决  谢谢

**Comment by pyy** [comment]
Please have a check this pull #363 Thanks.
