### ISSUE TITLE
我居然安装不了

### ISSUE THREAD

**Issue by FuaerCN** [orvice/ss-panel#361]
太失败了，按照教程安装结果出现500服务器错误
我用的的vestacp控制面板，我的VirtualHost配置和你的有点不一样

**Comment by orvice** [comment]
发php error log

**Comment by FuaerCN** [comment]
应该是这里吧
[root@fuaer public_html]# curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /home/admin/web/kiv.pw/public_html/composer.phar
Use it: php composer.phar
[root@fuaer public_html]# php composer.phar  install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aws/aws-sdk-php 3.15.1 -> satisfiable by aws/aws-sdk-php[3.15.1].
    - aws/aws-sdk-php 3.15.1 requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for guzzlehttp/guzzle 6.1.1 -> satisfiable by guzzlehttp/guzzle[6.1.1].
    - guzzlehttp/guzzle 6.1.1 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for guzzlehttp/promises 1.0.3 -> satisfiable by guzzlehttp/promises[1.0.3].
    - guzzlehttp/promises 1.0.3 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - Installation request for illuminate/container v5.2.7 -> satisfiable by illuminate/container[v5.2.7].
    - illuminate/container v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 5
    - Installation request for illuminate/contracts v5.2.7 -> satisfiable by illuminate/contracts[v5.2.7].
    - illuminate/contracts v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 6
    - Installation request for illuminate/database v5.2.7 -> satisfiable by illuminate/database[v5.2.7].
    - illuminate/database v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 7
    - Installation request for illuminate/pagination v5.2.7 -> satisfiable by illuminate/pagination[v5.2.7].
    - illuminate/pagination v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 8
    - Installation request for illuminate/support v5.2.7 -> satisfiable by illuminate/support[v5.2.7].
    - illuminate/support v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 9
    - Installation request for slim/csrf 0.5.0 -> satisfiable by slim/csrf[0.5.0].
    - slim/csrf 0.5.0 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 10
    - Installation request for slim/slim 3.1.0 -> satisfiable by slim/slim[3.1.0].
    - slim/slim 3.1.0 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 11
    - Installation request for slim/twig-view 2.0 -> satisfiable by slim/twig-view[2.0].
    - slim/twig-view 2.0 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 12
    - Installation request for symfony/translation v3.0.2 -> satisfiable by symfony/translation[v3.0.2].
    - symfony/translation v3.0.2 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 13
    - Installation request for zeuxisoo/slim-whoops 0.4.0 -> satisfiable by zeuxisoo/slim-whoops[0.4.0].
    - zeuxisoo/slim-whoops 0.4.0 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 14
    - symfony/translation v3.0.2 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
    - nesbot/carbon 1.21.0 requires symfony/translation ~2.6|~3.0 -> satisfiable by symfony/translation[v3.0.2].
    - Installation request for nesbot/carbon 1.21.0 -> satisfiable by nesbot/carbon[1.21.0].

**Comment by orvice** [comment]
requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.

php版本太低

**Comment by FuaerCN** [comment]
嗯 我升级一下版本试试  谢谢
