### ISSUE TITLE
是不是一些页面还没有完成？

### ISSUE THREAD

**Issue by BorLee** [orvice/ss-panel#369]
管理中心那几个框框都是没有实际链接的，制作简单的数据统计，是否一些页面尚未完成？

**Comment by kaneawk** [comment]
对。目前还是烂摊子。。

**Comment by orvice** [comment]
每啥更新计划了，如果有想法欢迎pr

**Comment by kaneawk** [comment]
求把 ShadowX 的这些漂亮界面和功能加进去，就满足了。。

**Comment by orvice** [comment]
shadowx主题是商业主题非开源无法写到sspanel
Charles Kane <notifications@github.com>于2016年3月2日 周三上午12:53写道：

**Comment by kaneawk** [comment]
好吧。目前V3版来说，
用户管理尚未完成，记得之前v2是有的；
套餐管理尚未完成，记得之前有的；
二维码扫描尚未完成，记得之前V2有的；
暂时就这么多。。

**Comment by orvice** [comment]
你确定你用的是最新版？

**Comment by BorLee** [comment]
我是前天安装的，3.2.0的版本，后台只有用户管理，节点管理和邀请管理，然后就这样了恩。

付费功能要自己写，囧。也没见到什么套餐之类的。

用户流量里的记录是ss后端添加到数据库里的么？manyuser版不支持这个好像

**Comment by orvice** [comment]
付费功能ss-panel一直是没有的
流量记录需要go版本

**Comment by BorLee** [comment]
你链接的go版本给出的地址似乎已经失效了。

另外manyuser版本本身也有一个粗略的流量记录功能，只记录使用的流量，这个是shadowsocks-manyuser记录的么？

**Comment by feisu** [comment]
我刚装的3.2.1 管理中心进去，more info 怎么点都点不动。是不是管理中心只能看那些数据不能具体管理的？？
