### ISSUE TITLE
一直连不到数据库...shadowsocks

### ISSUE THREAD

**Issue by mikaoras** [orvice/ss-panel#37]
QAQ 隔壁没人理，所以这边求教

**Comment by orvice** [comment]
有错误信息么

**Comment by mikaoras** [comment]
提示db thread except:(2003, "Can't connect to MySQL server on 'localhost' (110)")

**Comment by wzxjohn** [comment]
@orvice 不用管这个人，直接关了这个 Issue 就好。他到处乱提 Issue 乱发 Pull Request，关键是根本不是系统的问题。你的程序代码完全没有问题的。

**Comment by mikaoras** [comment]
@wzxjohn 你有病？我就在mengskysama那pull了下，没有改动就是为了问下问题

**Comment by mikaoras** [comment]
请问我在哪乱提issue了？
我也没说是这边的问题，拜托好好学习下小学语文@wzxjohn
