### ISSUE TITLE
[nginx]部署之后可以进入首页，但是点击其他url报404

### ISSUE THREAD

**Issue by TheHooper** [orvice/ss-panel#378]
可以顺利进入首页，但是点击其他url就404，之前一直按照自己的流程部署都没有问题，今天换了个vps就出现了这样的情况，os已经重装了好几次都没用。麻烦大大指点了……

nginx配置如下：

server
    {

        listen 80 default_server ;
        #listen [::]:80 default_server ipv6only=on;
        server_name www.lnmp.org;
        index index.html index.htm index.php;
        root  /home/wwwroot/default/ss-panel/public;

        #error_page   404   /404.html;
        include enable-php.conf;

        #ss-panel
        location / 
        { 
           try_files $uri $uri/ /index.php$is_args$args;
        }
  
        location /nginx_status
        {
            stub_status on;
            access_log   off;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /home/wwwlogs/access.log  access;
    }

**Comment by orvice** [comment]
server_name改下？

**Comment by TheHooper** [comment]
谢谢您的回答，尝试过，没有效果呢。

**Comment by TheHooper** [comment]
部署流程如下：
![image](https://cloud.githubusercontent.com/assets/11960949/13552401/1362677a-e39c-11e5-834a-5b1e0900e1db.png)
![image](https://cloud.githubusercontent.com/assets/11960949/13552402/1b0105ae-e39c-11e5-85b6-5da229441b03.png)

**Comment by orvice** [comment]
404是nginx的404页面还是slim error？

**Comment by TheHooper** [comment]
nginx的404,重新部署了一遍又好了，不知道什么情况…………

**Comment by xieweicn** [comment]
nginx里需要增加以下代码：
```
location / {
   try_files $uri $uri/ /index.php$is_args$args;
}   
```
