### ISSUE TITLE
无法正常调用phpqrcode.php生成二维码

### ISSUE THREAD

**Issue by ytf4425** [orvice/ss-panel#38]
https://xxx.com/user/node_qr.php?id=n (n>0)上面两行是正常的，就是二维码的图片是404（没生成图片啊）
经测试/lib/func下的phpqrcode.php文件正常

**Comment by ytf4425** [comment]
本地xampp测试可用，但Linode上lnmp一键包就不能用

**Comment by orvice** [comment]
user目录下新建个tmp目录，然后设置权限755或者777

**Comment by ytf4425** [comment]
tmp目录本来就有，权限设777也无效

**Comment by ytf4425** [comment]
把user目录chmod 777 . -R就行了

**Comment by ytf4425** [comment]
谢谢

**Comment by orvice** [comment]
如果用lnmp一键安装包
最好设置下用户chown

**Comment by ytf4425** [comment]
好的谢谢
