### ISSUE TITLE
用户界面节点列表

### ISSUE THREAD

**Issue by BorLee** [orvice/ss-panel#387]
今天重新安装了下ss-panel
用户界面的节点列表点开提示
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.
resources里有Node文件

**Comment by MaidGakuen** [comment]
数据库名称，前缀正确？
自己开DEBUG看错误

**Comment by BorLee** [comment]
已解决，新版本多了一个数据表，导入后就可以了
