### ISSUE TITLE
关于ss go mu错误

### ISSUE THREAD

**Issue by MaidGakuen** [orvice/ss-panel#389]
我部署了一个ss go mu，但不知道为什么会提示着两个错误，我找不到错误在哪。

ERRO[0425] update size fail for port:15000invalid character '<' looking for beginning of value 
ERRO[0426] invalid character '<' looking for beginning of value

**Comment by orvice** [comment]
确认下是否是最新的ss-panel

**Comment by orvice** [comment]
ps，mu的issue发那边去...
