### ISSUE TITLE
同一用户同时连接设备限制问题

### ISSUE THREAD

**Issue by Gav1nMa** [orvice/ss-panel#39]
首先得感谢作者的辛勤汗水！
RT，建议增加同一用户同时连接设备限制功能，期待您的更新。

**Comment by cdiscrete** [comment]
这个应该是后端该做的事情？

**Comment by wzxjohn** [comment]
这个显然跟前端木有关系，请通过 iptables 自行实现。

**Comment by Gav1nMa** [comment]
已经在用iptables做限制了，反馈错地方，抱歉。
