### ISSUE TITLE
显示这个是哪里出了问题？

### ISSUE THREAD

**Issue by xdker** [orvice/ss-panel#392]
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by xdker** [comment]
Predis \ Connection \ ConnectionException (111)
HELP
Connection refused [tcp://127.0.0.1:6379]

**Comment by orvice** [comment]
安装下redis

**Comment by xdker** [comment]
哦哦 我忘记装了  可以了
