### ISSUE TITLE
流量使用记录里面都是空的啊

### ISSUE THREAD

**Issue by jerryh80** [orvice/ss-panel#396]
user里面的流量使用记录, 和admin里面的流量使用记录都无法看到数据, 

两个表 ss_node_online_log 和 user_traffic_log 运行起来后都是空的没有数据

请问需要如何设置才能看到呢

**Comment by MaidGakuen** [comment]
通讯错误，没有同步到数据

**Comment by orvice** [comment]
this feature requires ss-go mu port:
https://github.com/orvice/shadowsocks-go/tree/master/mu
