### ISSUE TITLE
如何设置默认加密方式？

### ISSUE THREAD

**Issue by VishKozus** [orvice/ss-panel#397]
装好后用户注册默认加密方式是 rc4-md5，如何将默认值修改成 aes-256-cfb 或者其他的？

**Comment by Acris** [comment]
https://github.com/orvice/ss-panel/blob/master/db-160305.sql#L81
将DEFAULT 'rc4-md5'改为你需要的。

**Comment by VishKozus** [comment]
@Acris 多谢。

**Comment by holdlife** [comment]
您好，教程链接失效。可否补充？

**Comment by holdlife** [comment]
翻代码找到了。谢谢了

**Comment by ghostsf** [comment]
是吗？ 直接改数据库user表的method字段的默认值为你需要的即可
