### ISSUE TITLE
修改一些说明文字就500错误

### ISSUE THREAD

**Issue by PlexPt** [orvice/ss-panel#400]
把个人中心和node的一些文字修改了，就500了

**Comment by orvice** [comment]
所以你修改了什么呢

Sent from Outlook Mobile




On Wed, Mar 16, 2016 at 11:39 PM -0700, "PlexPt" <notifications@github.com> wrote:












把个人中心和node的一些文字修改了，就500了

**Comment by PlexPt** [comment]
动了index几个字就全站500

**Comment by MaidGakuen** [comment]
自己修改错了不要怪代码

**Comment by fsgmhoward** [comment]
你检查一下500错误详细是什么错误，像是漏打分号花括号之类的改过来不就好了么。我自己的站被我魔改了一大堆地方都没出问题。
