### ISSUE TITLE
“节点流量”和“节点在线人数”两个地方都显示}“暂无数据”？

### ISSUE THREAD

**Issue by yueker** [orvice/ss-panel#407]
“节点流量”和“节点在线人数”两个地方都显示}“暂无数据”？

**Comment by MaidGakuen** [comment]
节点通讯错误没有同步数据

**Comment by saladinxp** [comment]
2个版本 ss都可以限制在线人数，还是只有go版才能显示呢？

**Comment by orvice** [comment]
目前只有go mu版本的才有此功能
https://github.com/orvice/shadowsocks-go/tree/master/mu
