### ISSUE TITLE
3.2 直升3.3后 其他正常 就用户节点信息错误

### ISSUE THREAD

**Issue by saladinxp** [orvice/ss-panel#409]
其他一切正常，就是用户节点信息 提示以下信息
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.﻿

我是直接覆盖安装，然后重新运行一下那些指令和更改设置文件文件，谢谢。

**Comment by orvice** [comment]
发debug信息

**Comment by saladinxp** [comment]
当初失败我就回滚了，没看，下次我再测试下吧

**Comment by saladinxp** [comment]
对了，我翻查了一下前面的人，也有一个类似问题的，也是用户的节点列表打不开
有人回答得导入新的数据库吗？多了一个列表？
如果是这样的话，有导入的指令吗，咱是菜鸟，只会照搬，因为现在把默认路径指向ss panel后 进不去phpmyadmin了，
