### ISSUE TITLE
不能显示二维码

### ISSUE THREAD

**Issue by Jarvanh** [orvice/ss-panel#41]
![000](https://cloud.githubusercontent.com/assets/5900885/5891336/ff64ca2c-a4c9-11e4-973c-69bbdae75f4e.png)

===
===

![0000](https://cloud.githubusercontent.com/assets/5900885/5891329/957f0212-a4c9-11e4-8742-6b3029cb6556.png)

**Comment by cdiscrete** [comment]
检查tmp目录是否有权限写入。一般是因为文件夹的owner不对，建议chown到www-data一类的用户（视具体情况而定）。

**Comment by Jarvanh** [comment]
@cdiscrete 
权限为755

目录如下
![00000](https://cloud.githubusercontent.com/assets/5900885/5891445/f01b7faa-a4d0-11e4-9a89-79bb136f9f83.png)

**Comment by wzxjohn** [comment]
@Jarvanh 请设置为 777

**Comment by Jarvanh** [comment]
@wzxjohn 
谢谢。
tmp为777还不行
user为777就成功了
