### ISSUE TITLE
3.3签到后流量变2G

### ISSUE THREAD

**Issue by drice82** [orvice/ss-panel#411]
反馈一个问题：3.3版本，签到后流量变2G。

**Comment by twlz0ne** [comment]
`用户管理>编辑` 存在同样问题

**Comment by drice82** [comment]
我是在 .env里改过默认的流量。如果没有改默认流量，好像不会有这个问题。至于这个是不是准确原因，不好说。

**Comment by orvice** [comment]
系统是32位导致的
#399
下个版本fix
