### ISSUE TITLE
用户流量结算是否计算错误

### ISSUE THREAD

**Issue by ershiwo** [orvice/ss-panel#414]
换用 ss-go mu 之后可以使用节点流量统计功能了，但是发现一个问题，用户的总已用流量计算错误，变成了每条节点流量记录的总和。应该只统计当前用户最后一条节点流量记录吧。
![2016-03-21_225103.png](https://c.hime.io/images/kMNy.png)
![2016-03-21_225118.png](https://c.hime.io/images/86yQ.png)
实际只用了 49 M，最后变成了 1 G……

**Comment by orvice** [comment]
看起来好像是因为你redis版本有问题？
流量记录后，没有情况流量使用。

发下你redis的版本

./mu -debug 这样运行下mu，发下debug log

**Comment by orvice** [comment]
不用开debug，看下log是否有如下信息：
```
set storage size to 0 fail for port
```

**Comment by ershiwo** [comment]
有这么一条 `msg="update size fail for port:10050invalid character '<' looking for beginning of value"`
redis 版本 2.8.4，系统版本是 ubuntu 14.04 LTS

**Comment by orvice** [comment]
目测是更新流量成功，但是有抛异常。

**Comment by orvice** [comment]
```
curl -X POST -H "Cache-Control: no-cache"  -H "Content-Type: application/x-www-form-urlencoded" -d 'node_id=1&u=1&d=1' "http://xxx.dev/mu/users/1/traffic?key=abc"
```

先开ss-panel的debug，然后改下这个语句中的地址和key，执行，发下。

**Comment by ershiwo** [comment]
邮件回复没贴上啊……
返回了 500，Slim 程序错误，然后流量记录就多了一条奇怪的东西
![2016-03-22_125835.png](https://c.hime.io/images/Qmw4.png)
考虑重新配置一遍环境了……

**Comment by orvice** [comment]
开debug会有debug log的

**Comment by ershiwo** [comment]
>>>DEBU[5820] check user for 8389                
INFO[5820] check finish...                    
INFO[5880] 1                                            
INFO[5880] sync finish...start logging online count     
INFO[5880] 1                                            
DEBU[5880] [{1 10050 7gy aes-256-cfb 1 53844377600 2 561197499}]

当时只返回了这几行信息，没见到异常

**Comment by orvice** [comment]
我是说slim 500的时候有没有debug log...

**Comment by ershiwo** [comment]
slim 的 log 是指返回的网页还是硬盘上的某个日志文件？

**Comment by orvice** [comment]
网页上

**Comment by ershiwo** [comment]
>Invalid configuration value provided for "region". Expected string, but got bool(false) region: (string) Region to connect to. See http://docs.aws.amazon.com/general/latest/gr/rande.html for a list of available regions.

**Comment by ershiwo** [comment]
[0.txt](https://github.com/orvice/ss-panel/files/183751/0.txt)

**Comment by orvice** [comment]
```
// 记录流量日志到dynamodb ,beta,请勿开启
log_traffic_dynamodb = 'false'
```

你是不是开启这个了。

**Comment by ershiwo** [comment]
没有。
[env.txt](https://github.com/orvice/ss-panel/files/183758/env.txt)
这是配置文件

**Comment by orvice** [comment]
```
#aws_access_key_id = ''
#aws_secret_access_key = ''
#aws_region = 'ap-northeast-1'
#aws_ses_region = 'us-east-1'
#aws_ses_sender = ''

```

这几行不要取消注释试试看

**Comment by ershiwo** [comment]
![2016-03-22_173550.png](https://c.hime.io/images/RM4O.png)
不知道这样算不算正常了，虽然还是计算总和，但是每条记录之间并不是累积的关系了。如果还不行就冲装一下，正好服务器那边炸的厉害。

**Comment by orvice** [comment]
正常了。
