### ISSUE TITLE
sspanel v3新建节点时出现500错误

### ISSUE THREAD

**Issue by ccc1924** [orvice/ss-panel#415]
2016/03/22 02:12:46 [error] 7355#7355: *650 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Illuminate\Database\QueryException                           
Code: 42S22
Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'traffic_rate' in 'field list' (SQL: insert into `ss_node` (`name`, `server`, `method`, `custom_method`, `traffic_rate`, `info`, `type`, `status`, `sort`) values (ss, xxx.xxx.xxx.xxx, aes-256-cfb, 0, 1, , 1, , ))
File: /var/www/ss-panel/vendor/illuminate/database/Connection.php
Line: 669
Trace: #0 /var/www/ss-panel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `ss...', Array, Object(Closure))
#1 /var/www/ss-panel/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into `ss...', Array, Object(Closure))
#2 /var/www/ss-panel/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `ss...', Array)
#3 /var/www/ss-panel/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->i" while reading response header from upstream, client: 61.154.12.99, server: xxx.xxx.xxx.xxx, request: "POST /admin/node HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx.xxx.xxx.xxx", referrer: "http://xxx.xxx.xxx.xxx/admin/node/create"
已经导入user_traffic_log.sql   ss_node_online_log.sql     db-160305.sql
如何解决？

**Comment by orvice** [comment]
看下是不是node表少了字段
```
name, server, method, custom_method, traffic_rate, info, type, status, sort
```

**Comment by orvice** [comment]
看下是不是node表少了字段
```
name, server, method, custom_method, traffic_rate, info, type, status, sort
```

**Comment by ccc1924** [comment]
怎么看，新手

**Comment by ccc1924** [comment]
没有少 但问题没解决

**Comment by ccc1924** [comment]
没有少 但问题没解决

**Comment by ccc1924** [comment]
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| name          | varchar(128) | NO   |     | NULL    |                |
| type          | int(3)       | NO   |     | NULL    |                |
| server        | varchar(128) | NO   |     | NULL    |                |
| method        | varchar(64)  | NO   |     | NULL    |                |
| custom_method | tinyint(1)   | NO   |     | 0       |                |
| traffic_rate  | float        | NO   |     | 1       |                |
| info          | varchar(128) | NO   |     | NULL    |                |
| status        | varchar(128) | NO   |     | NULL    |                |
| offset        | int(11)      | NO   |     | 0       |                |
| sort          | int(3)       | NO   |     | NULL    |                |
+---------------+--------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)
