### ISSUE TITLE
最近突然无法连接面板主机数据库了

### ISSUE THREAD

**Issue by madlaxcb** [orvice/ss-panel#419]
之前一直运行良好，面板主机和节点机子都没动过，最近查看节点情况发现全是

`2016-03-25 21:14:57 WARNING  db thread except:(2003, "Can't connect to MySQL server on 'XXX.XXX.XXX.XXX' (110)")
2016-03-25 21:17:19 WARNING  db thread except:(2003, "Can't connect to MySQL server on 'XXX.XXX.XXX.XXX' (110)")
`
MYSQL用的默认3306.没开防火墙，端口是开的
`Active Internet connections (servers and established)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name`
`tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      849/mysqld      `
`tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      887/redis-server 12`

节点重装系统和SS情况依旧

`mysql -hXXX.XXX.XXX.XXX -rXXXX -p`
`password: `
`ERROR 2003 (HY000): Can't connect to MySQL server on 'XXX.XXX.XXX.XXX' (110)`

请问应该怎么处理？

**Comment by ljl024** [comment]
MySQL运行异常
近期有没有*升级MySQL*或*修改my.cnf配置文件*？

**Comment by madlaxcb** [comment]
面板在主机上用的是主机数据库localhost或127.0.0.1都正常运作。就是外面无法远程连接。没有升级和修改文件。也没重启过，出问题后重启过问题依旧。

**Comment by MaidGakuen** [comment]
你重新配置就不行了，怎么看都不是源码问题。
每天看到一群人提交这种没有意义的东西我也是醉

**Comment by orvice** [comment]
外面无法连接是你mysql配置的问题
