### ISSUE TITLE
用户改密码后，好像没办立即生效

### ISSUE THREAD

**Issue by ikzzdd** [orvice/ss-panel#42]

**Comment by wzxjohn** [comment]
你需要使用最新版后端。该功能与前端无关。

**Comment by ikzzdd** [comment]
好的，谢谢

在 15/1/27，wzxjohn<notifications@github.com> 写道：
> 你需要使用最新版后端。该功能与前端无关。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/orvice/ss-panel/issues/42#issuecomment-71657015


-- 
Jason

**Comment by liuchao0130** [comment]
更新了最新版的ss， 根本无法解决这个问题，每次改了ss密码 必须重新服务才会生效

**Comment by orvice** [comment]
最新版ss manyuser早就没有这个问题了

**Comment by liuchao0130** [comment]
为什么 我更新了ss还是无法解决 ，是怎么更新？？ 是不是我更新的方式不对？　
我是用这个命令升级的 ：
pip install -U shadowsocks
