### ISSUE TITLE
关于流量比例

### ISSUE THREAD

**Issue by saladinxp** [orvice/ss-panel#421]
### Description of the problem / 问题描述
我ss端是 manyuser
sspanel 3.2版本 设置流量比例 0.5  ,0.1,  甚至0都没有任何变化，还是一样的扣流量， 只 manyuser 版本不支持需要更换go版呢，还是3.3 就修正了，谢谢

**Comment by BorLee** [comment]
流量比例和详细的流量统计功能都需要go-mu版

**Comment by alexking99** [comment]
https://github.com/orvice/shadowsocks-go/tree/master/mu
