### ISSUE TITLE
请问后台管理“站点配置 App Config” 设置失败是什么原因？

### ISSUE THREAD

**Issue by dolfchan** [orvice/ss-panel#426]
填写完内容后点“更新配置”提示 错误500，麻烦看一下是什么问题？

**Comment by orvice** [comment]
需要导入几个表
看下release的说明
https://github.com/orvice/ss-panel/releases/tag/v3.3.5

**Comment by dolfchan** [comment]
好的 多谢

安装了3.3.5版本以后出现一个无法正常登录的问题

点击登录以后没有任何响应，连续快速点击才登录提示（发生错误：200）并且停留在登录页面    然后回到主页时发现已经是登录状态
