### ISSUE TITLE
请问SMTP的配置文件应该怎么填

### ISSUE THREAD

**Issue by echoowall** [orvice/ss-panel#427]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:5.6
* ss-panel version/ ss-panel版本:3.3.5

### Description of the problem / 问题描述

* ...env里的SMTP不会填，我用的是腾讯企业邮箱。
# smtp
smtp_host = 'smtp.ivan.ren'
smtp_username = 'w@ivan.ren'
smtp_port = ''
smtp_name = ''
smtp_sender = ''
这些字段应该如何填入？腾讯企业邮箱的发送和接受的地址不一样，端口也不一样，求教

**Comment by orvice** [comment]
smtp效率太低bug多，不在支持了。

**Comment by qq303335508** [comment]
mailgun一定要加域 名才可以发多个用户吗？  我只想发邮件到gmail邮箱，但只能发一个，很麻烦。
