### ISSUE TITLE
升级了3.3.5 好像没有提示登录成功?

### ISSUE THREAD

**Issue by slue0521** [orvice/ss-panel#429]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:5.5
* ss-panel version/ ss-panel版本:3.3.5

### Description of the problem / 问题描述

*升级了3.3.5 用戶中心登录没有任何反应 也没有提示登录成功 ?
但是用回3.3.0就有提示登录成功
@orvice

**Comment by dolfchan** [comment]
你也是无法登录吗？  看看是否与我下面描述的一样？ https://github.com/orvice/ss-panel/issues/426

**Comment by slue0521** [comment]
@dolfchan 你好 情况完全一样 应该是bug吧?  我还以为我自己弄错了什么
按登录没有任何反应 也没有任何提示 重新整理页面就回到用户中心
