### ISSUE TITLE
请问下有办法配置多个后端吗？

### ISSUE THREAD

**Issue by VishKozus** [orvice/ss-panel#43]

**Comment by VishKozus** [comment]
在一个前端服务器上，配置多个不同服务器的后端ssserver。

在ss-pannel的网页面板里面看到有服务器的选项，不晓得怎么用。

**Comment by orvice** [comment]
多个server使用同一个数据库。。。

**Comment by VishKozus** [comment]
大概是不是这样的。
在control服务器上配置ss-pannel和mysql。
在service服务器上配置ssserver多用户，都连到control服务器上的mysql

**Comment by orvice** [comment]
差不多

—
通过 Mailbox 发送
