### ISSUE TITLE
最后在线时间15秒一个间隔的被集体更新

### ISSUE THREAD

**Issue by gongz** [orvice/ss-panel#430]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:5.5.9
* ss-panel version/ ss-panel版本:3.3.0

### Description of the problem / 问题描述

* 最后在线时间15秒一个间隔的被集体更新
导致用户最后使用时间没有被记录

**Comment by orvice** [comment]
什么后端？

**Comment by dolfchan** [comment]
楼主是否是每隔一小时刷新一次？  我这遇到这情况，有大牛说疑似是被gfw检测了

**Comment by gongz** [comment]
nginx 
PHP Version /PHP版本:5.5.9
ss-panel version/ ss-panel版本:3.3.0
