### ISSUE TITLE
对所有SS-Panel版本进行自动提取后端服务器IP以及SS账号和密码

### ISSUE THREAD

**Issue by nqzhang** [orvice/ss-panel#432]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:

### Description of the problem / 问题描述

* ...

http://www.360.com.sb/safe/195.html

不知道这个怎么实现的

**Comment by maskerTUI** [comment]
个人感觉应该是注入或者命令执行这些漏洞引起的吧。

**Comment by glzjin** [comment]
就凭ta一两句话就那么害怕干嘛= =连利用方式都还没放出来就说什么通吃所有版本= =

**Comment by sendya** [comment]
然而我丢了github地址给他 想让他弄成呢，真成了还得感谢他，然后赶紧改进自己的框架.. （今天居然发说自己前两天要公布方法是不好的，不公布了。。 **我现在表情很不开心，想知道怎么搞的**

**Comment by norlover** [comment]
@sendya 看你之前的日志应该就有了解

**Comment by sendya** [comment]
@norlover 什么日志..
