### ISSUE TITLE
求mailgun怎么设置，老是500错误。

### ISSUE THREAD

**Issue by Tomzuo** [orvice/ss-panel#433]
求个模板
`#` mailgun
mailgun_key = ''
mailgun_domain = ''
mailgun_sender = ''

**Comment by orvice** [comment]
注册个账号
https://www.mailgun.com/

控制面板里有key

**Comment by Acris** [comment]
# mailgun
mailgun_key = 'key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'   # API Key
mailgun_domain = 'https://api.mailgun.net/v3/example.com'    # API Base URL
mailgun_sender = 'postmaster@example.com'

**Comment by Tomzuo** [comment]
成功了  谢谢

**Comment by Tomzuo** [comment]
再问一句    怎么让邀请码用一次后自动删除或者失效

**Comment by Acris** [comment]
现在难道不是用了就失效?

**Comment by MaidGakuen** [comment]
现在难道不是用了就失效?
