### ISSUE TITLE
配置的是50GB流量，用户登录之后变成了2GB

### ISSUE THREAD

**Issue by boyplay** [orvice/ss-panel#435]
## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:3.3.6
* OS: Ubuntu 14.04 32位

### Description of the problem / 问题描述
.env配置的是50GB流量，用户登录之后变成了2GB

**Comment by kinhit** [comment]
我也和你一样的问题。作者说是32位操作系统的问题，等待下个版本修复。

**Comment by MaidGakuen** [comment]
换个系统，多简单的事

**Comment by boyplay** [comment]
换系统是最麻烦的，这个应该很好改啊，怎么这么久了都没人改一下

**Comment by MaidGakuen** [comment]
换系统怎么麻烦？换系统5分钟的事，装web环境和部署好网站总共1小时好吧，怎么都够啦。
何况有的镜像都带环境的都不用你装了，更简单了，10分钟就搞定。

**Comment by boyplay** [comment]
不要想当然的以为所有的服务器都像你的那样简单。。。

**Comment by knowsee** [comment]
您好， 我现在有一个Fix 方案提供到给你们

寻找： /ss-panel/app/Models/User.php

Found:  `"transfer_enable" => 'int',`



Fix:  `"transfer_enable" => 'float',`
