### ISSUE TITLE
mailgun注册发送邮件验证码总是提示错误500

### ISSUE THREAD

**Issue by boyplay** [orvice/ss-panel#437]
## 运行环境

* PHP Version /PHP版本:5.5.9
* ss-panel version/ ss-panel版本:3.3.6

### Description of the problem / 问题描述

忘记密码界面可以成功发送邮件，所以mailgun的配置应该没问题，账号注册界面发送邮件总是提示错误500.

**Comment by iloveuMissliao** [comment]
@boyplay 我和你一样的环境，用的是SMTP，也是一点发送就500报错，然后重置密码那里是点击了无反应

**Comment by iloveuMissliao** [comment]
@orvice 求修复

**Comment by iloveuMissliao** [comment]
@orvice 同时建议恢复密码的邮件发送完毕后给出一个反馈并跳离页面，不然不知道的人以为点了没用会连续点击多次导致发送一大堆邮件

**Comment by Peter-XL** [comment]
重置密码邮件并不是所有用户都成功，163 qq 之类的都不行，Gmail的部分不行，唯一成功发送的就是admin的Gmail

**Comment by knowsee** [comment]
你们应该配置出错了

mailgun_key = 'key-0*****c09'  //上面的KEY
mailgun_domain = '*****.net'  //你经过验证过的域名  
mailgun_sender = 'postmaster@******.net'   //postmaster@你经过验证过的域名

**Comment by Peter-XL** [comment]
配置正确啊，能发忘记密码的邮件给admin邮箱啊

**Comment by boyplay** [comment]
@orvice 没修复就关闭了吗

**Comment by Peter-XL** [comment]
@boyplay 
ss-panel-3.3.6 以上如使用mailgun验证邮箱，请先登录mailgun并激活，否则会出现500错误。﻿

**Comment by Peter-XL** [comment]
@boyplay 
https://plus.google.com/103819359906022627379/posts/QzKKP2SviV1

**Comment by boyplay** [comment]
@Peter-XL 
注册mailgun的时候就已经激活过的呀

**Comment by boyplay** [comment]
这个邮件做的真的太烂了，直接调用php的mail函数发送不就完了么，就像wordpress那样

**Comment by Peter-XL** [comment]
@boyplay 登录到你的mailgun看看日志吧，我确实是激活完就好了。我付的链接也有对应截图啊。

**Comment by Peter-XL** [comment]
@boyplay mailgun安全性更强。

**Comment by zhwalker** [comment]
我也有这个问题。同样的mailgun配置在v2正常

**Comment by Frank-Hust** [comment]
我的也是这个问题，V3版本。
可以发送重置密码邮件，但是不能发送验证密码邮件。
后来发现是安装的时候，没有执行ss-panel目录下的sp_email_verify.sql文件。
把这个文件里的sql语句执行一下就好了。

**Comment by joeaki1983** [comment]
遇到同样的问题，搜索了之后导入sp_email_verify.sql，故障依旧，只能给管理员账户发忘记密码的信，后来把配置文件里的mailgun账户换成网站域名的那个账户，又莫名其妙好了，但是qq收不到mailgun的邮件，其他都可以。应该是mailgun的问题。

**Comment by isanniu** [comment]
我的也不行 找回密码邮件能发，注册发送验证码 就一直是500
