### ISSUE TITLE
作为一名熟练PHP开发的我~~决定参与这个ss平台开发

### ISSUE THREAD

**Issue by knowsee** [orvice/ss-panel#440]
已经完成了部分已知的bug修复，还有一些体验改善等优化。

Fix 已知部分bug问题
Fix 体验的问题
Fix 加密可以使用下拉菜单选择了

Add  服务器配置文件一键下载
Add  服务器稳定性报告 与 监控宝对接
Add  客户端响应测试

![qq 20160403143919](https://cloud.githubusercontent.com/assets/13564480/14231119/e121ca3e-f9a9-11e5-90b2-e71b6063e9c0.png)

![222](https://cloud.githubusercontent.com/assets/13564480/14231123/12e522dc-f9aa-11e5-8096-7f48704a633e.png)

**Comment by MaidGakuen** [comment]
然而你直接提交pull requests就好了

**Comment by Menma123** [comment]
pull requests吧

**Comment by Menma123** [comment]
如果能再加一个服务器流量控制功能就好了，自动关闭流量达到上限的服务器

**Comment by MaidGakuen** [comment]
自动关闭流量达到上限的服务器是不可能的，除非ss go 有api

**Comment by glzjin** [comment]
服务器流量控制可以看看这个版本(改得太大就不提PR了) https://www.zhaoj.in/read-3289.html ，然后go的API可以直接控制，Python的话— —需要自己改了。。。。

**Comment by knowsee** [comment]
LS, 你也可以提交呀，  就把那部分合并上来就好~~~

**Comment by knowsee** [comment]
我的合并还没那么快~~~

**Comment by orvice** [comment]
连接相应lz从哪里测的。。？

**Comment by HuanMeng0** [comment]
jiankongbao毕竟是国内的东西，我觉得用uptimerobot.com好点

**Comment by knowsee** [comment]
我会从用户客户端以及监控宝的免费监控点来测试的

**Comment by knowsee** [comment]
@HuanMeng0   其实基本上都是国内用户在用，用国内监测点会更好的反映节点状况哦~~~

**Comment by HuanMeng0** [comment]
@knowsee 但是其安全性……

**Comment by knowsee** [comment]
@HuanMeng0   啥安全性？？？  监控宝只是ping你的地址。。没什么安全性可言吧

**Comment by HuanMeng0** [comment]
@knowsee jiankongbao毕竟还是受ZF管制的，搞不好会配合有关部门调查，把你的账号数据供出去
