### ISSUE TITLE
3.3.7的新表名字写错啦

### ISSUE THREAD

**Issue by echoowall** [orvice/ss-panel#441]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:

### Description of the problem / 问题描述

* ...
直接导入是ss_node_info，报错了，手动改成ss_node_info_log就行了。

**Comment by echoowall** [comment]
话说uptime和负载需要go后端是吧？我用的是go后端，但是一直是没有数据啊

**Comment by orvice** [comment]
是否是最新的ss-go mu?

**Comment by echoowall** [comment]
是最新的ss-go mu，1.1.4版本的
