### ISSUE TITLE
流量使用情况邮件通知无法正常使用？

### ISSUE THREAD

**Issue by dolfchan** [orvice/ss-panel#442]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:3.3.6

### Description of the problem / 问题描述

* 如题，密码找回邮件可以正常发送，使用php xcat sendDiaryMail 无法正常发送邮件（这功能是否存在？）报错如下，域名以中文替换

Unable to load template file '总流量:9GB  已用流量: 714.64MB 剩余流量:8.3GB'Send daily mail to user: 5PHP Warnin
g:  Missing argument 4 for App\Services\Mail::send(), called in /home/wwwroot/域名/app/Command/DailyMa
il.php on line 22 and defined in /home/wwwroot域名app/Services/Mail.php on line 65
PHP Warning:  Missing argument 5 for App\Services\Mail::send(), called in /home/wwwroot/域名app/Comma
nd/DailyMail.php on line 22 and defined in /home/wwwroot/域名/app/Services/Mail.php on line 65
PHP Notice:  Undefined variable: ary in /home/wwwroot/域名/app/Services/Mail.php on line 67
PHP Warning:  Invalid argument supplied for foreach() in /home/wwwroot/域名/app/Services/Mail.php on l
ine 51

**Comment by orvice** [comment]
fixed in v3.3.8
https://github.com/orvice/ss-panel/releases/tag/v3.3.8
