### ISSUE TITLE
请问uptime和负载一直是暂无数据，后端用的go1.1.4最新版

### ISSUE THREAD

**Issue by echoowall** [orvice/ss-panel#443]
请问** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:

### Description of the problem / 问题描述

* ...这是什么原因？

**Comment by orvice** [comment]
是dev分之？
https://github.com/orvice/shadowsocks-go/tree/dev/mu

**Comment by echoowall** [comment]
哦··我用的是master分之，我换个试试

**Comment by echoowall** [comment]
有数据了，不过你那个ss_node_info表名字还是不对啊，应该是ss_node_info_log
