### ISSUE TITLE
为什么后台修改页面后前台没有变化？

### ISSUE THREAD

**Issue by BoneAsh** [orvice/ss-panel#444]
### Description of the problem / 问题描述

* 为什么我在后台修改完tpl文件后，重新刷新页面，页面并没有变化？
只有我重命名了页面名称，并且在route文件和controller文件相应修改后页面才会改变！！

**Comment by orvice** [comment]
> 后台修改完tpl文件后

没懂你怎么修改的

**Comment by BoneAsh** [comment]
比如，我在后台修改了index.tpl中的内容，例如修改了介绍部分，然后我把文件重新上传到原目录，可是我把浏览器刷新后，主页还是原来的样子，并没有改变

**Comment by BoneAsh** [comment]
就好像虽然我后台修改了文件，但是网页上显示的还是缓存的内容，我重启了apache，清理了浏览器缓存，清理了redis的缓存都没用。。。求大大指条明路

**Comment by orvice** [comment]
清空下`storage/framework/smarty/compile`目录下的文件

**Comment by BoneAsh** [comment]
非常感谢，已经解决了，希望ss-panel越来越完善！！

**Comment by MucangCat** [comment]
为什么我重置密码的邮件可以发送 但是邮箱验证的邮件则是500错误 mailgun
