### ISSUE TITLE
3.3.8 user/node 无法正常显示。

### ISSUE THREAD

**Issue by drice82** [orvice/ss-panel#445]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:  5.5
* ss-panel version/ ss-panel版本: 3.3.8

### Description of the problem / 问题描述

* ...

3.3.8 user/node 节点信息无法显示，用3.3.6的覆盖后正常。

**Comment by orvice** [comment]
导入数据库
https://github.com/orvice/ss-panel/blob/master/ss_node_info_log.sql

**Comment by imoldchen** [comment]
导入sql问题还是有，不知道为什么。
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by MaidGakuen** [comment]
@imoldchen 开debug

**Comment by imoldchen** [comment]
谢谢，看到错误信息了，表没导入完整。
