### ISSUE TITLE
老大后台编辑用户资料页面，流量的字节如何修改为GB呀？

### ISSUE THREAD

**Issue by jsonge** [orvice/ss-panel#446]
萌新确实对字节那修改无助啊，流量使用字节操作起来比GB麻烦呀，请问如何修改呢？

**Comment by jsonge** [comment]
还有一个问题，默认的邀请码页面地址是code，如何更改这个默认的路径呢？想换个名字，谢谢！

**Comment by knowsee** [comment]
你要改GB啊。。。其实可以的。。。哈哈哈。。。

只是你要到时候进行字节转换而已

**Comment by jsonge** [comment]
就是问下怎么改呀

**Comment by boyplay** [comment]
这个确实很不友好，改成MB或者GB把

**Comment by HuanMeng0** [comment]
程序路由：config/routes.php
关于流量字节的转换，app/Utils/Tools.php 有相关的function
