### ISSUE TITLE
MU运行之后出现错误提示 Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yylzcom** [orvice/ss-panel#447]
### Description of the problem / 问题描述
运行之后出错
root@test:~/go/bin# ./mu
INFO[0000] PONG                                         
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401118]

goroutine 1 [running]:
panic(0x9835c0, 0xc82000a0f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.boot()
	/root/go/src/shadowsocks-go/mu/boot.go:31 +0x118
main.main()
	/root/go/src/shadowsocks-go/mu/main.go:31 +0x28f

**Comment by orvice** [comment]
使用webapi还是mysql？

ps，mu问题就发mu那边- -

**Comment by yylzcom** [comment]
不好意思，是mysql，我以为MU也是你修改的作品

**Comment by yylzcom** [comment]
不好意思，已经解决，出现问题是因为远程数据库没有授予远程登录的权限，改为anyhost就好了

**Comment by orvice** [comment]
mu确实也是我改的- -
mu的问题就发那边吧。。
