### ISSUE TITLE
后台随机生成的ss密码，如何去掉一些容易混淆的字符

### ISSUE THREAD

**Issue by jsonge** [orvice/ss-panel#448]
V2 可以在Comm.php里，$chars = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
去掉oO0和1 I l，这些看不清容易混淆的字符，V3在哪里修改呢？烦请告知一下。

**Comment by orvice** [comment]
`app/Utils/Tools.php`
