### ISSUE TITLE
请问流量清不了零是什么原因？

### ISSUE THREAD

**Issue by ikzzdd** [orvice/ss-panel#45]

**Comment by ikzzdd** [comment]
重新上传了一次，手动执行又可以了。 下月再看看能不能自行

**Comment by orvice** [comment]
参考 #86

**Comment by thank243** [comment]
写入了crontab还是执行不了。

#reset shadowsocks transfer monthly
0 0 1 * * /usr/bin/php /usr/www/ss_panel/tools/cron.php
root@senis:/usr/www/ss_panel# /usr/bin/php /usr/www/ss_panel/tools/cron.php
PHP Warning:  require_once(../lib/config.php): failed to open stream: No such file or directory in /usr/www/ss_panel/tools/cron.php on line 2
PHP Fatal error:  require_once(): Failed opening required '../lib/config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/www/ss_panel/tools/cron.php on line 2

**Comment by thank243** [comment]
这样有什么问题么？提示config.PHP文件不存在。但是进入tools文件夹执行提示


root@senis:/usr/www/ss_panel/tools# /usr/bin/php /usr/www/ss_panel/tools/cron.php
PHP Fatal error:  Using $this when not in object context in /usr/www/ss_panel/tools/reset_transfer.php on line 9

**Comment by orvice** [comment]
fixed
试用最新的试试看
https://github.com/orvice/ss-panel/blob/733481abe46b1ddc2f812c374dc2941e3906d490/tools/reset_transfer.php
