### ISSUE TITLE
 ss-panel/app/sp_config.sql

### ISSUE THREAD

**Issue by ju0594** [orvice/ss-panel#450]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:

### Description of the problem / 问题描述

* ...
这个是重复的吗？

**Comment by MaidGakuen** [comment]
什么鬼回复。。。

**Comment by ju0594** [comment]
根目录下也有这个文件
