### ISSUE TITLE
邮件模板的几个问题

### ISSUE THREAD

**Issue by ju0594** [orvice/ss-panel#451]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:
* ss-panel version/ ss-panel版本:

### Description of the problem / 问题描述

* ...

实测QQ邮箱收到后链接为file://
在邮件模板网址少加上http://后测试正常。
顺便问下能不能添加个一键群发公告信息的？

**Comment by orvice** [comment]
发下你的邮件内容？

我测试连接是正常的

**Comment by ju0594** [comment]
@orvice 发现了，是我.env里的站点地址前没加http://的原因…
