### ISSUE TITLE
感觉签到不准吧

### ISSUE THREAD

**Issue by saladinxp** [orvice/ss-panel#453]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me

## 运行环境

* PHP Version /PHP版本:5.5几忘记了
* ss-panel version/ ss-panel版本:3.38

### Description of the problem / 问题描述

签到人数显示是曾经签到过的人数，而不是当天签到人数。

**Comment by orvice** [comment]
显示的是 ` 签到用户 `
没有说是今天的吧。
