### ISSUE TITLE
流量记录功能目前可用吗

### ISSUE THREAD

**Issue by lion1991** [orvice/ss-panel#460]
## 运行环境

* PHP Version /PHP版本: 5.6.20
* ss-panel version/ ss-panel版本:V3.3.9
* 其他环境信息(Nginx,系统等):Nginx&Centos6.7

### Description of the problem / 问题描述
在这里输入描述信息.我用的后端是shadowsocks manyuser,网站后台的“流量记录”功能页面是灰色空白没有内容，是必须搭配go来使用吗还是功能没开发完成。

**Comment by HuanMeng0** [comment]
必须使用shadowsocks-go 的webapi好像……

**Comment by Tomzuo** [comment]
要用shadowsocks-go mu的api

**Comment by lion1991** [comment]
@Tomzuo 启动mu的时候卡住了...webapi错误：Get User Errorinvalid character '<' looking for beginning of value.url是填写主页的域名吗.

**Comment by lion1991** [comment]
搞定了。封。

**Comment by evilkong** [comment]
流量记录功能不一定要用go，我用mysql的触发器也实现了。
go版本不支持协议混淆，go的时候给功夫墙直接虐了。。。

**Comment by lion1991** [comment]
我觉得只要流量不是特别大的情况下 应该可以过墙的

**Comment by weihuang0908** [comment]
ss-panel 3和shadowsocks-rm的这个api不太兼容
ss-panel要的是http://localhost/mu/users/<user_id>/traffic?key=config.API_PASS
shadowsocks-rm给的是http://localhost/mu/users/<port>/traffic?key=config.API_PASS
结果ss-panel用<port>当user的主键去查user,当然查不到，然后就服务器内部错误了
解决办法只要在shadowsocks-rm端用sql查一下user表中port对应的id发过去就好啦
