### ISSUE TITLE
如果想限制一个ip地址能注册一个账户应该如何写呢

### ISSUE THREAD

**Issue by lion1991** [orvice/ss-panel#462]
很多同一个ip的注册多个账户，很伤啊，我只是大概了解步骤差不多就是获取当前客户端ip地址和主机名然后和表中的相关字段比对，如果没有相同的正常写入新用户里，如果有拒绝注册。求问代码应该怎么写呢

**Comment by MaidGakuen** [comment]
拨号上网，一断一开又是一个新IP，有什么用？

**Comment by lion1991** [comment]
@MaidGakuen 除了限制注册外那基本上就没法杜绝这类现象了？

**Comment by MaidGakuen** [comment]
@lion1991 不然还有什么办法

**Comment by glzjin** [comment]
自己写个短信验证呗= =

**Comment by orvice** [comment]
dev分之添加了此功能，可以测试下 
https://github.com/orvice/ss-panel/tree/dev

.env添加`ipDayLimit = '1'`

**Comment by lion1991** [comment]
确实由于动态分配ip，效果并不是那么好。感谢各位解答。

**Comment by lion1991** [comment]
按照修改已成功，再次感谢！
