### ISSUE TITLE
composer问题

### ISSUE THREAD

**Issue by Liufire** [orvice/ss-panel#463]
php composer.phar update
ubuntu现在在3.3.8运行这条会说php版本要>=5.6,php5.5装不了了- -
所以安装环境要求现在也要提高成php5.6咯？

**Comment by Liufire** [comment]
`# php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.3.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.3.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.3.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.9 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.8 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.12 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.11 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.10 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.9 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.8 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.10 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ~5.0 -> satisfiable by phpunit/phpunit[5.0.0, 5.0.1, 5.0.10, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.2.0, 5.2.1, 5.2.10, 5.2.11, 5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.3.0, 5.3.1, 5.3.2].`

**Comment by Liufire** [comment]
```
# php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.3.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.3.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.3.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.9 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.8 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.12 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.11 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.10 requires php ^5.6 || ^7.0 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.2.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.1.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.9 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.8 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.7 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.6 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.5 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.4 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.3 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.2 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.10 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.1 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - phpunit/phpunit 5.0.0 requires php >=5.6 -> your PHP version (5.5.25) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ~5.0 -> satisfiable by phpunit/phpunit[5.0.0, 5.0.1, 5.0.10, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.2.0, 5.2.1, 5.2.10, 5.2.11, 5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.3.0, 5.3.1, 5.3.2].
```

**Comment by Acris** [comment]
同样的问题，所以我干脆升到了PHP7

**Comment by orvice** [comment]
是的需要php56


Sent from Outlook Mobile




On Sat, Apr 16, 2016 at 7:32 PM -0700, "Acris" <notifications@github.com> wrote:












同样的问题，所以我干脆升到了PHP7

**Comment by Liufire** [comment]
所以README.md该改咯-.-虽然已经对流程轻车熟路

**Comment by orvice** [comment]
5.5最新一个版本是支持的....
还是改下吧...
