### ISSUE TITLE
创建管理员出错 PHP Fatal error on line 3

### ISSUE THREAD

**Issue by fakehaoyang** [orvice/ss-panel#464]
我在创建管理员的时候
php xcat createAdmin
总是出现
PHP Warning:  require(/home/wwwroot/default/ss-panel/bootstrap.php): failed to open stream: No such file or directory in /home/wwwroot/default/ss-panel/xcat on line 3
PHP Fatal error:  require(): Failed opening required '/home/wwwroot/default/ss-panel/bootstrap.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/default/ss-panel/xcat on line 3 
请问怎么解决
Debian8+PHP5.6

**Comment by HuanMeng0** [comment]
/home/wwwroot/default/ss-panel/bootstrap.php 文件不存在

**Comment by fakehaoyang** [comment]
那文件了呢？已经装了两次了……都这样，该怎么做

**Comment by orvice** [comment]
重新git clone

**Comment by fakehaoyang** [comment]
为啥git到的没有bootstrap.php这个文件
但压缩包里有
刚刚接触不是很懂……望指教……

**Comment by fakehaoyang** [comment]
git clone的是文件夹诶

**Comment by fakehaoyang** [comment]
单独上传上去就都好了

**Comment by orvice** [comment]
git clone最新版本也有了。。。

这个文件换位置了
