### ISSUE TITLE
创建管理员时候说Uncaught exception PDOException

### ISSUE THREAD

**Issue by fakehaoyang** [orvice/ss-panel#466]
在创建管理员的时候出现的
start create admin accountPHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'sspanel'@'localhost' (using password: YES)' in /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/Connector.php:55
数据库账户密码都是对的，反复确认了
试着去掉php.ini里php_pdo_mysql.dll前的 ; 也不行
如果尝试登录，输入什么都会提示错误500
请问是啥问题？

bandwagon的服务器
php5.6.9
debian8

**Comment by orvice** [comment]
Access denied for user 'sspanel'@'localhost' (using password: YES)' 

数据库连不上，密码错误什么的自己检查下

**Comment by fakehaoyang** [comment]
嗷嗷嗷啊啊原来是数据库弄的％
