### ISSUE TITLE
后台管理界面，管理员不可以主动新增用户吗？

### ISSUE THREAD

**Issue by linye2008** [orvice/ss-panel#469]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
目前版本是否只支持用户自主注册，管理只能edit不可以新增？谢谢

**Comment by MaidGakuen** [comment]
不能

**Comment by orvice** [comment]
不能
