### ISSUE TITLE
导入数据库后，后台添加节点、编辑用户信息 500 错误

### ISSUE THREAD

**Issue by XIAZY** [orvice/ss-panel#470]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 7.0
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等): Ubuntu 16.04

### Description of the problem / 问题描述
导入从别的机器导出 mysql 数据库，在管理员后台界面无法添加节点、编辑用户信息。提示 500 错误。

使用的导出命令:
```
mysqldump -u root -p shadowsocks > database_dump.txt
```
使用的导入命令：
```
mysql -u root -p shadowsocks < database_dump.txt
```

**Comment by HuanMeng0** [comment]
"安装问题等错误请开启debug模式,并附上debug log"

**Comment by XIAZY** [comment]
安装是正常的，不算安装错误吧？稍后附上日志
在 2016年4月23日，下午11:07，HuanMeng <notifications@github.com<mailto:notifications@github.com>> 写道：


"安装问题等错误请开启debug模式,并附上debug log"

**Comment by XIAZY** [comment]
'''
2016/04/23 15:01:31 [error] 1428#1428: *336 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Illuminate\Database\QueryException
Code: 01000
Message: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'invite_num' at row 1 (SQL: update `user` set `transfer_enable` = 10737418240, `invite_num` = 57.59KB where `id` = 4)
File: /var/www/ss-panel/vendor/illuminate/database/Connection.php
Line: 673
Trace: #0 /var/www/ss-panel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('update `user` s...', Array, Object(Closure))
#1 /var/www/ss-panel/vendor/illuminate/database/Connection.php(434): Illuminate\Database\Connection->run('update `user` s...', Array, Object(Closure))
#2 /var/www/ss-panel/vendor/illuminate/database/Connection.php(377): Illuminate\Database\Connection->affectingStatement('update `user` s...', Array)
#3 /var/www/ss-panel/vendor/illuminate/database/Query/Builder.php(1978): Illuminate\Database\Connection->update('update `user` s...', Array)
#4 /var/www/ss-panel/vendor/illuminate/database/Eloquent/B" while reading response header from upstream, client: 108.162.215.102, server: ss.mechanus.io, request: "PUT /admin/user/4 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "example.com", referrer: "https://example.com/admin/user/4/edit"
'''

**Comment by HuanMeng0** [comment]
`invite_num` = 57.59`KB` <- WHAT???

你尝试下从phpmyadmin之类的webmysql管理工具，导出，然后再导入

**Comment by XIAZY** [comment]
使用了 phpmyadmin 导出导入数据，问题依旧。看起来应该不是这方面的问题。

**Comment by XIAZY** [comment]
但是直接修改 MySQL 数据库是可以的，很奇怪啊

**Comment by HuanMeng0** [comment]
关闭MySQL严格模式试试
https://ihuanmeng.com/2415.html

**Comment by orvice** [comment]
添加节点也错误？
发下添加节点的log

**Comment by XIAZY** [comment]
Sorry，log 的保存路径在哪……
在 2016年4月25日，上午1:15，orvice <notifications@github.com<mailto:notifications@github.com>> 写道：


添加节点也错误？
发下添加节点的log

**Comment by XIAZY** [comment]
@HuanMeng0 很尴尬，`SET sql_mode = '';` 不管用

**Comment by HuanMeng0** [comment]
log路径：
storage/logs

**Comment by XIAZY** [comment]
debug 模式已开，但是 logs 目录是空的

**Comment by HuanMeng0** [comment]
是不是目录权限的问题？

**Comment by XIAZY** [comment]
应该不是，已经设为 777 了

Sent from Outlook<http://taps.io/outlookmobile> Mobile



On Mon, Apr 25, 2016 at 5:58 AM -0700, "HuanMeng" <notifications@github.com<mailto:notifications@github.com>> wrote:


是不是目录权限的问题？

―

**Comment by HuanMeng0** [comment]
@XIAZY 如果可以，发E-mail到imhuanmeng@outlook.com，附带上服务器信息、站点地址、管理员账号密码，我尝试帮你解决并贴上相关的错误以及解决办法在这个issue

**Comment by XIAZY** [comment]
邮件已发，请查收
在 2016年4月25日，下午10:13，HuanMeng <notifications@github.com<mailto:notifications@github.com>> 写道：


@XIAZY<https://github.com/XIAZY> 如果可以，发E-mail到imhuanmeng@outlook.com<mailto:imhuanmeng@outlook.com>，附带上服务器信息、站点地址、管理员账号密码，我尝试帮你解决并贴上相关的错误以及解决办法在这个issue

**Comment by HuanMeng0** [comment]
最后发现是这个的问题：https://github.com/orvice/ss-panel/commit/9b52c11c1d26f6c3ad64e5e312218f800c94d2d8
input id 的问题

**Comment by XIAZY** [comment]
Closed. Please consider adding the newest commit to the `release` page.
