### ISSUE TITLE
为何修改了.env网站立马挂

### ISSUE THREAD

**Issue by fakehaoyang** [orvice/ss-panel#471]
就这么设定的么？想修改那几个数据该怎么改？

**Comment by HuanMeng0** [comment]
哪几个数据？

**Comment by echoowall** [comment]
你得说你改了哪儿挂了才行啊··要不然贴出来

**Comment by fakehaoyang** [comment]
不知道是不是我姿势不对，我想修改新用户流量或者有关签到的。改了下网页就开不开了，虽然其他都正常

**Comment by HuanMeng0** [comment]
修改成了什么？

**Comment by fakehaoyang** [comment]
比如从初始1g改到2g。我是用ssh上传上去的，是不是开启后不应该修改.env？

**Comment by HuanMeng0** [comment]
defaultTraffic = '5' -> defaultTraffic = '2g' 
这样？

**Comment by fakehaoyang** [comment]
不不不，还没那么蠢，等等我先看看是不是因为我mac被智能引号坑了，虽然看着一样，我得想个办法确认下是不是真的一样😂

**Comment by fakehaoyang** [comment]
我的错，mac好像得重启下智能引号才能真的关掉，麻烦你了😂
