### ISSUE TITLE
数据库连不上么？

### ISSUE THREAD

**Issue by Liufire** [orvice/ss-panel#472]
ubuntu lnmp的php5.6 ，数据库数据绝对正确，然后弹这个

**Comment by Liufire** [comment]
_```
start create admin accountPHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1129] Host '66.666.6666.233' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'' in /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=103....', 'liufire', 'xYst0908~', Array)
#1 /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=103....', Array, Array)
#2 /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connection.php(868): call_user_func(Object(Closure))
 in /home/wwwroot/default/ss-panel/vendor/illuminate/database/Connectors/Connector.php on line 55
```_

**Comment by orvice** [comment]
> Host '66.666.6666.233' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'' 


执行下 `mysqladmin flush-hosts`试试看？

**Comment by Liufire** [comment]
> start create admin accountPHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user

执行完后变成这个错误了。数据库信息也没错啊，，数据库必须和网站一台机么？数据库已经执行了给所有用户权限了，当然下面的东西有改动才执行。
`GRANT ALL PRIVILEGES ON `ss-panel`.* TO 'test'@'127.0.0.1' IDENTIFIED BY '密码' WITH GRANT OPTION;  `

**Comment by HuanMeng0** [comment]
MYSQL账号的HOST正确了吗？

**Comment by Liufire** [comment]
账号 	%	全局	ALL PRIVILEGES

**Comment by Liufire** [comment]
用户	主机	类型	权限
666	%	全局	ALL PRIVILEGES

**Comment by HuanMeng0** [comment]
PDO扩展开启了吗？

**Comment by orvice** [comment]
> Access denied for user

用户无法访问到数据库

**Comment by max2max** [comment]
https://github.com/orvice/ss-panel/issues/479
