### ISSUE TITLE
各位老大，注册模块能加验证码吗？

### ISSUE THREAD

**Issue by yestop** [orvice/ss-panel#473]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.
Smarty模版不是特别会啊，有懂行的老大告诉我大概怎么才能添加验证码不？

**Comment by orvice** [comment]
防止批量注册限制ip注册数量比验证码来的好吧

**Comment by HuanMeng0** [comment]
你可以尝试下Google nocaptcha
