### ISSUE TITLE
open_basedir  添加后依然报错 open_basedir restriction in effect.

### ISSUE THREAD

**Issue by duyuwei** [orvice/ss-panel#477]
`Warning: require(): open_basedir restriction in effect. File(/home/wwwroot/ss-panel/bootstrap/app.php) is not within the allowed path(s): (/home/wwwroot/ss-panel/public:/usr/share/pear:/usr/share/php:/etc/phpMyAdmin:/tmp:/proc) in /home/wwwroot/ss-panel/public/index.php on line 7 Warning: require(/home/wwwroot/ss-panel/bootstrap/app.php): failed to open stream: Operation not permitted in /home/wwwroot/ss-panel/public/index.php on line 7 Fatal error: require(): Failed opening required '/home/wwwroot/ss-panel/public/../bootstrap/app.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/wwwroot/ss-panel/public/index.php on line 7`

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):
server
{
    listen 80;
    server_name xx.xxx.xx; #server_name end
    index index.html index.htm index.php; #index end
    charset utf-8;

    set $subdomain '/public';
    root  /home/wwwroot/ss-panel$subdomain;
    include rewrite/nomal.conf; #rewrite end

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

    location ~ .*\.php$
    {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass  unix:/dev/shm/php-fpm-ss-panel.sock;
        fastcgi_index index.php;
        fastcgi_param DOCUMENT_ROOT  /home/wwwroot/ss-panel/public;
        fastcgi_param  PHP_VALUE  "open_basedir=$document_root:/tmp/:/proc/:/home/wwwroot/ss-panel/";
        fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include fastcgi_params;
        try_files $uri = 404;
    }

    location ~ .*\.(mp3|m4a|ogg|aac|wma|mp4|m4v|mpeg|webm|avi|swf|flv)$
    {
        expires      30d;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|webp|ico)$
    {
        expires      15d;
    }

    location ~ .*\.(js|css|woff|eot|ttf|ttc|otf|svg)$
    {
        expires      7d;
    }

    location ~* /templates?(/.*)\.(bak|html|htm|ini|old|php|tpl)$ {
        allow 127.0.0.1;
        deny all;
    }

### Description of the problem / 问题描述

open_basedir  添加 后依然报错

**Comment by HuanMeng0** [comment]
chmod

**Comment by duyuwei** [comment]
尝试过777 依然无效 ， 对php不太了解，麻烦大家了

**Comment by duyuwei** [comment]
===========>WRONG
fastcgi_param  PHP_VALUE  "open_basedir=$document_root:/tmp/:/proc/:/home/wwwroot/ss-panel/";
include fastcgi_params;
============
include fastcgi_params;
fastcgi_param  PHP_VALUE  "open_basedir=$document_root:/tmp/:/proc/:/home/wwwroot/ss-panel/";
============RIGHT

nginx玩的不6额，现在好了，谢谢
