### ISSUE TITLE
请问php xcat createAdmin后管理员登录错误500 

### ISSUE THREAD

**Issue by weiwei695** [orvice/ss-panel#479]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 7
* ss-panel version/ ss-panel版本:v3
* 其他环境信息(Nginx,系统等):nginx

### Description of the problem / 问题描述
在这里输入描述信息.
php xcat createAdmin后管理员登录错误500 
start create admin accountPHP Fatal error:  Uncaught PDOException: could not find driver in /sites/ss-panel/vendor/illuminate/database/Connectors/Connector.php:55

**Comment by HuanMeng0** [comment]
could not find driver
PDO扩展开启了吗？

**Comment by weiwei695** [comment]
没有，请问怎么开？原谅小白一个，谢谢

**Comment by HuanMeng0** [comment]
www.baidu.com / www.google.com

**Comment by max2max** [comment]
php编译的时候添加--with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd

**Comment by weiwei695** [comment]
已解决，感谢楼上两位大神，是我php7安装时候没有安装完整。
