### ISSUE TITLE
最新的composer和现有版本是不是不兼容

### ISSUE THREAD

**Issue by kinhit** [orvice/ss-panel#484]
* PHP Version /PHP版本: 5.6.21
* ss-panel version/ ss-panel版本:3.4.0
* 其他环境信息(Nginx,系统等):nginx/1.8.1

### Description of the problem / 问题描述
今天升级版本，出现全站500错误，打开getcomposer.org官网，发现最近版本更新频繁。
1.1.0-RC (2016-04-29)
1.0.3 (2016-04-29)
1.0.2 (2016-04-21)
1.0.1 (2016-04-18)
1.0.0 (2016-04-05)
我把composer降到1.0.0的版本500错误就没有了，请作者检查一下是不是
curl -sS https://getcomposer.org/installer | php
下载的最新版本和现有的ss-panel版本有不兼容的问题。

**Comment by HuanMeng0** [comment]
composer只是一个安装器

**Comment by orvice** [comment]
安装过程中没有错误就没问题。
