### ISSUE TITLE
ss-panel 支持php7吗？

### ISSUE THREAD

**Issue by usami-muzugi** [orvice/ss-panel#485]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

**Comment by usami-muzugi** [comment]
V2的

**Comment by orvice** [comment]
你可以试试看，应该是没有问题的
