### ISSUE TITLE
使用 nginx 时返回 403 错误

### ISSUE THREAD

**Issue by agentmario** [orvice/ss-panel#491]
## 运行环境

* PHP Version /PHP版本: 5.5.9
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等):Ubuntu 14.04 x64/nginx 1.9.9

### Description of the problem / 问题描述
在这里输入描述信息.按例子设置 nginx 之后提示 403 forbidden, 
```
root /var/www/ss/public;
        location / {
                try_files $uri $uri/ /index.php$is_args$args;
                }
```
我可以访问到 public 目录下的 robots.txt, 但无法访问主页

**Comment by fiepi** [comment]
nginx和php-fpm需要调教

**Comment by agentmario** [comment]
使用 v2 版的时候用到了 php-fpm, 可以正常运行
