### ISSUE TITLE
访问 domainname/admin 时产生的迷之错误

### ISSUE THREAD

**Issue by agentmario** [orvice/ss-panel#493]
## 运行环境

* PHP Version /PHP版本: 5.5.9
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等):Ubuntu 14.04, nginx 1.10.1

### Description of the problem / 问题描述
在这里输入描述信息.只有访问 /admin/ 的时候可以进入管理员页面，访问 /admin 时返回了一段奇怪的 php 代码。只有 /admin 会这样，其他页面没问题

**Comment by zuoruizhi** [comment]
@agentmario 返回的代码贴一下吧，没发现问题 /admin可正常访问

**Comment by agentmario** [comment]
@zuoruizhi 过了几天之后就可以访问了，不知道是哪里的问题。。。
