### ISSUE TITLE
无法实时统计流量耗用

### ISSUE THREAD

**Issue by agentmario** [orvice/ss-panel#494]
## 运行环境

* PHP Version /PHP版本: 5.5.9
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等):Ubuntu 14.04, nginx 1.10.1, shadowsocksR-manyuser latest

### Description of the problem / 问题描述
在这里输入描述信息.从 ss-panel v2 迁移到 v3 之后发现它不能统计流量了，其他用户功能不受影响

**Comment by fiepi** [comment]
用go版可以统计

**Comment by agentmario** [comment]
@fiepi 用 python 版难道连上下行流量都没法统计了么。。。

**Comment by zuoruizhi** [comment]
python 也是可以统计的，主要取决于你用的后端，python 版是后端直接更新数据库的，和前端没关系

**Comment by agentmario** [comment]
感谢回复，我发现是我的 ssr 服务端更新之后缺少一个与数据库通信的设置项 所以无法更新上下行流量
