### ISSUE TITLE
/admin可以打开可以配置 主页无法打开(403)

### ISSUE THREAD

**Issue by relei1988** [orvice/ss-panel#498]
## 运行环境

* PHP Version /PHP版本: 7.0.6
* ss-panel version/ ss-panel版本:V3
* 其他环境信息(Nginx,系统等):NGINX 1.10.0 centOS6.7 x64

服务器应该是安装成功了 doman/admin可以正常访问使用，但是打开主页就是403不知为何

**Comment by zuoruizhi** [comment]
检查下nginx或apache配置文件  


<Directory /home/www/ss-panel/public>
   AllowOverride All
   Order Deny,Allow
   Allow from all
</Directory>
并且需要开启mod_rewrite模块。

Nginx设置

root /home/www/ss-panel/public;

location / {
   try_files $uri $uri/ /index.php$is_args$args;
}    



root目录有没有public

**Comment by relei1988** [comment]
看了半天明明加了public了，后来发现被我手残修饰掉了…谢谢

**Comment by zuoruizhi** [comment]
Ok，关单吧
