### ISSUE TITLE
smtp是不是不能用了？

### ISSUE THREAD

**Issue by fucknima** [orvice/ss-panel#499]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.6
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.mailgun太难注册，注册就被禁用，所以用smtp
把smtp配置填了发送邮件返回错误0，
不填就显示发送成功，其实没有发送邮件

**Comment by zuoruizhi** [comment]
mailgun被禁用可以发工单申请开通

**Comment by fucknima** [comment]
我工单都发了，给我终止了，几个号都是

**Comment by zuoruizhi** [comment]
终止原因是什么，方便发下工单截图吗

**Comment by fucknima** [comment]
@zuoruizhi 来个联系方式

**Comment by fucknima** [comment]
@zuoruizhi 我注册了不下5个号

**Comment by fiepi** [comment]
注册、登录 mailgun 时千万不要使用代理
