### ISSUE TITLE
用composer安装依赖时出错>_<

### ISSUE THREAD

**Issue by DCLangX** [orvice/ss-panel#501]
## 运行环境

* PHP Version /PHP版本: 7.0.6
* ss-panel version/ ss-panel版本:3.3.9
* 其他环境信息(Nginx,系统等):Nginx 1.10，Ubuntu 14.04

### 执行php composer.phar install时出现如下错误，小白表示完全看不懂= =

Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for illuminate/support v5.2.31 -> satisfiable by illuminate/support[v5.2.31].
    - illuminate/support v5.2.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for phpunit/phpunit 5.3.2 -> satisfiable by phpunit/phpunit[5.3.2].
    - phpunit/phpunit 5.3.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 3
    - illuminate/support v5.2.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/pagination v5.2.31 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.31].
    - Installation request for illuminate/pagination v5.2.31 -> satisfiable by illuminate/pagination[v5.2.31].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by zuoruizhi** [comment]
PHP环境安装不正确     有些模块没有开    把上面那段英文翻译下按照说的做

**Comment by orvice** [comment]
`apt-get install php7.0-mbstring`

试试看？

**Comment by DCLangX** [comment]
十分感谢！打完apt-get install php7.0-mbstring和apt-get install php7.0-dom就可以啦~~
