### ISSUE TITLE
sspanel统计的流量是否只是tcp的流量

### ISSUE THREAD

**Issue by hdstar2009** [orvice/ss-panel#502]
sspanel统计的流量是通过什么接口获取的？iptables吗？
统计的流量是只针对tcp的流量还是包括一个端口上的tcp udp icmp stcp等协议的流量？

**Comment by zuoruizhi** [comment]
V3是webapi   http://demain/mu

**Comment by hdstar2009** [comment]
@zuoruizhi 
你那个网站打不开，已翻墙。
另外webapi又是什么情况，是否统计tcp和udp？

**Comment by zuoruizhi** [comment]
之前说的不是很准确，流量信息都是后端主动更新的，更新方式可以通过webapi或者数据库。另外那个不是网站，domain拼错了，是接口地址。
Webapi只是个接口，后端的数据可以通过这里上传记录。
统计了哪些流量，就看你后端怎么统计了。

**Comment by hdstar2009** [comment]
@zuoruizhi 
你说的后端是说的ss 服务端软件？
ss manyuser 或者ssr的版是否有udp流量的统计？

**Comment by zuoruizhi** [comment]
As mark 
fsgmhoward/shadowsocks-py-mu fork from mengskysama/shadowsocks-rm is support UDP traffic statistics
And in [87](https://github.com/breakwa11/shadowsocks/issues/87) the author said support.
