### ISSUE TITLE
如何关闭用户48小时候注册邀请码生成？

### ISSUE THREAD

**Issue by CnKore-zzb** [orvice/ss-panel#513]
## 运行环境

* PHP Version /PHP版本: 7.0
* ss-panel version/ ss-panel版本:3.30
* 其他环境信息(Nginx,系统等):nginx

### Description of the problem / 问题描述
在这里输入描述信息.
如何关闭用户48小时候注册邀请码生成？

**Comment by zuoruizhi** [comment]
V3最新版现在应该没有48小时限制了

**Comment by orvice** [comment]
v3没有此限制
