### ISSUE TITLE
想让新用户从40000开始分配端口，请问如何实现？

### ISSUE THREAD

**Issue by cccatcc** [orvice/ss-panel#515]
* ss-panel version/ ss-panel版本: v2.4.2

最初是从默认的50000端口开始分配的，现在端口快要分配殆尽，想在不影响现有的用户的情况下，让新注册用户的端口从40000开使分配，请问该如何修改php？

**Comment by jinyu121** [comment]
在不改动代码的情况下…… 管理员的帐号有了吧？进数据库，把管理员的port改为4000.之后就从4001开始分配了。

我记得逻辑是取port的max，然后+1.忘记在哪里改了。

**Comment by cccatcc** [comment]
额，可能是我没有说清楚，现在已经有很多用户，端口号已经快到60000了，我记得逻辑是取max加一个3~5的随机数，怎么让它把取max的范围进行限定，比如只对50000以下取max

**Comment by zuoruizhi** [comment]
app/Utils/Tools.php
修改200行
`    public static function getLastPort()
    {
        $user = User::orderBy('port', 'asc')->first();
        if ($user == null) {
            return 49999; // @todo
        }
        return $user->port;
    }
}`

app/Controllers/AuthController.php
修改164行
`        $user->port = Tools::getLastPort() - 1;`

效果，从49999端口递减，每次减1，V3版本

**Comment by cccatcc** [comment]
在V2版本中 相关的代码在 lib/Ss/User/Reg.php
`    function GetLastPort(){
        $datas = $this->db->select($this->table,"*",[
            "ORDER" => "uid DESC",
            "LIMIT" => 1
        ]);
        return $datas['0']['port'];
    }`

`    function Reg($username,$email,$pass,$plan,$transfer,$invite_num,$ref_by){

        $sspass = \Ss\Etc\Comm::get_random_char(8);

        $this->db->insert($this->table,[
           "user_name" => $username,
            "email" => $email,
            "pass" => $pass,
            "passwd" =>  $sspass,
            "t" => '0',
            "u" => '0',
            "d" => '0',
            "plan" => $plan,
            "transfer_enable" => $transfer,
            "port" => $this->GetLastPort()+rand(1,4),
            "invite_num" => $invite_num,
            "money" => '0',
            "#reg_date" =>  'NOW()',
            "ref_by" => $ref_by
        ]);
`
如何针对V2版本修改呢？

**Comment by zuoruizhi** [comment]
V2。。。。你直接该数据库就好了      新建一个用户     手动吧端口改成40000      在新建的用户应该就是从40000开始的了

**Comment by cccatcc** [comment]
手动新建低位端口号的用户的话，之后注册的用户的端口号依然是从现有的高位端口向后排列的呀

**Comment by zuoruizhi** [comment]
@cccatcc 试过了？

**Comment by cccatcc** [comment]
@zuoruizhi 安装上面列出的代码逻辑应该是这样的，而且目前已经有手动设置低位端口的账户，新注册账户依然是从最末端口开始排列的。

**Comment by zuoruizhi** [comment]
`function GetLastPort(){
$datas = $this->db->select($this->table,"*",[
"ORDER" => "uid DESC",
"LIMIT" => 1
]);
return $datas['0']['port'];
}`

按照这个，是按照uid排序取最高的，就是最新添加的用户，按照他的port增加

**Comment by zuoruizhi** [comment]
中间用户端口号改低了没用的    只能是最新的用户

**Comment by cccatcc** [comment]
@zuoruizhi 明白了 非常感谢！

**Comment by sunyh87** [comment]
@zuoruizhi app/Utils/Tools.php这个路径在哪啊？根目录里哪有什么app文件夹？

**Comment by zuoruizhi** [comment]
@sunyh87 V2的你直接把数据库里面随便一个用户端口改成40000就好了，app文件夹是V3的

**Comment by sunyh87** [comment]
@我就是V3的 找来找去没找到APP文件夹
