### ISSUE TITLE
我装的是lamp环境，你的重写在apache里面该怎么写？

### ISSUE THREAD

**Issue by weiweimao1991** [orvice/ss-panel#516]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境
php5.5
ss-panel3.0
apache 2.2

### Description of the problem / 问题描述
我装的是lamp环境，你的重写在apache里面该怎么写？能不能告知我一下
nginx里面这么写
location / {  
    try_files $uri $uri/ /index.php$is_args$args;
}

**Comment by orvice** [comment]
apache 不需要重写。
public目录下有.htaccess文件。

**Comment by weiweimao1991** [comment]
我做的是虚拟主机开启了vhost功能  
[Fri Jun 10 19:31:11 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/auth, referer: http://ss.itman.win/
[Fri Jun 10 19:46:06 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/code, referer: http://ss.itman.win/
[Fri Jun 10 20:00:51 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/code, referer: http://ss.itman.win/
[Fri Jun 10 20:00:55 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/auth, referer: http://ss.itman.win/
[Fri Jun 10 20:00:59 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/auth, referer: http://ss.itman.win/
[Fri Jun 10 20:54:17 2016] [error] [client 103.212.33.61] File does not exist: /var/html/ss/public/code, referer: http://ss.itman.win/

我首页能访问ok  我的虚拟主机配置
<VirtualHost *:80>
    ServerAdmin xxxxxxx
    DocumentRoot "/var/html/ss/public"
    ServerName ss.itman.win
    RewriteEngine on
    ErrorLog "|/usr/sbin/cronolog /application/apache/logs/ss_error_$(date +%w).log"
    CustomLog "|/usr/sbin/cronolog /application/apache/logs/ss_access_$(date +%w).log" combined
</VirtualHost>

**Comment by weiweimao1991** [comment]
好了，要开启重写功能  本来AllowOverride None的改了下就好了
<Directory "/usr/share/zabbix">
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
</Directory>

**Comment by myfingerhurt** [comment]
For more detailed information of how to enable AllowOverride for LAMP, or you have issues about Page NOT FOUND kind of error except the home page, please do the following instructions told as below.

https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite-for-apache-on-ubuntu-14-04
