### ISSUE TITLE
Unable to load template file 'index.tpl'

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#517]
## 运行环境

* PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun  8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]# 

* ss-panel version/ ss-panel版本:
最新的master分支

* 其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v   
nginx version: nginx/1.6.2
[root@localhost public]# 

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]# 

### Description of the problem / 问题描述
在这里输入描述信息.
 SmartyException

Unable to load template file 'index.tpl'
Open: /home/ss-panel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php

            // checks if template exists
            if (!$this->source->exists) {
                if ($parentIsTpl) {
                    $parent_resource = " in '{$this->parent->template_resource}'";
                } else {
                    $parent_resource = '';
                }
                throw new SmartyException("Unable to load template {$this->source->type} '{$this->source->name}'{$parent_resource}");
            }
            // disable caching for evaluated code

**Comment by orvice** [comment]
.env的theme是否有配置

**Comment by winer632** [comment]
//  ss-panel v3 配置
//
// !!! 修改此key为随机字符串确保网站安全 !!!
key = 'jlJ2EI(*@37**$I#)TI"@ 89WJJH>><s'
env = 'prod'  // 正式环境请保持env为prod确保安全
debug =  'true'  //  正式环境请确保为false
appName = 'ss-panel3'             //站点名称
baseUrl = 'https://www.google.com'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'sha256'       // 密码加密   可选 md5,sha256
salt = ''               // 密码加密用，从旧版升级请留空
theme    = 'break'   // 主题
// v3.4 后使用 session代替authDriver
// session,cache  可选 file/redis
session = 'redis'
cache   = 'redis'
tokenDriver = 'db'
// mu key 用于校验ss-go mu的请求
muKey = ''
// 邮件
mailDriver = 'mailgun'   // mailgun   #smtp不在支持,仅供测试

// 注册限制,每天每个ip能注册的次数
ipDayLimit = '10'

// 邮箱验证设置
emailVerifyEnabled = 'true' // 是否开启注册时邮箱验证 (true:开启 false:关闭)
emailVerifyCodeLength = '8'  // 邮箱验证代码长度
emailVerifyTTL = '30'        // 验证代码有效时间 单位分钟

// 用户签到设置
checkinTime = '22'      // 签到间隔时间 单位小时
checkinMin = '93'       // 签到最少流量 单位MB
checkinMax = '97'       // 签到最多流量

//
defaultTraffic = '5'      // 用户初始流量 单位GB
// 注册后获得的邀请码数量
inviteNum = '5'

// 记录流量日志到dynamodb ,beta,请勿开启
log_traffic_dynamodb = 'false'

# database 数据库配置
db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'sspanel'
db_username = 'root'
db_password = 'sOHSS*)@@)#R*382984'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

# redis
redis_scheme = 'tcp'
redis_host = '127.0.0.1'
redis_port = '6379'
redis_database = '0'
redis_pass = ''

# mailgun
mailgun_key = ''
mailgun_domain = ''
mailgun_sender = ''

# smtp
smtp_host = ''
smtp_username = ''
smtp_port = ''
smtp_name = ''
smtp_sender = ''
smtp_passsword = ''
smtp_ssl = 'true'

# aws
aws_access_key_id = ''
aws_secret_access_key = ''
aws_region = 'ap-northeast-1'
aws_ses_region = 'us-east-1'
aws_ses_sender = ''

**Comment by orvice** [comment]
theme = 'break' // 主题

resources/views目录下有break目录？

**Comment by winer632** [comment]
谢谢！现在直接访问 http://45.78.37.230/index.php OK了。
但是访问 http://45.78.37.230/ 会报错 2016/06/12 02:27:27 [error] 9518#0: *1 directory index of "/home/ss-panel/public/" is forbidden, client: 116.228.89.198, server: 45.78.37.230, request: "GET / HTTP/1.1", host: "45.78.37.230"

可是我查看了nginx的用户和ss-panel目录的权限应该是一致的，这是为什么呢？
[root@localhost home]# ll
total 8
drwxrwxrwx 12 ss-panel ss-panel 4096 Jun 12 01:22 ss-panel
drwxr-xr-x  6 root     root     4096 Jun  8 12:26 wangxx
[root@localhost home]# ps -ef | grep nginx
root      9517     1  0 02:24 ?        00:00:00 nginx: master process /usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf
ss-panel  9518  9517  0 02:24 ?        00:00:00 nginx: worker process                                          
root      9543  9131  0 02:28 pts/4    00:00:00 grep nginx
[root@localhost home]#

**Comment by orvice** [comment]
nginx配置发下

**Comment by winer632** [comment]
user  ss-panel;
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 2 256k;
    fastcgi_busy_buffers_size 256k;
    fastcgi_temp_file_write_size 256k;



    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  45.78.37.230;



				root   /home/ss-panel/public;

				
        location / {
            
            try_files $uri $uri/ /index.php$is_args$args;
        }


        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }


        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            root           /home/ss-panel/public;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;


        }


    }


 

}

**Comment by winer632** [comment]
有人吗。。。。。。。。。。。。。。。。？

**Comment by winer632** [comment]
配置文件改成这样就OK了，我也不知道对不对，但是it works for me now. 
是否会引入其他问题还有待观察。

user  ss-panel;
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 2 256k;
    fastcgi_busy_buffers_size 256k;
    fastcgi_temp_file_write_size 256k;



    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  45.78.37.230;



				root   /home/ss-panel/public/;
				index           index.php;
				
        location / {
            
            try_files $uri $uri/ /index.php$is_args$args;
        }


        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }


        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            root           /home/ss-panel/public/;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;


        }


    }


 

}
