### ISSUE TITLE
ss-panel 可否做成自动按时长或流量售卖账号，到规定时间或流量自动掐断对应账号的功能？

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#518]
PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun 8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]#

ss-panel version/ ss-panel版本:
最新的master分支

其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v

nginx version: nginx/1.6.2
[root@localhost public]#

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]#

**Comment by orvice** [comment]
你可以自己修改下ss后端
