### ISSUE TITLE
发送邮箱验证码失败--mailgun如何配置？

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#521]
PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun 8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]#

ss-panel version/ ss-panel版本:
最新的master分支

其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v

nginx version: nginx/1.6.2
[root@localhost public]#

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]#

### Description of the problem / 问题描述
在这里输入描述信息.

发送邮箱验证码失败，需要修改哪些配置才能让它正常工作起来？

现在感觉是Mailgun的配置问题。
请问这几个字段在哪里配置？

"key" => Config::get('mailgun_key'),
            "domain" => Config::get('mailgun_domain'),
            "sender" => Config::get('mailgun_sender')

**Comment by winer632** [comment]
没人回答，我搞定了。。。参考前面的issue

**Comment by sunnoy** [comment]
怎么搞定能说一下么
