### ISSUE TITLE
.env文件里面的aws相关配置是做什么的？

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#523]
PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun 8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]#

ss-panel version/ ss-panel版本:
最新的master分支

其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v

nginx version: nginx/1.6.2
[root@localhost public]#

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]#

### Description of the problem / 问题描述
在这里输入描述信息.

.env文件里面的aws相关配置是做什么的？

**Comment by orvice** [comment]
aws的ses和dynamodb需要。如果没有用到可以留空

**Comment by winer632** [comment]
这里aws指的是亚马逊的云服务吗？
