### ISSUE TITLE
点击忘记密码，然后再点击重置密码，我的注册邮箱（QQ邮箱）确实收到了重置密码的邮件。但是点击“点击此链接重置密码”的蓝色大按钮，却怎么也点不动，就好像它不是一个链接似的，没有任何反应

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#524]
PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun 8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]#

ss-panel version/ ss-panel版本:
最新的master分支

其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v

nginx version: nginx/1.6.2
[root@localhost public]#

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]#

### Description of the problem / 问题描述
在这里输入描述信息.

点击忘记密码，然后再点击重置密码，我的注册邮箱（QQ邮箱）确实收到了重置密码的邮件。
但是点击“点击此链接重置密码”的蓝色大按钮，却怎么也点不动，就好像它不是一个链接似的，没有任何反应

**Comment by winer632** [comment]
补充说明： gmail邮箱的重置密码链接可以点动，有跳转
是QQ邮箱不兼容？

**Comment by orvice** [comment]
复制的浏览器打开呢
