### ISSUE TITLE
我的ss-panel和shadowsocks-go装在同一台vps上，那么问题来了，这个在线人数统计的是ss-panel网站的在线人数呢还是同时连接到shadowsocks-go的在线人数呢？

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#526]
PHP Version /PHP版本: 
[root@localhost public]# php -v
PHP 5.6.3 (cli) (built: Jun 8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[root@localhost public]#

ss-panel version/ ss-panel版本:
最新的master分支

其他环境信息(Nginx,系统等):
[root@localhost public]# /usr/local/nginx/sbin/nginx -v

nginx version: nginx/1.6.2
[root@localhost public]#

[root@localhost public]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost public]#

### Description of the problem / 问题描述
在这里输入描述信息.

我的ss-panel和shadowsocks-go装在同一台vps上，那么问题来了，这个在线人数统计的是ss-panel网站的在线人数呢还是同时连接到shadowsocks-go的在线人数呢？

![image](https://cloud.githubusercontent.com/assets/4931801/16065446/626b1c3c-32dd-11e6-89f6-7becb34f5f00.png)

**Comment by orvice** [comment]
连接到ss节点的，5分钟内的在线人数。
