### ISSUE TITLE
请问如何修改默认的用户加密方式,默认是rc4-md5

### ISSUE THREAD

**Issue by genics** [orvice/ss-panel#540]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
数据库里面找不到这个字段~~~~~~~~~

**Comment by fiepi** [comment]
user 表这个字段
  `method` varchar(64) NOT NULL DEFAULT 'rc4-md5',

**Comment by genics** [comment]
感谢~
