### ISSUE TITLE
“站点配置 App Config” 设置报‘500’错误

### ISSUE THREAD

**Issue by monokoo** [orvice/ss-panel#545]
*\* 开issue前请确认: **
- 安装问题等错误请开启debug模式,并附上debug log
- 安全问题请发邮箱 sspanel#orx.me
- 未填写运行环境的issue将会被直接关闭
- 一个issue请只题一个问题,多个问题分多个issue开.
## 运行环境
- PHP Version /PHP版本: 7.0.7
- ss-panel version/ ss-panel版本:最新源码
- 其他环境信息(Nginx,系统等):nginx version: nginx/1.10.0
  centos7，mysql 5.7
### Description of the problem / 问题描述

在这里输入描述信息.
填写完内容后点“更新配置”提示 错误500，这个错误应该从哪排查呢。另外不同节点设置不同的混淆和协议这个目前有啥办法支持吗  想尝试自己改下前端，后端PHP不懂。。

**Comment by YZBoo** [comment]
777权限

**Comment by monokoo** [comment]
storage目录已经是777权限了

**Comment by monokoo** [comment]
我把全站文件都给了777权限。添加节点没问题。生成邀请码，站点配置都报500错误，求助呀

**Comment by orvice** [comment]
看下nginx是否有error log

**Comment by monokoo** [comment]
nginx error log 没有报错内容，开了debug模式，不过app.log里面也没有报错 @orvice ，求分析，还能从哪入手呢

**Comment by monokoo** [comment]
@orvice 基本问题是找到了，因为数据库mysql版本太新的原因，我用的5.7 降级到5.5就好了。略感无语

**Comment by monokoo** [comment]
导入数据库的时候，每导入一条都提示warning，具体warning是什么 show warnings也没内容…

**Comment by Anoneko** [comment]
Debian7，nginx 1.9.14，PHP 7.0.5，MySQL 5.7.12，发生相同情况，没有报错。

**Comment by monokoo** [comment]
@Anoneko 可以执行这条语句之后看看 
ALTER TABLE `ss_invite_code` CHANGE `created_at` `created_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHANGE `updated_at` `updated_at` TIMESTAMP NOT NULL DEFAULT '2016-06-01 00:00:00';

**Comment by Anoneko** [comment]
#385 
@monokoo 感谢，邀请码已能生成，但添加节点还是会报500。

**Comment by dotedu** [comment]
@monokoo 修改配置报错的问题找到了吗？

**Comment by monokoo** [comment]
@dotedu 找到了，因为mysql版本比较新，sql语句有些地方兼容性不好。排除其他因素之后，还抱错那就把数据库里面的字段默认值为0000-00-00的改为具体的日期比如2016-08-01

**Comment by seon212** [comment]
完美！MySQL 5.7.16 出现同样问题，生成邀请码500错误，站点配置500错误，呃...已解决。

**Comment by xiaobailong24** [comment]
CentOS-7 LinuxEye lnmp一键安装包（Updated: 2016-11-2）MySQL（ 5.7.16）生成邀请码500错误，站点配置500错误。
MySQL改为5.5问题解决
