### ISSUE TITLE
Mailgun 550 有没有好的解决方法？

### ISSUE THREAD

**Issue by MoeGakuen** [orvice/ss-panel#553]
Mailgun日志返回`550 Ip frequency limited.`
是发信服务器IP被限制，有没有好的解决方法？
而且Mailgun发送成功也只是`Accepted`，基本上也收不到。

**Comment by MoeGakuen** [comment]
自己加入了 SendCloud 替代 Mailgun，国内友好。完结此单

**Comment by gtihubAlimjan** [comment]
我也是sendcloud不过不成功提示500错误。你知道怎么解决吗？
