### ISSUE TITLE
希望manyuser支持节点信息统计

### ISSUE THREAD

**Issue by liyangio** [orvice/ss-panel#558]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP7.0
* ss-panel version/ ss-panel版本:3.4.2
* 其他环境信息(Nginx,系统等):1.10.1

### Description of the problem / 问题描述
我是用shadowsocks manyuser 来搭建的后端，可是目前go mu的支持统计节点信息，而这个却不支持，希望作者能够支持这个功能，目前只能用python脚本来每5分钟往db里插一次，这样日志会比较多。
感谢作者制作了这个工具。好评！！！
还有就是mailgun需要的一个表作者没有整合到SQL脚本中。

**Comment by monokoo** [comment]
https://github.com/breakwa11/shdowsocks 这个现在也支持统计节点信息了

**Comment by liyangio** [comment]
安装方法是一样的吗？

**Comment by monokoo** [comment]
一样的 @liyangio

**Comment by liyangio** [comment]
@monokoo 嗯嗯，那我按照原来的教程装一台试试，对了ss-panel的流量记录菜单是不是就可以用了?

**Comment by monokoo** [comment]
流量可以记录了

**Comment by liyangio** [comment]
@monokoo 恩恩，使用破娃酱的分支流量统计，节点信息之类的都已经搞定了。
