### ISSUE TITLE
流量统计到2G之后就不再更新了，有时甚至会减少。 比如我手动把user表里面的d字段改为3G，然后重启shadowsocks-go，流量自动变成2G。

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#560]
流量统计到2G之后就不再更新了，有时甚至会减少。
比如我手动把user表里面的d字段改为3G，然后重启shadowsocks-go，流量自动变成2G。

**Comment by monokoo** [comment]
shadowsocks-go的问题

**Comment by winer632** [comment]
ss-panel的问题，我在自己的站上已经改好了，在这里也提交Pull request了。

**Comment by monokoo** [comment]
我这没遇到啊，你说的用户流量统计我这里可以超过2G的啊

**Comment by winer632** [comment]
你用的php7?php7里面int貌似会自动转为long，我用的php6，int到2G以后会溢出

**Comment by monokoo** [comment]
确实是PHP7

**Comment by winer632** [comment]
那就是了，原来的程序处理没有考虑到PHP6，要么加个说明，要么就按照我的pull request改一下
