### ISSUE TITLE
Docker里的Mysql没运行阿？

### ISSUE THREAD

**Issue by pcwuyu** [orvice/ss-panel#566]
start create admin accountPHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /opt/ss-panel/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /opt/ss-panel/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'ssuser', 'sspasswd', Array)
#1 /opt/ss-panel/vendor/illuminate/database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /opt/ss-panel/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors{closure}()
#4 /opt/ss-panel/vendor/illuminate/database/Connection.php(846): call_user_func(Object(Closure))
#5 /opt/ss-panel/vendor/illuminate/database/Connection.php(714): Illuminate\Database\Connection->getPdo()
#6 in /opt/ss-panel/vendor/illuminate/database/Connectors/Connector.php on line 55

**Comment by iliul** [comment]
注意一下内存大小，我发现小于800M内存会出现这个问题，无法启动MySQL。

**Comment by iliul** [comment]
修改MySQL配置，调小运行内存，我的可行了，你试下，希望对你有帮助！

```SQL
performance_schema_max_table_instances=200
table_definition_cache=200
table_open_cache=128
```

**Comment by HamGuy** [comment]
@pcwuyu 请问这个问题解决了吗，我也遇到了，郁闷死了
@iliul 请教下怎么调运行内存啊？

**Comment by iliul** [comment]
@HamGuy 我上面的回答中已经写了调小内存的配置，设置上重启MySQL就行了！

**Comment by HamGuy** [comment]
@iliul 我修改了下 /etc/mysql/my.cnf， 不过貌似没用啊

**Comment by iliul** [comment]
@HamGuy 我当时是可以的，[再参考下这里呢？](http://stackoverflow.com/questions/1178736/mysql-maximum-memory-usage)

**Comment by zhao0625** [comment]
跟另一个mysql的docker容器冲突了怎么处理呢。。

**Comment by orvice** [comment]
https://sspanel.xyz/docs/install/docker
