### ISSUE TITLE
LNMP环境下部署失败。

### ISSUE THREAD

**Issue by xiqingongzi** [orvice/ss-panel#57]
LNMP环境下部署失败。
使用官方原版 master
报错。
Parse error: syntax error, unexpected '[', expecting ')' in /web/lib/config.php on line 26

**Comment by orvice** [comment]
php版本多少

**Comment by ikzzdd** [comment]
这应该是缺少pdo 吧？

**Comment by orvice** [comment]
PHP版本确认下是不是5.4+

**Comment by ikzzdd** [comment]
试了PHP-5.6.4 mysql-5.5.34 ，同样不行。

**Comment by orvice** [comment]
报什么错误? php5.6

**Comment by ikzzdd** [comment]
浏览器只报500， 具体哪里出问题抱歉我不太懂应该查哪里的日志。 自从config 里用了medoo后（0.3.5开始?），我这的软体环境就不能正常运行了

**Comment by xiqingongzi** [comment]
5.3.27.需要5.4+啊，我自己手动升级一下。

**Comment by ikzzdd** [comment]
重新安装了新的LMNP环境 ， 顺利部署。 看来是之前环境面板的问题

**Comment by xiqingongzi** [comment]
升级了PHP，已经正常部署。
SS后端和Panel前端需要公用数据库么？
希望新的版本可以将NODE和面板 数据库分开

**Comment by orvice** [comment]
对，共用数据库
