### ISSUE TITLE
出错比例很高

### ISSUE THREAD

**Issue by sunyh87** [orvice/ss-panel#578]
*\* 开issue前请确认: **
- 安装问题等错误请开启debug模式,并附上debug log
- 安全问题请发邮箱 sspanel#orx.me
- 未填写运行环境的issue将会被直接关闭
- 一个issue请只题一个问题,多个问题分多个issue开.
## 运行环境
- PHP Version /PHP版本: 
  ss-panel version/ ss-panel版本:
  其他环境信息(Nginx,系统等):
### Description of the problem / 问题描述

在这里输入描述信息.
为什么配合SSR、rm等后端连接时出错比例很高，导致页面延迟的厉害，还是同样的后端，换了一个shadowsocks-panel前端面板出错比例一直保持0，是哪里的问题？这样肯定不是后端的问题了

**Comment by sunyh87** [comment]
已解决

**Comment by afeng1991** [comment]
是什么问题导致的呢
