### ISSUE TITLE
any body speaks english here?

### ISSUE THREAD

**Issue by baselkhateeb** [orvice/ss-panel#585]
*\* 开issue前请确认: **
- 安装问题等错误请开启debug模式,并附上debug log
- 安全问题请发邮箱 sspanel#orx.me
- 未填写运行环境的issue将会被直接关闭
- 一个issue请只题一个问题,多个问题分多个issue开.
## 运行环境
- PHP Version /PHP版本: 
- ss-panel version/ ss-panel版本:
- 其他环境信息(Nginx,系统等):
### Description of the problem / 问题描述

在这里输入描述信息.

**Comment by orvice** [comment]
hi?

**Comment by baselkhateeb** [comment]
Can you please encourage everybody to use English, as Open Source is cross nation, and should encourage any body from any culture to contribute, My native language is Arabic,, but I wouldn't use it to document source code or on github at all.

**Comment by Asheblog** [comment]
you can use google translante

**Comment by orvice** [comment]
hi, in dev branch, we have add multiple lang support. and it would be release in next week.

**Comment by relei1988** [comment]
Arabic speaking country also got nation firewall prob?lol

**Comment by orvice** [comment]
Last version has been support english
