### ISSUE TITLE
开始多语言支持, init multiple lang support

### ISSUE THREAD

**Issue by orvice** [orvice/ss-panel#590]
dev分支开始多语言支持，目前开始逐步将添加英文支持 
https://github.com/orvice/ss-panel/tree/dev/resources/lang/en

并将在英文翻译完成后添加中文翻译。

**Comment by ziyaointl** [comment]
我想帮助翻译template文件，请问应该从哪里开始呢

**Comment by orvice** [comment]
@ziyaointl 参考 https://github.com/orvice/ss-panel/wiki/i18n
