### ISSUE TITLE
删除帐号后为何还可使用

### ISSUE THREAD

**Issue by saladinxp** [orvice/ss-panel#608]
### Description of the problem / 问题描述

在这里输入描述信息.

今天发现，有的账号我删除以后 为何该账号还可以使用

**Comment by orvice** [comment]
使用哪种后端呢

**Comment by Asheblog** [comment]
是不是节点服务端没有更新？你是指SS还可以使用吗

**Comment by saladinxp** [comment]
@orvice 
用的这个 https://github.com/mengskysama/shadowsocks-rm.git

**Comment by Asheblog** [comment]
用破瓦匠的

**Comment by Asheblog** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues

**Comment by saladinxp** [comment]
@Asheblog 你说的服务端更新是什么意思呢，就是sspanel v3 3.39 删除某用户账号以后，他今天告诉我他还能用，后台找不到他的账号和端口了，我把其他帐号改为他的端口后并且关闭账号后才好

**Comment by Asheblog** [comment]
你遇到这种情况有没有试过重启节点服务器？让节点服务器重新获取sspanel用户端数据？

**Comment by saladinxp** [comment]
@Asheblog 没有重启过服务器，需要重启一下？

**Comment by Asheblog** [comment]
给你个测试建议

1.首先还是建议你把后端换成破瓦酱的

2.sspanel删除某个账户

3.重启节点服务器，让节点服务器重新获取用户数据

4.看看还能不能用？如果没猜错，此时应该不能用了那个端口

**Comment by Asheblog** [comment]
最好你测试一下换成破瓦酱的后端，然后直接删除账户信息，不重启节点服务器的情况下看看还能不能正常链接使用，23333333333333333333

**Comment by saladinxp** [comment]
@Asheblog 我晚点测试下吧，谢谢

**Comment by saladinxp** [comment]
@orvice @Asheblog 
没换东西，直接重启就好了
