### ISSUE TITLE
站点正常显示，但邀请码/登录/注册/admin页面全为404错误。

### ISSUE THREAD

**Issue by Heisosmith** [orvice/ss-panel#617]
*\* 开issue前请确认: **
- 安装问题等错误请开启debug模式,并附上debug log
- 安全问题请发邮箱 sspanel#orx.me
- 未填写运行环境的issue将会被直接关闭
- 一个issue请只题一个问题,多个问题分多个issue开.
## 运行环境
- PHP Version /PHP版本:  PHP 5.6.26-0+deb8u1 (cli)
- ss-panel version/ ss-panel版本:  ss-panel-3.3.9
- 其他环境信息(Nginx,系统等):  ubuntu 14.04  3.13.0-36-generic
                                            Apache/2.4.10
                                            enable mod_rewrite
                                            使用重写http到https
                                            重写规则:
                                                  RewriteEngine On
                                                  RewriteCond %{HTTPS} !=on
                                                  RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
### Description of the problem / 问题描述

打开站点( https://canyong.me )后，站点首页正常显示。但点击邀请码/注册/登录，还有/admin都是404 Not Found。

**Comment by Asheblog** [comment]
重装一下环境跟sspanel吧

**Comment by Heisosmith** [comment]
已确认。是mysql不自启动。3306端没打开。
可能是多版本冲突。
重装系统，再重装lnmp环境后一切正常。

**Comment by zhangxudong97** [comment]
这个问题今天我也遇到了，已经解决。
大概是nginx的配置有问题，我重新设置了下虚拟主机和conf就可以了
