### ISSUE TITLE
不小心删除ss-panel文件夹，重新安装后无法打开

### ISSUE THREAD

**Issue by GaHoKwan** [orvice/ss-panel#634]
网页只显示run();

error.log显示AH00491: caught SIGTERM, shutting down

后端显示：
DEBU[0000] debug on                                     
INFO[0000] PONG                                         
DEBU[0000] <?php

//  PUBLIC_PATH
define('PUBLIC_PATH', __DIR__);

// Bootstrap
require PUBLIC_PATH . '/../bootstrap/app.php';

// Build Slim App
$app = require BASE_PATH . '/app/routes.php';

// Run ButterFly!
$app->run();
 
E1208 03:24:46.680304     850 boot.go:36] Get User Error%!(EXTRA *json.SyntaxError=invalid character '<' looking for beginning of value)

**Comment by orvice** [comment]
@GaHoKwan php环境都有问题了吧

**Comment by GaHoKwan** [comment]
好吧 重装php就好了
