### ISSUE TITLE
3.4版本是用什么框架写的？是自己写的框架吗？

### ISSUE THREAD

**Issue by kelelee** [orvice/ss-panel#636]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

**Comment by gucong3000** [comment]
人家不是说了么，基于[LightFish](https://github.com/Pongtan/LightFish)开发

文档第二行：
> Let's talk about cat. Based on LightFish.
