### ISSUE TITLE
我想添加一个连接，一直出错。

### ISSUE THREAD

**Issue by alstarking** [orvice/ss-panel#637]
我在\resources\views\material\user\main.tpl新增加一个连接。
![1](https://cloud.githubusercontent.com/assets/24618335/21577277/33724b26-cf90-11e6-8e74-585a0be21fe6.jpg)
之后我在user里面随便找了一个tpl复制一份（node.tpl）并改名为new1.tpl。但是打不开啊，出错。。是不是需要在别的地方添加东西？？

**Comment by MoeGakuen** [comment]
php文件也要改的哥

**Comment by alstarking** [comment]
@MoeGakuen  是app/routes.php里的文件吗？？

**Comment by alstarking** [comment]
@MoeGakuen ![1](https://cloud.githubusercontent.com/assets/24618335/21577540/1dd2fb86-cf99-11e6-91e1-d0e64abc8d37.jpg)
我这块也添加了。。好像还是错误。。

**Comment by MoeGakuen** [comment]
那么你的`UserController.php`文件里面有`public function new1`吗

**Comment by alstarking** [comment]
![1](https://cloud.githubusercontent.com/assets/24618335/21577626/ba0f1c98-cf9c-11e6-94b2-2d057ae252e5.jpg)
好像很难修改，我把完整的node复制了一份改名为new1，如果把里面的内容清空的话，出错。不清空的，改resources\views\default\user\new1.tpl文件无效，依然走node.tpl里的信息。。 @MoeGakuen  大神。。

**Comment by zhaoxitao** [comment]
要添加一个页面，需要修改四个地方：
1、首页模版文件 main.tpl 里添加导航链接
2、routes.php 里添加路由指向对应控制器
3、对应的控制器里（如果是前台页面就是 HomeContrlooer.php）添加添加对应 function，传递参数并指向前段模板文件
4、编辑前端模板文件
