### ISSUE TITLE
PDOException (1045) HELP SQLSTATE[HY000] [1045] Access denied for user 'root'@'127.0.0.1' (using password: YES)

### ISSUE THREAD

**Issue by winer632** [orvice/ss-panel#639]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
PHP 5.6.3 (cli) (built: Jun  8 2016 10:50:20) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

* ss-panel version/ ss-panel版本:
2016.06.15版本
* 其他环境信息(Nginx,系统等):
nginx  1.6.2
CentOS release 6.8 (Final)

### Description of the problem / 问题描述
在这里输入描述信息.

更改了数据库user表last_get_gift_time字段为end_time
![image](https://cloud.githubusercontent.com/assets/4931801/21580987/8349f966-d056-11e6-8916-4a2bff97fa16.png)

更改了index.tpl的最后签到时间为到期时间
更改了index.tpl的<td>{$user->lastCheckInTime()}</td>为<td>{$user->endTime()}</td>
![image](https://cloud.githubusercontent.com/assets/4931801/21580985/66ffa8f0-d056-11e6-8748-58283157d544.png)

user.php增加了
public function endTime()
    {
        return Tools::toDateTime($this->attributes['end_time']);
    }
![image](https://cloud.githubusercontent.com/assets/4931801/21580989/8a9691e8-d056-11e6-9343-b1200725e331.png)

然后就出现报错了

![image](https://cloud.githubusercontent.com/assets/4931801/21580960/38fb9a50-d055-11e6-9a40-f26578955c2a.png)

**Comment by orvice** [comment]
@winer632 数据库是否能连上？

**Comment by winer632** [comment]
可以的
![image](https://cloud.githubusercontent.com/assets/4931801/21580993/e7c024f6-d056-11e6-8186-f372e8c62f75.png)

**Comment by orvice** [comment]
@winer632 邀请码页面能打开？

**Comment by winer632** [comment]
打不开
![image](https://cloud.githubusercontent.com/assets/4931801/21581001/2bde9c30-d057-11e6-8957-58871ab03435.png)

**Comment by winer632** [comment]
搞定了

**Comment by orvice** [comment]
@winer632 url不能随便写

**Comment by winer632** [comment]
@orvice url的作用是？

**Comment by orvice** [comment]
@winer632 有些地方用来构建url
