### ISSUE TITLE
关于maligun，以及其他邮件提供

### ISSUE THREAD

**Issue by HolaJam** [orvice/ss-panel#641]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 7.07
* ss-panel version/ ss-panel版本:v3
* 其他环境信息(Nginx,系统等):Nginx 1.10.0

### Description of the problem / 问题描述
在这里输入描述信息.

是否支持*除maligun以外*的邮件提供？

**Comment by orvice** [comment]
@HolaJam 目前只有mailgun，v4 后面会支持更多的mail service
