### ISSUE TITLE
 php xcat sendDiaryMail报错

### ISSUE THREAD

**Issue by thank243** [orvice/ss-panel#645]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
* ss-panel version/ ss-panel版本:3.4.2
* 其他环境信息(Nginx,系统等):nginx,debian 8

### Description of the problem / 问题描述
root@Senis:/home/www/ss-panel# php xcat sendDiaryMail
Send daily mail to user: 1Send daily mail to user: 2PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs!' in /home/www/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:127
Stack trace:
#0 /home/www/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/www/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('sandbox036889bf...', Array, Array)
#2 /home/www/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('sandbox036889bf...', Array, Array)
#3 /home/www/ss-panel/app/Services/Mail/Mailgun.php(50): Mailgun\Mailgun->sendMessage('sandbox036889bf...', Array, Array)
#4 /home/www/ss-panel/app/Services/Mail.php(71): App\Services\Mail\Mailgun->send('ztqXXXXX@ho...', 'Senis-\xE6\xAF\x8F\xE6\x97\xA5\xE6\xB5\x81...', '<!DOCTYPE html ...', Arr in /home/www/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 127

似乎一个邮件都没发出去

**Comment by vcnovember** [comment]
+1
API更新了吗？

**Comment by LYJSPEEDX** [comment]
同样的问题 反复更改mailgun配置仍报错

**Comment by lin710839742** [comment]
+1
