### ISSUE TITLE
能把混淆和协议两项扫进去吗？

### ISSUE THREAD

**Issue by jinshijie** [orvice/ss-panel#647]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: php5.6
* ss-panel version/ ss-panel版本:ss-panel v3 
* 其他环境信息(Nginx,系统等):nginx1.0

### Description of the problem / 问题描述
扫描时，不能把协议及混淆两项扫进去，需手工设置才行，不知哪里设置才能实现自动扫描这两项功能呢
【如图所示】
<img src="https://raw.githubusercontent.com/jinshijie/tupian/master/%E5%8D%8F%E8%AE%AE%E5%92%8C%E6%B7%B7%E6%B7%861.png"/>

**Comment by orvice** [comment]
新版已经支持
