### ISSUE TITLE
v3 版本，去掉每月流量重置了 么？若不是，如何设置

### ISSUE THREAD

**Issue by cnme** [orvice/ss-panel#651]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

用户流量无法自动重置

**Comment by orvice** [comment]
cronjob添加
```
cd /path/to/ss-panel && php xcat resetTraffic
```

**Comment by erqqnafdgg6w** [comment]
@orvice 您好，我在crontab添加4 1 1 * * cd /data/wwwroot/我的网站/ss-panel && php xcat resetTraffic发现并没有重置。crontab日志显示执行了这个命令。我尝试直接cd /data/wwwroot/我的网站/ss-panel && php xcat resetTraffic执行是可以的，4 1 1 * * 换后面 /sbin/reboot确实机器被重启了。
我不知道是什么原因
