### ISSUE TITLE
大大，请问V3如何修改默认的0.5流量比例？

### ISSUE THREAD

**Issue by ysbreh** [orvice/ss-panel#653]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

请问V3如何修改默认的0.5流量比例？

**Comment by MoeGakuen** [comment]
我的哥，不是可以直接设置吗，你确定你真的使用过吗

**Comment by ysbreh** [comment]
这个设置无效，还是按照默认0.5的比例的。节点显示消耗了1000mb，总流量那儿显示只消耗了500多..

**Comment by ysbreh** [comment]
@MoeGakuen 我是想知道前端默认的0.5在那里修改...，节点上设置似乎对默认的0.5无效

**Comment by thank243** [comment]
去ss配置文件设置，这边只是显示而已，不涉及统计。主要统计功能还是在ssr那边
