### ISSUE TITLE
如何更新版本

### ISSUE THREAD

**Issue by miaoyanginfo** [orvice/ss-panel#654]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:3.4.2
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
现在是SS-PANEL 3.4.2 ,请问有了更新之后如何升级？谢谢

**Comment by thank243** [comment]
git pull

**Comment by wj985712588** [comment]
git pull
error: Your local changes to the following files would be overwritten by merge:
        app/Controllers/AdminController.php
        app/Controllers/HomeController.php
        app/Controllers/UserController.php
        app/Services/Mail/Smtp.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by orvice** [comment]
备份.env文件重新覆盖
