### ISSUE TITLE
api的token是有过期时限的吗

### ISSUE THREAD

**Issue by lan894734188** [orvice/ss-panel#657]
## 运行环境

* PHP Version /PHP版本: 7
* ss-panel version/ ss-panel版本:3.4
* 其他环境信息(Nginx,系统等):nginx

### Description of the problem / 问题描述
在这里输入描述信息.

token是有过期期限的吗
另外token是存在redis的？

**Comment by orvice** [comment]
@lan894734188 有，另外这部分在重写，不建议现在使用

**Comment by lan894734188** [comment]
@orvice get

**Comment by orvice** [comment]
api已经完成，这几天会添加文档
