### ISSUE TITLE
管理员添加节点页面加密选项应该要加上 select 标签。

### ISSUE THREAD

**Issue by zhaoxitao** [orvice/ss-panel#659]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.
RT，在 resources/views/default/admin/node/create.tpl 模板文件的加密方式 {foreach} 位置，应该要加上

`<select class="form-control" id="custom_method"> </select>`

标签才能显示为下拉菜单。请作者确认，谢谢。

**Comment by hudson6666** [comment]
pr吧 我觉得是bug

**Comment by hudson6666** [comment]
另外建议将标题修改为`管理员添加节点页面加密选项 select 标签 id 错误`
