### ISSUE TITLE
为什么不支持STMP发邮件了，mailgun会被QQ邮箱拒收

### ISSUE THREAD

**Issue by 331969102** [orvice/ss-panel#669]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
为什么不支持STMP发邮件了，mailgun会被QQ邮箱拒收

**Comment by yywudi** [comment]
QQ邮箱的锅。把mailgun的发邮件IP屏蔽了。其他邮箱都正常

**Comment by hudson6666** [comment]
支持的吧 程序带phpmail 我用的好好的呢 不知道为什么.env里写不受支持 @orvice

**Comment by orvice** [comment]
#742
