### ISSUE TITLE
apache登录500错误

### ISSUE THREAD

**Issue by ZGWS88** [orvice/ss-panel#670]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.6.22
* ss-panel version/ ss-panel版本:3.4.5
* 其他环境信息(Nginx,系统等):centos7 apache2.2.31 

### Description of the problem / 问题描述
创建管理员后,在页面登录显示"出错了!发生错误500"

**Comment by lydasia** [comment]
解决了大大小小一堆问题后同遇到了这个问题，这个前端真的是太难搞了。
![p](https://cloud.githubusercontent.com/assets/22676960/23572213/d3fcc6a8-006d-11e7-96e5-f52c37885105.png)
