### ISSUE TITLE
流量记录没有单位

### ISSUE THREAD

**Issue by zyd2001** [orvice/ss-panel#671]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.6
* ss-panel version/ ss-panel版本:最新
* 其他环境信息(Nginx,系统等):1.10

### Description of the problem / 问题描述
在这里输入描述信息.
流量记录有的时候没有单位，是有问题吗

**Comment by luyuxuan** [comment]
没有问题。没有单位是还没有用到1024字节，也就是1kb
