### ISSUE TITLE
put ss-panel into sub-directory on a web site such as http://your-domain/ss/ss-panel/

### ISSUE THREAD

**Issue by myfingerhurt** [orvice/ss-panel#682]
## 运行环境  ubuntu x64 server 16.04 LTS

* PHP Version /PHP版本:  php7.0
* ss-panel version/ ss-panel版本:  v3.4.5
* 其他环境信息(Nginx,系统等): LAMP

### Description of the problem / 问题描述
在这里输入描述信息.

need to be able put ss-panel into sub-directory on a web site such as http://your-domain/ss/ss-panel/

please give me a guide of how to do it?

**Comment by hudson6666** [comment]
Excuse me but may I ask why not set an independent virtual host instead?
