### ISSUE TITLE
怎么在注册时多插入两个数据库字段

### ISSUE THREAD

**Issue by iansomer** [orvice/ss-panel#685]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.5.12
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
找了与User用户注册相关的class文件，发现app/Controllers/AuthController.php的registerHandle函数是执行用户注册逻辑的，里面有个User->save()，可是我怎么找也找不到这个save()的函数在哪里，因为我需要在用户注册时增加两个字段，请问这个在哪里可以加？

**Comment by hudson6666** [comment]
在数据库表中插入这两个字段，然后直接用就行了。

譬如给user表加了个字段叫`is_frozen`，注册的时候就加上
`$user->is_frozen = false;`
然后一起
`$user->save();`
就可以了
查询和修改同理

User这个模型是派生自Model这个基类的，定义在app/Models/User.php里。save是Model基类的方法

这是你第一次用MVC吗。作者这个是基于  [Lightfish](https://github.com/Pongtan/LightFish) 框架，用的是 [Slim 和 Eloquent](https://www.slimframework.com/docs/cookbook/database-eloquent.html)
[Eloquent ORM 的文档](http://d.laravel-china.org/docs/5.4/eloquent)

**Comment by iansomer** [comment]
Thanks
