### ISSUE TITLE
lanmp环境安装完safari白屏，chrome说无法处理请求http error 500

### ISSUE THREAD

**Issue by mooyxu** [orvice/ss-panel#687]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.6
* ss-panel version/ ss-panel版本:v3
* 其他环境信息(Nginx,系统等): 
lanmp环境，(lnmp.org 1.4版本)
nginx 1.10.3
apache 2.2.32
php最初5.5，升到5.6

### Description of the problem / 问题描述
在这里输入描述信息.
配置好后，safari打开会白屏，chrome打开会显示无法处理请求http error 500。

**Comment by luyuxuan** [comment]
500错误有很多可能
php语言无任何错误提示，少写个分号也只是简单地抛出一个500错误
你主页能打开么？

**Comment by mooyxu** [comment]
@luyuxuan 当时是什么都不能打开，只有500提示。我研究了好久，现在能打开了。

**根本原因：
是php里头的open_basedir函数配置错误：没有开或没给值或给值错误（我是给值错误）。
造成给值错误的原因是，函数的值在lnmp里有很多地方被配置了，这些配置相互覆盖，虽然我更改了其中一个的值，但是最终结果被一个默认的给值给覆盖了。**

**细节过程：**
发现500错误，
查issues，发现很可能是php错误，更细得说可能是open_basedir的错误。
打开php的log查看log错误讯息。
发现自己也是open_basedir函数出错，要访问的位置没有被包含在函数值里（有值但不包括）。
在ngnix里用fastcgi_param PHP_VALUE "open_basedir=url" 把位置加入了该函数的值，覆盖导入的模块fastcgi_params.conf里的配置。
依然错误，php的log错误没变。
查找资料，发现函数主要配置在web根目录的.user.ini里、php的php.ini里、php-fpm.conf里、nginx的fastcgi_param里（或apache）。
于是挨个检查，发现php.ini和php-fpm.conf都是空值，nginx是我刚设置的，那么错误锁定到.user.ini。
.user.ini默认值是本文档，其实该值是包括ss-panel所有文件的（网站根为ss.xxxx.com/ss-panel/public，.user.ini在最外层的ss.xxxx.com/），但我依然更改到更细的位置，以测试。
依然报错，错误原因没变。
所以我又折回去检查nginx，检查它include的所有代码。
于是发现fastcgi_param里是用PHP_ADMIN_VALUE来给值，而include后，我是用PHP_VALUE给值的。而PHP_ADMIN_VALUE的给值是与报错的值相同的。
这就找到原因了，PHP_ADMIN_VALUE的优先级大于PHP_VALUE，于是把我配置的PHP_VALUE覆盖了。而PHP_ADMIN_VALUE的给值是网站根（/ss.xxxx.com/ss-panel/public），但ss-panel/public内index的运行需要访问网站根外的一些文件，也就是ss-panel的文件，这时就没有权限了。
所以，我重新用fastcgi_param PHP_ADMIN_VALUE方法在include fastcgi_param后覆盖模块里头的值。
restart，成功运行。

**总结：
像我这样错误的人肯定不是少数。
因为我用的是lnmp.org的一键包，刚装完就来装ss-panel了，是个纯净的系统。
问题的难点是，错误不大，但很难发现。
如果你没看过fastcgi_params配置模块，那你很难知道原因。

前车之鉴，希望给同样问题的人提供一个参考和思路。
附上nginx配置讯息：
`
server {
    省略；
    location ~ [^/]\.php(/|$){
        省略；
        include fastcgi.conf;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir = /home/wwwroot/ss.xxxx.com/:/temp/:/proc";
    }
}
`
**
