### ISSUE TITLE
如何更改主页上链接

### ISSUE THREAD

**Issue by leoleoasd** [orvice/ss-panel#688]
## 运行环境

* PHP Version /PHP版本: 5.6.22
* ss-panel version/ ss-panel版本:3.4.5
* 其他环境信息(Nginx,系统等): debian

### Description of the problem / 问题描述
rt，主页上的客户端下载的链接打不开，在哪里替换？
这个网站的目录结构真心难以理解

**Comment by miuchan** [comment]
这里
resources/views/default/header.tpl

**Comment by mooyxu** [comment]
@miuchan 改完无法使用，只能连接外网地址，不能链接本地的

**Comment by hudson6666** [comment]
本地的路由是定义在`app/routes.php`里的

https://www.slimframework.com/docs/objects/router.html
