### ISSUE TITLE
如何配置mailgun？

### ISSUE THREAD

**Issue by leoleoasd** [orvice/ss-panel#691]
## 运行环境

* PHP Version /PHP版本: 5.6.22
* ss-panel version/ ss-panel版本:3.4.5
* 其他环境信息(Nginx,系统等):debain7.11 x64

### Description of the problem / 问题描述
RT，如何配置mailgun？

**Comment by LYJSPEEDX** [comment]
同问 好像官方没说明关于邮件的配置？

**Comment by orvice** [comment]
升级到最新版，后台配置
