### ISSUE TITLE
关于清除流量记录

### ISSUE THREAD

**Issue by mikelei8291** [orvice/ss-panel#694]
## 运行环境

* PHP Version /PHP版本: 5.6.22
* ss-panel version/ ss-panel版本: 3.4.5
* 其他环境信息(Nginx,系统等): nginx 1.10.3 / Ubuntu 14.04 LTS

### Description of the problem / 问题描述
流量记录是不会被 `resetTraffic` 命令一并清除吗？现在数据库里都积压了几个月的流量记录，数据库大小高达几MB
ss-panel是没有相应的清除命令吗？
如果没有的话，能否加入在执行 `resetTraffic` 时同时清除流量记录和在配置文件内控制是否记录流量记录的功能？

**Comment by luyuxuan** [comment]
直接进去phpmysql  delete from 。。。 where 1

**Comment by mikelei8291** [comment]
fixed #705
