### ISSUE TITLE
打开网站 500 http://www.xxxxx.com/ss-panel/public/index.php

### ISSUE THREAD

**Issue by holyen** [orvice/ss-panel#697]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP 5.4.16
* ss-panel version/ ss-panel版本:最新
* 其他环境信息(Nginx,系统等):apache

### Description of the problem / 问题描述
在这里输入描述信息.
打开网站 http://www.xxxxx.com/ss-panel/public/index.php 返回500 服务是centos 7

**Comment by hudson6666** [comment]
如果单独开一个虚拟主机目录在`./path/to/ss-panel/public`想必是极好的
