### ISSUE TITLE
新建一个index.htm可以访问，换成V3里面index.php就错误500

### ISSUE THREAD

**Issue by sunwei945** [orvice/ss-panel#699]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP 5.6
* ss-panel version/ ss-panel版本:最新
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

全是安装完成，我在public里面，随便创建一个新的index.htm网站可以访问。
但是换成ss-panel v3 public里面的index.php，网站就提示错误500.

**Comment by sunwei945** [comment]
单独安装php mariaDB ss-panel v3 nginx，设置好了，还是提示错误500.

**Comment by chauyuen** [comment]
请开启debug模式,并附上debug log
