### ISSUE TITLE
index.php主页报错

### ISSUE THREAD

**Issue by DDMCloud** [orvice/ss-panel#701]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 5.6.27
* ss-panel version/ ss-panel版本: 3.4.5
* 其他环境信息(Nginx,系统等): IIS Windows2012 R2 X64

### Description of the problem / 问题描述
在这里输入描述信息.

Whoops \ Exception \ ErrorException (E_WARNING)
HELP
Creating default object from empty value
Open: D:\wwwroot\ss-panel\app\Services\Auth.php
    /**
     * @return User|void
     */
    public static function getUser()
    {
        if (Helper::isTesting()) {
            $user = User::first();
            $user->isLogin = true;
            return $user;
        }

**Comment by DDMCloud** [comment]
模式为testing

切换为env = 'prod' 就正常

**Comment by orvice** [comment]
@DDMCloud 肯定要prod啊

**Comment by MoeGakuen** [comment]
又一个不看注释说明的人。
