### ISSUE TITLE
升级后进入“系统维护”报错

### ISSUE THREAD

**Issue by miaoyanginfo** [orvice/ss-panel#704]
升级之后后台进入“系统维护”页面报错，打开调试模式，提示
App\Controllers\AdminController:sysinfo is not resolvable
请问大神们是哪里的问题？

**Comment by Asheblog** [comment]
https://github.com/orvice/ss-panel/issues/703

我两可以组队了，QQ：402947780

**Comment by Asheblog** [comment]
https://github.com/orvice/ss-panel/issues/703

我两可以组队了，QQ：NDAyOTQ3Nzgw

**Comment by thank243** [comment]
小弟也是

**Comment by hudson6666** [comment]
看了下 这个功能…… 怕是还差一点没写好😂😂

**Comment by hudson6666** [comment]
#705

**Comment by Cp0204** [comment]
+1

**Comment by bobscyes** [comment]
我今天刚配好ss-panel，请问访问系统维护页面报错的问题解决了吗？谢谢

**Comment by Cp0204** [comment]
https://github.com/orvice/ss-panel/pull/705/commits/1055823d091fd2b86429c80493b690603d1cfffc

app/Controllers/AdminController.php 里，加入
`public function sysinfo($request, $response, $args)
 +    {
 +        return $this->view()->display('admin/sys.tpl');
 +    }`

就可以了

**Comment by bobscyes** [comment]
好的，添加后已经可以访问了，谢谢
