### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by orangejx** [orvice/ss-panel#708]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP5.6
* ss-panel version/ ss-panel版本:v3
* 其他环境信息(Nginx,系统等):Apache

### Description of the problem / 问题描述
在这里输入描述信息.

Fatal error: Using $this when not in object context in /WWWNET/ss.sof618.com/WEB/vendor/illuminate/config/Repository.php on line 49
这个是PHP的提示，不是很懂=。=

**Comment by sadxt** [comment]
环境的话是XAMPP for Linux一键包，PHP版本的话应该是5.6.30,

**Comment by sadxt** [comment]
![qq 20170503063920](https://cloud.githubusercontent.com/assets/19427231/25642280/6fc3648e-2fcb-11e7-9385-38c3ab951a0d.png)
start create admin accountPHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'sspanel', 'tA8gXtvI6ANoZEJ...', Array)
#1 /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connection.php(875): call_user_func(Object(Closure))
#5 /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connection.php(743): Illuminate\Database\Connection->getPdo()
#6 / in /WWWNET/ss.sof618.com/WEB/vendor/illuminate/database/Connectors/Connector.php on line 55
前面的问题倒是解决了，但是这个问题卡了好久了，就是解决不了

**Comment by hudson6666** [comment]
composer install 了么

**Comment by sadxt** [comment]
composer install了，再次执行后提示没有安装和更新了。
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

**Comment by jsplyy** [comment]
相同问题 求解

**Comment by ishamo** [comment]
@jsplyy 兄台解决了吗？
