### ISSUE TITLE
站点配置405错误

### ISSUE THREAD

**Issue by q601904795** [orvice/ss-panel#710]
## 运行环境

* PHP Version /PHP版本: PHP7.0
* ss-panel version/ ss-panel版本:v3.4.5
* 其他环境信息(Nginx,系统等):ubuntu 14.04  nginx 1.4.6

### Description of the problem / 问题描述
站点配置提示405错误
nginx的erorr.log没有错误日志
控制台看到这个
[https://zry-blog.top/wp-content/uploads/2017/05/5L5HNOWEC9R9Z361_2V.png](url)
看到另外一个issue上面把PUT改为POST的方法 并没有什么用
新人小白求指点
谢谢

**Comment by orvice** [comment]
Fixed
