### ISSUE TITLE
Wingy无法识别节点二维码

### ISSUE THREAD

**Issue by bobscyes** [orvice/ss-panel#712]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP 7.0
* ss-panel version/ ss-panel版本: ss-panel v3
* 其他环境信息(Nginx,系统等): Nginx 10.0

### Description of the problem / 问题描述
我使用iOS App Wingy来扫描节点二位码时提示Invalid Configuration，请问能否排查一下？不排除是App的Bug

**Comment by buutuud** [comment]
mark

**Comment by XiaoFaye** [comment]
我的可以哦，很正常。

**Comment by bobscyes** [comment]
难道是人品问题？还是我哪里没设置好？

不过这也不是重要问题吧，就是麻烦一些，要手动配置
