### ISSUE TITLE
编辑用户信息页面左上角和右上角个人信息加载问题

### ISSUE THREAD

**Issue by mikelei8291** [orvice/ss-panel#715]
## 运行环境
- PHP Version /PHP版本: `5.6.22`
- ss-panel version/ ss-panel版本: `3.4.5`
- Nginx: `1.10.3`

## Description of the problem / 问题描述
用户管理编辑用户信息的页面，左上角和右上角的用户个人信息会变成被编辑用户的个人信息，而不是登录的管理员的个人信息
我注意到 v2 的时候并不是这样的，看了一下似乎是因为 v3 的编辑页加载的时候直接用了一个 user 变量，不知道这个是 bug 还是 feature？

**Comment by hudson6666** [comment]
feature吧

**Comment by mikelei8291** [comment]
@hudson6666 感觉并不是什么好 feature...

**Comment by hudson6666** [comment]
额我觉得挺方便的因为我观察一个用户的昵称的时候会习惯往左上角瞥……

这是什么根本不重要吧😂你要是有强迫症的话可以改掉然后pr
