### ISSUE TITLE
升级后就这样了

### ISSUE THREAD

**Issue by Altonhe** [orvice/ss-panel#717]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

**Comment by Altonhe** [comment]
Deprecated: Non-static method Illuminate\Config\Repository::get() should not be called statically in /home/www/panel/app/Services/Boot.php on line 20

Fatal error: Uncaught Error: Using $this when not in object context in /home/www/panel/vendor/illuminate/config/Repository.php:49 Stack trace: #0 /home/www/panel/app/Services/Boot.php(20): Illuminate\Config\Repository::get('debug') #1 /home/www/panel/bootstrap/app.php(20): App\Services\Boot::setDebug() #2 /home/www/panel/public/index.php(7): require('/home/www/panel...') #3 {main} thrown in /home/www/panel/vendor/illuminate/config/Repository.php on line 49

**Comment by Altonhe** [comment]
PHP Version /PHP版本:7.00
ss-panel version/ ss-panel版本:v3
其他环境信息(Nginx,系统等):ngnix centos7

**Comment by Asheblog** [comment]
依赖库有问题，删除重建环境是最好解决办法了
