### ISSUE TITLE
安装报这个错

### ISSUE THREAD

**Issue by isanniu** [orvice/ss-panel#718]
Warning: require(/www/wwwroot/ss/public/../bootstrap/app.php): failed to open stream: No such file or directory in /www/wwwroot/ss/public/index.php on line 7

Fatal error: require(): Failed opening required '/www/wwwroot/ss/public/../bootstrap/app.php' (include_path='.:/www/server/php/56/lib/php') in /www/wwwroot/ss/public/index.php on line 7

**Comment by lifespy** [comment]
我也是，试了好长时间了。

**Comment by orvice** [comment]
composer安装依赖

建议使用docker
https://sspanel.xyz/docs/install/docker
