### ISSUE TITLE
注册用户成功后开通的端口问题

### ISSUE THREAD

**Issue by yixuexiaoao** [orvice/ss-panel#73]
我测试用户注册后开通的端口为7，连接不了，怎样修改注册用户的起始端口呢？
注册启用的端口是否为实时自动开通？还是需要手动开通呢？

**Comment by Acris** [comment]
user.sql中默认有一个用户了，默认的初始端口是5000，然后随机增长2~7，如果要修改起始端口只要修改该默认用户的端口即可。
启用的端口为自动开通。

**Comment by yixuexiaoao** [comment]
原来是我把以前的账号删除了，谢谢解答。
