### ISSUE TITLE
节点过多导致节点列表过慢甚至504

### ISSUE THREAD

**Issue by yylzcom** [orvice/ss-panel#735]
## 运行环境

* PHP Version /PHP版本: PHP 5.6.26-0+deb8u1
* ss-panel version/ ss-panel版本: 3.4.2 
* 其他环境信息(Nginx,系统等): nginx1.62

### Description of the problem / 问题描述

当sspanel添加超过20个节点的时候，打开节点列表页面会变得非常慢设置出现504超时错误，在nginx调整
        keepalive_timeout 55;
为：
        keepalive_timeout 180;
之后504超时的情况会得到环节，但是打开速度仍然不理想。

## 能否做一个分页功能，可以自定义每页的节点数量已改善此问题？
（如果已经有此功能请告知并稍微点拨一下在哪儿能设置，我的ss panel好久没更新了，粗略搜索了一下没找到类似问题，也没找到changelog，恕我愚钝）

**Comment by yylzcom** [comment]
#565 

应该和这个issue有关，正在尝试

**Comment by orvice** [comment]
@yylzcom 尝试添加下索引  或者试试看dev分之 https://github.com/orvice/ss-panel/tree/dev

**Comment by orvice** [comment]
最新版已经添加索引
