### ISSUE TITLE
/auth/login was not found on this server. 

### ISSUE THREAD

**Issue by darkwave3137** [orvice/ss-panel#736]
## 运行环境

* PHP Version /PHP7.1
* ss-panel version/ ss-panelv3
* 其他环境信息(Nginx,系统等):apache ubuntu16.04

### Description of the problem / 问题描述
请问vhost文件应该怎么写, 按照安装说明填写以后搭建之后提示/auth/login was not found on this server. 主页能进

**Comment by darkwave3137** [comment]
3.4.2

**Comment by darkwave3137** [comment]
@orvice

**Comment by orvice** [comment]
```
root /home/www/ss-panel/public;

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
    
```
