### ISSUE TITLE
配置地址和配置二维码中加上协议和混淆两个参数

### ISSUE THREAD

**Issue by wj985712588** [orvice/ss-panel#737]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.
节点列表的配置地址和配置二维码中如何加上协议和混淆两个参数

**Comment by orvice** [comment]
@wj985712588 dev分之已经支持ssr 二维码

**Comment by orvice** [comment]
https://github.com/orvice/ss-panel/releases/tag/v4beta1
