### ISSUE TITLE
多节点流量记录以及流量问题？

### ISSUE THREAD

**Issue by lingdonggzs** [orvice/ss-panel#738]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: PHP7
* ss-panel version/ ss-panel版本:ss-panel 3.4.5
* 其他环境信息(Nginx,系统等):Centos7 Nginx

### Description of the problem / 问题描述
在这里输入描述信息:
面板近期新增节点，配置正常
但发现流量记录会出现使用节点A，流量记录里面也有节点B的流量消耗记录
我请问是记录问题还是实际多节点或同时消耗流量之类的，类似与负载均衡么？
若不是请问可有处理思路或方法，多谢！

**Comment by orvice** [comment]
确认下真的没有用B节点？

**Comment by lingdonggzs** [comment]
问题描述错别字修正：在使用节点A的情况下，流量记录也会出现节点B的流量记录，不知道是流量记录的问题还是多个节点的情况下会同时走流量？或者是负载均衡了？
问题确认:多次确认和测试，单独使用节点A流量记录会有节点B的，单独使用节点B记录会有节点A的
多谢

**Comment by orvice** [comment]
你使用什么客户端，有些客户端有负载均衡，或者自动测速，会产生流量记录的

**Comment by lingdonggzs** [comment]
电脑端：shadowsocks 4.0.4  https://github.com/shadowsocks/shadowsocks-windows
手机端：wingy
负载均衡未开，没有自动测速

**Comment by orvice** [comment]
B出现的流量大妈

**Comment by lingdonggzs** [comment]
测试的时候用节点A访问google搜索几个网页，流量记录里节点B的流量比节点A还大

**Comment by orvice** [comment]
@lingdonggzs 检查下配置吧，或者关掉B节点，使用A一段时间确认是否真的没有B流量。

**Comment by lingdonggzs** [comment]
好的，我关掉B节点看看；谢谢

**Comment by lingdonggzs** [comment]
@orvice 经过今天整天的测试：
1.关闭节点B的情况下，使用节点A仅有节点A的流量
2.开启节点B的情况下，使用节点A会出现节点B的流量
3.新增节点C测试的情况下，使用节点A会出现节点B和节点C的流量
4.配置检查没发现什么，node_id和面板内的也一致
