### ISSUE TITLE
v4项目有安装文档吗

### ISSUE THREAD

**Issue by nishuo** [orvice/ss-panel#739]
## 运行环境

* PHP Version /PHP版本: 7.1.15
* ss-panel version/ ss-panel版本:v4
* 其他环境信息(Nginx,系统等):nginx 1.1

### Description of the problem / 问题描述
v4项目有安装文档吗，看到发布了beta1版本

**Comment by orvice** [comment]
https://sspanel.xyz/docs/install/docker
