### ISSUE TITLE
问一个小白问题

### ISSUE THREAD

**Issue by nishuo** [orvice/ss-panel#740]
## 运行环境

* PHP Version /PHP版本: 7.1.15
* ss-panel version/ ss-panel版本:v4 beta1
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述

- 在执行php composer.phar install安装的时候出现了
**Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.**
这个提示是否对我的ss-panel有影响？

- 为什么git clone下来的目录没有包含 .env.example配置文件，需要手动下载导入么？

**Comment by orvice** [comment]
` ls -al `看下有没有

**Comment by nishuo** [comment]
请问新安装的v4面板如何添加管理员账号？

**Comment by orvice** [comment]
``` php xcat createAdmin <email> <password> ```

**Comment by nishuo** [comment]
![Image of Yaktocat](![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
有错误 是需要配置redis吗

**Comment by orvice** [comment]
redis必须

**Comment by nishuo** [comment]
已经好了。

v4正式版大概什么时候可以发布？

**Comment by nishuo** [comment]
@orvice

**Comment by orvice** [comment]
master以及docker最新版均已经可以正常使用了
