### ISSUE TITLE
添加邀请码错误。

### ISSUE THREAD

**Issue by wj985712588** [orvice/ss-panel#743]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:ss-panel v4
* 其他环境信息(Nginx,系统等):nginx

### Description of the problem / 问题描述
在这里输入描述信息.
管理员添加邀请码时出错。

**Comment by wj985712588** [comment]
目前找到问题，v4邀请码的数据表的结构和v3的不一样。

**Comment by orvice** [comment]
邀请码结构没有变化的，你看下storage/logs/fish.log日志内容

**Comment by wj985712588** [comment]
###  **ss-panel 4.ERROR: SQLSTATE[22007]: # Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'updated_at' at row 1$**
 ss-panel 4.ERROR: #0 /data/wwwroot/ss-panel/vendor/illuminate/database/Connection.php 607 [] []
 ss-panel 4.ERROR: #1 /data/wwwroot/ss-panel/vendor/illuminate/database/Connection.php 450 [] []
 ss-panel 4.ERROR: #2 /data/wwwroot/ss-panel/vendor/illuminate/database/Connection.php 404 [] []
 ss-panel 4.ERROR: #3 /data/wwwroot/ss-panel/vendor/illuminate/database/Query/Processors/Processor.php 32 [] []
 ss-panel 4.ERROR: #4 /data/wwwroot/ss-panel/vendor/illuminate/database/Query/Builder.php 2138 [] []
 ss-panel 4.ERROR: #5 /data/wwwroot/ss-panel/vendor/illuminate/database/Eloquent/Builder.php 1247 [] []
 ss-panel 4.ERROR: #6 /data/wwwroot/ss-panel/vendor/illuminate/database/Eloquent/Model.php 684 [] []
 ss-panel 4.ERROR: #7 /data/wwwroot/ss-panel/vendor/illuminate/database/Eloquent/Model.php 684 [] []
 ss-panel 4.ERROR: #8 /data/wwwroot/ss-panel/vendor/illuminate/database/Eloquent/Model.php 649 [] []
 ss-panel 4.ERROR: #9 /data/wwwroot/ss-panel/vendor/illuminate/database/Eloquent/Model.php 518 [] []
 ss-panel 4.ERROR: #10 /data/wwwroot/ss-panel/app/Controllers/Api/Admin/InviteController.php 42 [] []
 ss-panel 4.ERROR: #11 store  App\Controllers\Api\Admin\InviteController  [] []
 ss-panel 4.ERROR: #12 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php 41 [] []
 ss-panel 4.ERROR: #13 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/Route.php 344 [] []
 ss-panel 4.ERROR: #14 /data/wwwroot/ss-panel/app/Middleware/Admin.php 21 [] []
 ss-panel 4.ERROR: #15 __invoke  App\Middleware\Admin  [] []
 ss-panel 4.ERROR: #16 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/DeferredCallable.php 43 [] []
 ss-panel 4.ERROR: #17 __invoke  Slim\DeferredCallable  [] []
 ss-panel 4.ERROR: #18 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php 73 [] []
 ss-panel 4.ERROR: #19 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php 122 [] []
 ss-panel 4.ERROR: #20 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/Route.php 316 [] []
 ss-panel 4.ERROR: #21 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/App.php 476 [] []
 ss-panel 4.ERROR: #22 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php 122 [] []
 ss-panel 4.ERROR: #23 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/App.php 370 [] []
 ss-panel 4.ERROR: #24 /data/wwwroot/ss-panel/vendor/slim/slim/Slim/App.php 295 [] []
 ss-panel 4.ERROR: #25 /data/wwwroot/ss-panel/public/index.php 10 [] []

**Comment by orvice** [comment]
你是mysql5.7了吧
修改下两个time字段的默认值
