### ISSUE TITLE
do.php 执行失败

### ISSUE THREAD

**Issue by hupantingxue** [orvice/ss-panel#75]
<?php
/*
 * ䷾K轝¢佈«修彔¹
 */
//medoo
require_once 'class/medoo.class.php';
$db = new medoo([    //  这一行提示错误
    // required
    'database_type' => DB_TYPE,
    'database_name' => DB_DBNAME,
    'server' => DB_HOST,
    'username' => DB_USER,
    'password' => DB_PWD,
    'charset' => DB_CHARSET,

    // optional
    'port' => 3306,
    // driver_option for connection, read more from http://www.php.net/manual/en/pdo.setattribute.php
    'option' => [
        PDO::ATTR_CASE => PDO::CASE_NATURAL
    ]
]);
提示如下错误：
Parse error:  syntax error, unexpected '[', expecting ')' in /etc/shadowsocks/ss-panel-master/lib/do.php on line

**Comment by orvice** [comment]
php要求5.4+

**Comment by hupantingxue** [comment]
嗯，不过可以规避这个问题，将[]修改为：array()就可以了。

**Comment by orvice** [comment]
升级php吧，

**Comment by hupantingxue** [comment]
用lnmp装的，不想折腾了，我直接改源代码算了。
