### ISSUE TITLE
把SS-panel放在SAE上如何配置数据库连接

### ISSUE THREAD

**Issue by sptime** [orvice/ss-panel#84]
如题

**Comment by lasyman** [comment]
在配置文件你填入你需要访问的数据库地址、用户、密码，打开sae提供的链接访问ss-panel，会提示数据库连接失败，报出sae ip，在你的数据库里允许此ip访问即可。
PS：sae内部数据库无法提供外部访问，我测试使用外部数据库sae访问很慢。
