### ISSUE TITLE
每月流量清空问题。

### ISSUE THREAD

**Issue by thank243** [orvice/ss-panel#86]
月初观察了下，系统并没有自动执行cron.PHP来清空用户流量，请问是需要写入系统crontab还是php程序我没设置好？

**Comment by tutugreen** [comment]
你不是一个人，我也觉得怪怪的，后来手动改了
2015-4-3 下午4:18于 "thank243" <notifications@github.com>写道：

**Comment by thank243** [comment]
嗯，后来装了php cli 加入系统计划了

发自我的 iPhone
