### ISSUE TITLE
好像可以繞過檢查機制 以同樣的用戶名 email 密碼註冊N個帳號

### ISSUE THREAD

**Issue by akw28888** [orvice/ss-panel#91]
剛發現有人以同樣的username email和password連續註冊了10個帳戶
推測應該還是以同一個邀請碼註冊的
不知道是不是繞過了用戶名的檢查機制?

https://ssnode.net ssnode taiwan站長 上

**Comment by orvice** [comment]
版本多少？
今天更新了V2 重写了注册登录等，建议更新下

**Comment by akw28888** [comment]
已更新至v2.0.1 thanks.
