### ISSUE TITLE
升级2.2.3后无法登陆管理面板

### ISSUE THREAD

**Issue by PlaneV** [orvice/ss-panel#99]
升级2.2.3后，退出登陆的情况下，直接访问admin文件夹index.php会重定向到user/login.php，正确登陆以后还是不能访问管理面板。

**Comment by PlaneV** [comment]
问题已经解决了，原来是有个新的数据表需要导入。导入以后就可以解决了

**Comment by akw28888** [comment]
同樣無法登入
該導入的sql表已全部導入
但是提示帳戶或者密碼錯誤(phpmyadmin裡面看過都是正確的)

**Comment by orvice** [comment]
ss_user_admin 表导入了么？

要把user表的uid添加到此表里面去，默认uid为1的可以登录

**Comment by akw28888** [comment]
有import 
啊? 現在是看user表麼 不看admin表?

**Comment by orvice** [comment]
需要此表
https://github.com/orvice/ss-panel/blob/master/sql/ss_user_admin.sql

**Comment by orvice** [comment]
ss_admin 已经不需要了。。。
ss_user_admin 里面包含了管理员的uid
